*This file creates group id for investor name: conditional on city
set more off
cd "$root_data"
gen id=_n
sort id
save tempc_1, replace

cd "$root_do"
global x="invname_hold_temp"
do Remove_Trailing_Geo.do
replace $x=subinword($x,"accid","accident",.)
replace $x=subinword($x,"acc","accident",.)
replace $x=subinword($x,"ft","and",.)
replace $x=subinword($x,"fc","and",.)
replace $x=subinword($x,"jc","and",.)
replace $x=subinword($x,"american samoa","association",.)
replace $x=subinword($x,"asso","association",.)
replace $x=subinword($x,"assn","association",.)
replace $x=subinword($x,"assoc","association",.)
replace $x=subinword($x,"assocn","association",.)
replace $x=subinword($x,"american samoa","assurance",.)
replace $x=subinword($x,"assur","assurance",.)
replace $x=subinword($x,"assn","assurance",.)
replace $x=subinword($x,"ass","assurance",.)
replace $x=subinword($x,"ave","avenue",.)
replace $x=subinword($x,"br","branch",.)
replace $x=subinword($x,"cann","canada",.)
replace $x=subinword($x,"california","canada",.)
replace $x=subinword($x,"canadian","canada",.)
replace $x=subinword($x,"cent","cents",.)
replace $x=subinword($x,"connecticut ty","county",.)
replace $x=subinword($x,"dep$","deposit",.)
replace $x=subinword($x,"l ire","fire",.)
replace $x=subinword($x,"erie insurance","fire insurance",.)
replace $x=subinword($x,"germania","german",.)
replace $x=subinword($x,"guar ","guaranty",.)
replace $x=subinword($x,"guar","guaranty",.)
replace $x=subinword($x,"illinois inois","illinois",.)
replace $x=subinword($x,"indiana the town","in the town",.)
replace $x=subinword($x,"inst","institution",.)
replace $x=subinword($x,"institute","institution",.)
replace $x=subinword($x,"titution","institution",.)
replace $x=subinword($x,"ins","insurance",.)
replace $x=subinword($x,"insur","insurance",.)
replace $x=subinword($x,"liab","liability",.)
replace $x=subinword($x,"ltd","limited",.)
replace $x=subinword($x,"manufacturing","manufacturers",.)
replace $x=subinword($x,"mfgrs","manufacturers",.)
replace $x=subinword($x,"mfgr","manufacturers",.)
replace $x=subinword($x,"mfrs","manufacturers",.)
replace $x=subinword($x,"manufacturer","manufacturers",.)
replace $x=subinword($x,"massachusetts r ine","marine",.)
replace $x=subinword($x,"mer","mercantile",.)
replace $x=subinword($x,"merchants","mercantiles",.)
replace $x=subinword($x,"mechanic","merchants",.)
replace $x=subinword($x,"mort","mortgage",.)
replace $x=subinword($x,"mut","mutual",.)
replace $x=subinword($x,"nat","national",.)
replace $x=subinword($x,"no","north",.)
replace $x=subinword($x,"pittsburg","pittsburgh",.)
replace $x=subinword($x,"provident","providence",.)
replace $x=subinword($x,"re insurance","reinsurance",.)
replace $x=subinword($x,"sav","savings",.)
replace $x=subinword($x,"savng","savings",.)
replace $x=subinword($x,"savngs","savings",.)
replace $x=subinword($x,"savins","savings",.)
replace $x=subinword($x,"savin","savings",.)
replace $x=subinword($x,"saving","savings",.)
replace $x=subinword($x,"securities","security",.)
replace $x=subinword($x,"soc","society",.)
replace $x=subinword($x,"sup court","supreme court",.)
replace $x=subinword($x,"trust title","title trust",.)
replace $x=subinword($x,"trading","traders",.)
replace $x=subinword($x,"tr","trust",.)
replace $x=subinword($x,"trut","trust",.)
replace $x=subinword($x,"trustees","trust",.)
replace $x=subinword($x,"trustee","trust",.)
replace $x=subinword($x,"us","united states",.)
replace $x=subinword($x,"u s a","us",.)
replace $x=subinword($x,"u s","us",.)
replace $x=subinword($x,"us a","us",.)
replace $x=subinword($x,"us","us",.)
replace $x=subinword($x,"usa","us",.)
replace $x=subinword($x,"and its vicinity","vicinity",.)
replace $x=subinword($x,"its vicinity","vicinity",.)
replace $x=subinword($x,"vicin","vicinity",.)
replace $x=subinword($x,"vic","vicinity",.)
replace $x=subinword($x,"assurance","insurance",.)
replace $x=subinword($x,"of the united states of america","",.)
replace $x=subinword($x,"indiana the county lycoming","",.)
replace $x=subinword($x,"indiana the town","",.)
replace $x=subinword($x,"indiana the towns","",.)
replace $x=subinword($x,"on the hudson","",.)
replace $x=subinword($x,"indiana town","",.)
replace $x=subinword($x,"united states","",.)
replace $x=subinword($x,"of us","",.)
replace $x=subinword($x,"savings ","",.)
replace $x=subinword($x,"supreme council","",.)
replace $x=subinword($x,"of city","",.)
replace $x=subinword($x,"the town","",.)
replace $x=subinword($x,"america","",.)
replace $x=subinword($x,"indiana","",.)
replace $x=subinword($x,"and","",.)
replace $x=subinword($x,"inc","",.)
replace $x=subinword($x,"the","",.)
replace $x=subinword($x,"the","",.)
replace $x=subinword($x,"company","",.)
replace $x=subinword($x,"branch","",.)
replace $x=subinword($x,"phila","",.)
replace $x=subinword($x,"at","",.)
replace $x=subinword($x,"of","",.)
replace $x=subinword($x,"for","",.)
replace $x=subinword($x,"","",.)
replace $x=subinword($x,"life","",.)
replace $x=subinword($x,"department","",.)
replace $x=subinword($x,"mutual","",.)
replace $x=subinword($x,"marine","",.)
replace $x=subinword($x,"indiana","",.)
replace $x=subinword($x,"vicinity","",.)
replace $x=subinword($x,"its","",.)
replace $x=subinword($x,"in","",.)
replace $x=subinword($x,"institution","",.)
replace $x=subinword($x,"institute","",.)
replace $x=subinword($x,"security","",.)
replace $x=subinword($x,"securities","",.)
replace $x=subinword($x,"insurance","",.)
replace $x=subinword($x,"trust","",.)
replace $x=subinword($x,"indemnity","",.)
replace $x=subinword($x,"accident","",.)
replace $x=subinword($x,"association","",.)
replace $x=subinword($x,"assurance","",.)
replace $x=subinword($x,"trustees","",.)
replace $x=subinword($x,"for","",.)
replace $x=subinword($x,"loss","",.)
replace $x=subinword($x,"by","",.)
replace $x=subinword($x,"society","",.)
replace $x=subinword($x,"fund","",.)
replace $x=subinword($x,"house","",.)
replace $x=subinword($x,"houses","",.)
replace $x=subinword($x,"location","",.)
replace $x=subinword($x,"title","",.)
replace $x=subinword($x,"deposit","",.)
replace $x=subinword($x,"discount","",.)
replace $x=subinword($x,"legion","",.)
replace $x=subinword($x,"union","",.)
replace $x=subinword($x,"surety","",.)
replace $x=subinword($x,"vounty","",.)
replace $x=subinword($x,"vicin","",.)
replace $x=subinword($x,"safe","",.)
replace $x=subinword($x,"savings","",.)
replace $x=subinword($x,"safe","",.)
replace $x=subinword($x,"deposit","",.)
replace $x=subinword($x,"liability","",.)
replace $x=subinword($x,"limited","",.)
replace $x=subinword($x,"home","",.)
replace $x=subinword($x,"commercial","",.)
replace $x=subinword($x,"state","",.)
replace $x=subinword($x,"america","",.)
replace $x=subinword($x,"annuity","",.)
replace $x=subinword($x,"league","",.)
replace $x=subinword($x,"the","",.)
replace $x=subinword($x,"on","",.)
replace $x=subinword($x,"fire","",.)
replace $x=subinword($x,"it","",.)
replace $x=subinword($x,"bank","",.)
replace $x=subinword($x,"national","",.)
replace $x=subinword($x,"us","",.)
replace $x=subinword($x,"county","",.)
replace $x=subinword($x,"city","",.)
replace $x=subinword($x,"st","",.)
replace $x=subinword($x,"us","",.)
replace $x=subinword($x,"guaranty","",.)
replace $x=subinword($x,"with","",.)
replace $x=subinword($x,"society","",.)
replace $x=subinword($x,"savings","",.)
replace $x=subinword($x,"loss","",.)
replace $x=subinword($x,"by","",.)
replace $x=subinword($x,"fund","",.)
replace $x=subinword($x,"trading","",.)
replace $x=subinword($x,"assurance","",.)
replace $x=subinword($x,"association","",.)
replace $x=subinword($x,"legion","",.)
replace $x=subinword($x,"league","",.)
replace $x=subinword($x,"insuring","",.)
replace $x=subinword($x,"house","",.)
replace $x=subinword($x,"houses","",.)
replace $x=subinword($x,"surety","",.)
replace $x=subinword($x,"casualty","",.)
replace $x=subinword($x,"from","",.)
replace $x=subinword($x,"the","",.)
replace $x=subinword($x,"insurance","",.)
replace $x=subinword($x,"loss","",.)
replace $x=subinword($x,"assurance","association",.)
replace $x=subinword($x,"canadian","canada",.)
replace $x=subinword($x,"california","canada",.)
replace $x=subinword($x,"commerce","commercial",.)
replace $x=subinword($x,"germania","german",.)
replace $x=subinword($x,"insurance","institution",.)
replace $x=subinword($x,"assurance","insurance",.)
replace $x=subinword($x,"merchant","mercantile",.)
replace $x=subinword($x,"mechanic","mercantile",.)
replace $x=subinword($x,"no","north",.)
replace $x=subinword($x,"provident","providence",.)
replace $x=subinword($x,"insurance","",.)
replace $x=subinword($x,"trust","",.)
replace $x=subinword($x,"fund","",.)
replace $x=subinword($x,"bank","",.)
replace $x=subinword($x,"savings ","",.)
replace $x=subinword($x,"life","",.)
replace $x=subinword($x,"indemnity","",.)
replace $x=subinword($x,"accident","",.)
replace $x=subinword($x,"loss","",.)
replace $x=subinword($x,"house","",.)
replace $x=subinword($x,"title","",.)
replace $x=subinword($x,"surety","",.)
replace $x=subinword($x,"liability","",.)
replace $x=subinword($x,"home","",.)
replace $x=subinword($x,"annuity","",.)
replace $x=subinword($x,"fire","",.)
replace $x=subinword($x,"guaranty","",.)
replace $x=subinword($x,"loss","",.)
replace $x=subinword($x,"casualty","",.)
replace $x=subinword($x,"mutual","",.)
replace $x=subinword($x,"marine","",.)
replace $x=subinword($x,"deposit","",.)
replace $x=subinword($x,"discount","",.)
replace $x=subinword($x,"safe","",.)
replace $x=subinword($x,"commercial","",.)
replace $x=subinword($x,"limited","",.)
replace $x=subinword($x,"security","",.)
replace $x=subinword($x,"indiana the county lycoming","",.)
replace $x=subinword($x,"of the united states of america","",.)
replace $x=subinword($x,"of united states","",.)
replace $x=subinword($x,"united states$","",.)
replace $x=subinword($x,"united states","",.)
replace $x=subinword($x,"america","",.)
replace $x=subinword($x,"the","",.)
replace $x=subinword($x,"in","",.)
replace $x=subinword($x,"city","",.)
replace $x=subinword($x,"and","",.)
replace $x=subinword($x,"at","",.)
replace $x=subinword($x,"of","",.)
replace $x=subinword($x,"for","",.)
replace $x=subinword($x,"indiana","",.)
replace $x=subinword($x,"its","",.)
replace $x=subinword($x,"institution","",.)
replace $x=subinword($x,"by","",.)
replace $x=subinword($x,"on","",.)
replace $x=subinword($x,"it","",.)
replace $x=subinword($x,"us","",.)
replace $x=subinword($x,"st","",.)
replace $x=subinword($x,"with","",.)
replace $x=subinword($x,"on","",.)
replace $x=subinword($x,"department","",.)
replace $x=subinword($x,"association","",.)
replace $x=subinword($x,"legion","",.)
replace $x=subinword($x,"union","",.)
replace $x=subinword($x,"league","",.)
replace $x=subinword($x,"national","",.)
replace $x=subinword($x,"county","",.)
replace $x=subinword($x,"city","",.)
replace $x=subinword($x,"town","",.)
replace $x=subinword($x,"supreme council","",.)
replace $x=subinword($x,"indiana","",.)
replace $x=subinword($x,"vicinity","",.)
replace $x=subinword($x,"society","",.)
replace $x=subinword($x,"location","",.)
replace $x=subinword($x,"county","",.)
replace $x=subinword($x,"vicin","",.)
replace $x=subinword($x,"state","",.)
replace $x=subinword($x,"township","",.)
replace $x=subinword($x,"union","",.)
replace $x=subinword($x,"exchange","",.)
replace $x=subinword($x,"secured","",.)
replace $x=subinword($x,"upper lower sancon","",.)
replace $x=subinword($x,"office","",.)
replace $x=strtrim($x)
replace $x=stritrim($x)

gen investor_city_use=cond(investor_city_2!="",investor_city_2,investor_city_1)
bysort investor_city_use: strgroup $x, gen(group_dummy) thresh(1) norm(none) force
drop investor_city_use

cd "$root_data"
save tempc_2,replace

use tempc_1, clear
merge m:n id using tempc_2, gen(merge_dummy)
sort investor_city_temp group_dummy

/*
duplicates drop invname_hold_temp, force
duplicates tag group_dummy, gen(count_dummy)
gsort -count_dummy investor_city_temp group_dummy
browse invname_hold_temp group_dummy count_dummy investor_city_temp invname_hold_orig

duplicates drop invname_hold_temp,force
duplicates tag group_dummy, gen(count_dummy)
replace count_dummy=0 if count_dummy>1000
replace count_dummy=0 if group_dummy==.
gsort -count_dummy group_dummy
count if count_dummy>0 & count_par==0 & count_par2==0
*browse cname_hold_temp count_geo2 group_geo2 //if count_par==0 & count_par2==0
*/
erase tempc_1.dta
erase tempc_2.dta
label var group_dummy "Group id for investor name"
rename group_dummy group_investor
cap drop id
cap drop merge_dummy
/*
cd "$root_data"
use Holdings_Data_InvestorClean.dta, clear
sort investor_city_temp invname_hold_temp
keep if industry~="Government"
browse investor_city_temp invname_hold_temp group_dummy invname_hold_orig

duplicates drop investor_city_temp investor_state_temp, force
browse investor_city_temp investor_state_temp if (strpos(investor_city_temp,"/") & !strpos(investor_state_temp,"/"))|(!strpos(investor_city_temp,"/") & strpos(investor_state_temp,"/"))
