/*
cd "D:\Dropbox\Bond Rating\Code and Data\dta"
use Holdings_Investor_LocClean.dta,clear

cd "D:\Dropbox\Bond Rating\Investor_Name_Loc\temp"
save Holdings_Investor_Nametemp.dta,replace

browse invname_hold_orig invname_hold_temp book_year_hold coupon_hold cname_hold_temp if regexm(invname_hold_orig,"Savings Bank") & investor_city_hold=="Meriden" 
& cname_hold_orig=="ROCK ISLAND, ARKANSAS AND LOUISIANA"


browse invname_hold_orig invname_hold_temp investor_city_temp investor_state_hold book_year_hold cname_hold_temp coupon_hold class_hold 
if regexm(invname_hold_orig,"^[a-z]")

/*cname_hold_orig=="CITY AND MEMPHIS RAILWAY AND BRIDGE" */

browse invname_hold_orig invname_hold_temp book_year_hold coupon_hold cname_hold_temp if strpos(invname_hold_temp,"home fire") & !strpos(invname_hold_orig,"Fire")
*/
global root_data="D:\Dropbox\Bond Rating\Code and Data\dta"
global root_do="D:\Dropbox\Bond Rating\Code and Data\do_investor_loc"

cd "$root_data"
use Holdings_Investor_LocClean.dta, clear
cd "$root_do"
do Replace_List_Investor.do
global x="invname_hold_temp"
*do Remove_Trailing_Geo.do
replace invname_hold_temp=strtrim(invname_hold_temp)
replace invname_hold_temp=stritrim(invname_hold_temp)
cd "$root_data"

*Revise state
replace investor_city_temp="boston" if strpos(investor_state_temp,"massachusetts") & strpos(investor_city_temp,"new york")
*Some additional cleaning
*1. Clean the case that number of investor city & state don't match
replace investor_state_temp="germany/new york" if investor_city_temp=="aixlachapelle/new york" & investor_state_temp=="new york"
replace investor_state_temp="germany/new york" if investor_city_temp=="aixlachapelle/new york" & investor_state_temp=="germany"
replace investor_state_temp="holland/new york" if investor_city_temp=="albany/new york" & investor_state_temp=="new york"
replace investor_state_temp="holland/new york" if investor_city_temp=="amsterdam/new york" & investor_state_temp=="new york"
replace investor_state_temp="holland/new york" if investor_city_temp=="amsterdam/new york" & investor_state_temp=="holland"
replace investor_state_temp="holland/new york" if investor_city_temp=="amsterdam/new york city" & investor_state_temp=="holland"
replace investor_state_temp="germany/new york" if investor_city_temp=="cologne/new york" & investor_state_temp=="new york"
replace investor_state_temp="scotland/connecticut" if investor_city_temp=="edinburgh/hartford" & investor_state_temp=="connecticut"
replace investor_state_temp="scotland/new york" if investor_city_temp=="edinburgh/hartford" & investor_state_temp=="new york"
replace investor_state_temp="scotland/canada" if investor_city_temp=="edinburgh/montreal" & investor_state_temp=="scotland"
replace investor_state_temp="scotland/new york" if investor_city_temp=="edinburgh/new york" & investor_state_temp=="new york"
replace investor_state_temp="scotland/new york" if investor_city_temp=="edinburgh/new york" & investor_state_temp=="scotland"
replace investor_state_temp="germany/new york" if investor_city_temp=="frankfort on main/new york" & investor_state_temp=="new york"
replace investor_state_temp="germany/new york" if investor_city_temp=="frankfort/new york" & investor_state_temp=="new york"
replace investor_state_temp="germany/new york" if investor_city_temp=="frankfort/new york" & investor_state_temp=="germany"
replace investor_state_temp="sweden/new york" if investor_city_temp=="gothenburg/new york" & investor_state_temp=="new york"
replace investor_state_temp="sweden/new york" if investor_city_temp=="gothenburg/new york" & investor_state_temp=="sweden"
replace investor_state_temp="germany/new york" if investor_city_temp=="hamburg/new york" & investor_state_temp=="new york"
replace investor_state_temp="germany/new york" if investor_city_temp=="hamburg/new york city" & investor_state_temp=="new york"
replace investor_state_temp="england/connecticut" if investor_city_temp=="liverpool/hartford" & investor_state_temp=="connecticut"
replace investor_state_temp="england/canada" if investor_city_temp=="liverpool/montreal" & investor_state_temp=="england"
replace investor_state_temp="england/new york" if investor_city_temp=="liverpool/new york" & investor_state_temp=="new york"
replace investor_state_temp="england/new york" if investor_city_temp=="liverpool/new york" & investor_state_temp=="england"
replace investor_state_temp="england/new jersey" if investor_city_temp=="liverpool/new york" & investor_state_temp=="new jersey"
replace investor_state_temp="england/new york" if investor_city_temp=="liverpool/new york city" & investor_state_temp=="new york"
replace investor_state_temp="great britain/new york" if investor_city_temp=="london and edinburgh/new york" & investor_state_temp=="new york"
replace investor_state_temp="great britain/new york" if investor_city_temp=="london and edinburgh/new york" & investor_state_temp=="great britain"
replace investor_state_temp="england/massachusetts" if investor_city_temp=="london/boston" & investor_state_temp=="england"
replace investor_state_temp="england/illinois" if investor_city_temp=="london/chicago" & investor_state_temp=="illinois"
replace investor_state_temp="england/canada" if investor_city_temp=="london/montreal" & investor_state_temp=="england"
replace investor_state_temp="england/new york" if investor_city_temp=="london/new york" & investor_state_temp=="great britain"
replace investor_state_temp="england/new york" if investor_city_temp=="london/new york" & investor_state_temp=="new york"
replace investor_state_temp="england/new york" if investor_city_temp=="london/new york city" & investor_state_temp=="england"
replace investor_state_temp="england/canada" if investor_city_temp=="london/ontario" & investor_state_temp=="canada"
replace investor_state_temp="england/canada" if investor_city_temp=="london/toronto" & investor_state_temp=="canada"
replace investor_state_temp="england/canada" if investor_city_temp=="london/toronto" & investor_state_temp=="england"
replace investor_state_temp="germany/new york" if investor_city_temp=="mannheim/new york" & investor_state_temp=="new york"
replace investor_state_temp="germany/connecticut" if investor_city_temp=="munich/hartford" & investor_state_temp=="connecticut"
replace investor_state_temp="germany/new york" if investor_city_temp=="munich/new york" & investor_state_temp=="new york"
replace investor_state_temp="germany/new york" if investor_city_temp=="munich/new york" & investor_state_temp=="germany"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="scotland/pennsylvania"
replace investor_state_temp="england/new york" if investor_city_temp=="norwich/new york" & investor_state_temp=="new york"
replace investor_state_temp="england/new york" if investor_city_temp=="norwich/new york" & investor_state_temp=="england"
replace investor_state_temp="france/new york" if investor_city_temp=="paris/new york" & investor_state_temp=="new york"
replace investor_state_temp="france/rhode island" if investor_city_temp=="paris/providence" & investor_state_temp=="rhode island"
replace investor_state_temp="france/rhode island" if investor_city_temp=="paris/providence" & investor_state_temp=="france"
replace investor_state_temp="rhode island" if investor_city_temp=="pawtucket" & investor_state_temp=="england/new york"
replace investor_state_temp="scotland/new york" if investor_city_temp=="perth/new york" & investor_state_temp=="new york"
replace investor_state_temp="scotland/pennsylvania" if investor_city_temp=="perth/philadelphia" & investor_state_temp=="new york"
replace investor_state_temp="scotland/pennsylvania" if investor_city_temp=="perth/philadelphia" & investor_state_temp=="new hampshire"
replace investor_state_temp="scotland/pennsylvania" if investor_city_temp=="perth/philadelphia" & investor_state_temp=="pennsylvania"
replace investor_state_temp="scotland/pennsylvania" if investor_city_temp=="perth/philadelphia" & investor_state_temp=="scotland"
replace investor_city_temp="st petersburg/new york" if investor_city_temp=="st petersburg/russia" & investor_state_temp=="new york/new york"
replace investor_state_temp="china/new york" if investor_city_temp=="shanghai/new york city" & investor_state_temp=="new york"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg/new york" & investor_state_temp=="new york"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg/new york" & investor_state_temp=="russia"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg/new york" & investor_state_temp=="new hampshire"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg/new york city" & investor_state_temp=="new york"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg/new york city" & investor_state_temp=="russia"
replace investor_state_temp="poland/illinois" if investor_city_temp=="stettin/chicago" & investor_state_temp=="illinois"
replace investor_state_temp="poland/new york" if investor_city_temp=="stettin/new york" & investor_state_temp=="new york"
replace investor_state_temp="sweden/new york" if investor_city_temp=="stockholm/new york" & investor_state_temp=="new york"
replace investor_state_temp="sweden/new york" if investor_city_temp=="stockholm/new york city" & investor_state_temp=="sweden"
replace investor_state_temp="canada/new york" if investor_city_temp=="toronto/new york" & investor_state_temp=="new york"
replace investor_state_temp="canada/new york" if investor_city_temp=="waterloo/ontario" & investor_state_temp=="canada"
replace investor_state_temp="england/canada" if investor_city_temp=="york/montreal" & investor_state_temp=="england"
replace investor_state_temp="switzerland/new york" if investor_city_temp=="zurich/new york" & investor_state_temp=="new york"
replace investor_state_temp="england/new york" if investor_city_temp=="york/new york" & investor_state_temp=="new york/new york"
replace investor_state_temp="england/new york" if investor_city_temp=="london/new york" & investor_state_temp=="new york/new york"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg/new york" & investor_state_temp=="new york/new york"
replace investor_city_temp="philadelphia" if invname_hold_orig=="Aldine Trust Company" & investor_city_temp==""
replace investor_city_temp="boston" if invname_hold_orig=="Columbian National Life Insurance Company" & investor_city_temp==""
replace investor_city_temp="hartford" if invname_hold_orig=="Hartford Steam Boiler Inspection and Insurance Co. (Series A and B)" & investor_city_temp==""
replace investor_city_temp="london/toronto" if invname_hold_orig=="London Mutual Fire Insurance Company of Canada. Toronto" & investor_city_temp==""
replace investor_city_temp="baltimore" if invname_hold_orig=="Maryland Life Insurance Company" & investor_city_temp==""
replace investor_city_temp="boston" if invname_hold_orig=="metropolitan Life Insurance Company" & investor_city_temp==""
replace investor_city_temp="new york" if invname_hold_orig=="Mutual Life Insurance Co." & investor_city_temp==""
replace investor_city_temp="new york" if invname_hold_orig=="New York Life Insurance & Trust Company. New York. N. Y." & investor_city_temp==""
replace investor_city_temp="pawtucket" if invname_hold_orig=="Pawtucket Institution for Savings." & investor_city_temp==""
replace investor_city_temp="stettin" if invname_hold_orig=="Prussian National Ins. Co. Stettin" & investor_city_temp==""
replace investor_city_temp="danbury" if invname_hold_orig=="Savings Bank of Danbury" & investor_city_temp==""
replace investor_city_temp="town of union" if invname_hold_orig=="Weehawken Trust Company" & investor_city_temp==""
replace investor_state_temp="pennsylvania" if invname_hold_orig=="Aldine Trust Company" & investor_state_temp==""
replace investor_state_temp="massachusetts" if invname_hold_orig=="Columbian National Life Insurance Company" & investor_state_temp==""
replace investor_state_temp="connecticut" if invname_hold_orig=="Hartford Steam Boiler Inspection and Insurance Co. (Series A and B)" & investor_state_temp==""
replace investor_state_temp="england/canada" if invname_hold_orig=="London Mutual Fire Insurance Company of Canada. Toronto" & investor_state_temp==""
replace investor_state_temp="maryland" if invname_hold_orig=="Maryland Life Insurance Company" & investor_state_temp==""
replace investor_state_temp="massachusetts" if invname_hold_orig=="metropolitan Life Insurance Company" & investor_state_temp==""
replace investor_state_temp="new york" if invname_hold_orig=="Mutual Life Insurance Co." & investor_state_temp==""
replace investor_state_temp="new york" if invname_hold_orig=="New York Life Insurance & Trust Company. New York. N. Y." & investor_state_temp==""
replace investor_state_temp="rhode island" if invname_hold_orig=="Pawtucket Institution for Savings." & investor_state_temp==""
replace investor_state_temp="germany" if invname_hold_orig=="Prussian National Ins. Co. Stettin" & investor_state_temp==""
replace investor_state_temp="connecticut" if invname_hold_orig=="Savings Bank of Danbury" & investor_state_temp==""
replace investor_state_temp="new jersey" if invname_hold_orig=="Weehawken Trust Company" & investor_state_temp==""

* Clean for incorrect city-state matches
replace investor_state_temp="germany/new york" if investor_city_temp=="aixlachapelle" & investor_state_temp=="new york"
replace investor_state_temp="germany/new york" if investor_city_temp=="aixlachapelle" & investor_state_temp=="germany"
replace investor_state_temp="california" if investor_city_temp=="alameda" & investor_state_temp=="new jersey"
replace investor_state_temp="california" if investor_city_temp=="alameda" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="albany" & investor_state_temp=="maryland"
replace investor_state_temp="new york" if investor_city_temp=="albany" & investor_state_temp=="maine"
replace investor_state_temp="new york" if investor_city_temp=="albany" & investor_state_temp=="scotland/pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="albany" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="allegheny" & investor_state_temp=="new hampshire"
replace investor_state_temp="pennsylvania" if investor_city_temp=="altoona" & investor_state_temp=="new hampshire"
replace investor_state_temp="pennsylvania" if investor_city_temp=="altoona" & investor_state_temp=="connecticut"
replace investor_state_temp="holland/new york" if investor_city_temp=="amsterdam" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="apollo" & investor_state_temp=="new hampshire"
replace investor_state_temp="georgia" if investor_city_temp=="atlanta" & investor_state_temp=="rhode island"
replace investor_state_temp="new jersey" if investor_city_temp=="atlantic city" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="atlantic city" & investor_state_temp=="california"
replace investor_state_temp="new jersey" if investor_city_temp=="atlantic city" & investor_state_temp=="massachusetts"
replace investor_state_temp="massachusetts" if investor_city_temp=="attleborough" & investor_state_temp=="connecticut"
replace investor_state_temp="maine" if investor_city_temp=="auburn" & investor_state_temp=="pennsylvania"
replace investor_state_temp="maine" if investor_city_temp=="augusta" & investor_state_temp=="massachusetts"
replace investor_state_temp="maine" if investor_city_temp=="augusta" & investor_state_temp=="pennsylvania"
replace investor_state_temp="maine" if investor_city_temp=="augusta" & investor_state_temp=="california"
replace investor_state_temp="california" if investor_city_temp=="bakersfield" & investor_state_temp=="new hampshire"
replace investor_state_temp="maryland" if investor_city_temp=="baltimore" & investor_state_temp=="california"
replace investor_state_temp="maryland" if investor_city_temp=="baltimore" & investor_state_temp=="north carolina"
replace investor_state_temp="maryland" if investor_city_temp=="baltimore" & investor_state_temp=="michigan"
replace investor_state_temp="maryland" if investor_city_temp=="baltimore" & investor_state_temp=="missouri"
replace investor_state_temp="maryland" if investor_city_temp=="baltimore" & investor_state_temp=="massachusetts"
replace investor_state_temp="maryland" if investor_city_temp=="baltimore" & investor_state_temp=="pennsylvania"
replace investor_state_temp="maryland" if investor_city_temp=="baltimore" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="bangor" & investor_state_temp=="missouri"
replace investor_state_temp="pennsylvania" if investor_city_temp=="bangor" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="bangor" & investor_state_temp=="connecticut"
replace investor_state_temp="maine" if investor_city_temp=="bath" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="bath" & investor_state_temp=="pennsylvania"
replace investor_state_temp="maine" if investor_city_temp=="bath" & investor_state_temp=="rhode island"
replace investor_state_temp="maine" if investor_city_temp=="bath" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="bayonne" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="berlin" & investor_state_temp=="maine"
replace investor_state_temp="new hampshire" if investor_city_temp=="berlin" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="berlin" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="berwick" & investor_state_temp=="michigan"
replace investor_state_temp="maine" if investor_city_temp=="bethel" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="bethel" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="bethlehem" & investor_state_temp=="maine"
replace investor_state_temp="pennsylvania" if investor_city_temp=="bethlehem" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="bethlehem" & investor_state_temp=="new jersey"
replace investor_state_temp="maine" if investor_city_temp=="biddeford" & investor_state_temp=="california"
replace investor_state_temp="new york" if investor_city_temp=="binghamton" & investor_state_temp=="connecticut"
replace investor_state_temp="new york" if investor_city_temp=="binghamton" & investor_state_temp=="new jersey"
replace investor_state_temp="new york" if investor_city_temp=="binghamton" & investor_state_temp=="california"
replace investor_state_temp="new york" if investor_city_temp=="binghamton" & investor_state_temp=="pennsylvania"
replace investor_state_temp="california" if investor_city_temp=="bishop" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="bloomfield" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="boothbay harbor" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="boston" & investor_state_temp=="maine"
replace investor_state_temp="connecticut" if investor_city_temp=="bridgeport" & investor_state_temp=="massachusetts"
replace investor_state_temp="massachusetts" if investor_city_temp=="bridgewater" & investor_state_temp=="maine"
replace investor_state_temp="new hampshire" if investor_city_temp=="bristol" & investor_state_temp=="north carolina"
replace investor_state_temp="new hampshire" if investor_city_temp=="bristol" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="bristol" & investor_state_temp=="massachusetts"
replace investor_state_temp="new york" if investor_city_temp=="brooklyn" & investor_state_temp=="indiana"
replace investor_state_temp="new york" if investor_city_temp=="brooklyn" & investor_state_temp=="new hampshire"
replace investor_state_temp="new york" if investor_city_temp=="brooklyn" & investor_state_temp=="rhode island"
replace investor_state_temp="new york" if investor_city_temp=="brooklyn" & investor_state_temp=="massachusetts"
replace investor_state_temp="new york" if investor_city_temp=="brooklyn" & investor_state_temp=="new jersey"
replace investor_state_temp="new york" if investor_city_temp=="brooklyn" & investor_state_temp=="pennsylvania"
replace investor_state_temp="maine" if investor_city_temp=="brunswick" & investor_state_temp=="massachusetts"
replace investor_state_temp="new york" if investor_city_temp=="buffalo" & investor_state_temp=="new hampshire"
replace investor_state_temp="new york" if investor_city_temp=="buffalo" & investor_state_temp=="connecticut"
replace investor_state_temp="new york" if investor_city_temp=="buffalo" & investor_state_temp=="pennsylvania"
replace investor_state_temp="iowa" if investor_city_temp=="burlington" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="burlington" & investor_state_temp=="new york"
replace investor_state_temp="iowa" if investor_city_temp=="burlington" & investor_state_temp=="louisiana"
replace investor_state_temp="maine" if investor_city_temp=="buxton" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="cambridge" & investor_state_temp=="new hampshire"
replace investor_state_temp="massachusetts" if investor_city_temp=="cambridge" & investor_state_temp=="maine"
replace investor_state_temp="new jersey" if investor_city_temp=="camden" & investor_state_temp=="indiana"
replace investor_state_temp="new jersey" if investor_city_temp=="camden" & investor_state_temp=="maine"
replace investor_state_temp="new jersey" if investor_city_temp=="camden" & investor_state_temp=="new york"
replace investor_state_temp="connecticut" if investor_city_temp=="canaan" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="carbondale" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="carbondale" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="chambersburg" & investor_state_temp=="california"
replace investor_state_temp="west virginia" if investor_city_temp=="charleston" & investor_state_temp=="virginia"
replace investor_state_temp="massachusetts" if investor_city_temp=="charlestown" & investor_state_temp=="new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="charlestown" & investor_state_temp=="new hampshire"
replace investor_state_temp="pennsylvania" if investor_city_temp=="chester" & investor_state_temp=="colorado"
replace investor_state_temp="illinois" if investor_city_temp=="chicago" & investor_state_temp=="maine"
replace investor_state_temp="illinois" if investor_city_temp=="chicago" & investor_state_temp=="pennsylvania"
replace investor_state_temp="illinois" if investor_city_temp=="chicago" & investor_state_temp==""
replace investor_state_temp="ohio" if investor_city_temp=="cincinnati" & investor_state_temp=="maine"
replace investor_state_temp="ohio" if investor_city_temp=="cincinnati" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="cohoes" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="concord" & investor_state_temp=="rhode island"
replace investor_state_temp="new hampshire" if investor_city_temp=="concord" & investor_state_temp=="virginia"
replace investor_state_temp="new hampshire" if investor_city_temp=="concord" & investor_state_temp=="utah"
replace investor_state_temp="new hampshire" if investor_city_temp=="concord" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new hampshire" if investor_city_temp=="concord" & investor_state_temp=="connecticut"
replace investor_state_temp="new hampshire" if investor_city_temp=="concord" & investor_state_temp=="new jersey"
replace investor_state_temp="new hampshire" if investor_city_temp=="concord" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="cranford" & investor_state_temp=="pennsylvania"
replace investor_state_temp="pennsylvania" if investor_city_temp=="danville" & investor_state_temp=="rhode island"
replace investor_state_temp="iowa" if investor_city_temp=="des moines" & investor_state_temp=="louisiana"
replace investor_state_temp="michigan" if investor_city_temp=="detroit" & investor_state_temp=="new hampshire"
replace investor_state_temp="michigan" if investor_city_temp=="detroit" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="dover" & investor_state_temp=="rhode island"
replace investor_state_temp="maine" if investor_city_temp=="dover" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="dover" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="dover" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="dover" & investor_state_temp=="england/new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="doylestown" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="doylestown" & investor_state_temp=="massachusetts"
replace investor_state_temp="iowa" if investor_city_temp=="dubuque" & investor_state_temp=="pennsylvania"
replace investor_state_temp="iowa" if investor_city_temp=="dubuque" & investor_state_temp=="louisiana"
replace investor_state_temp="new hampshire" if investor_city_temp=="east jaffrey" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="east orange" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="east orange" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="easton" & investor_state_temp=="maine"
replace investor_state_temp="maine" if investor_city_temp=="eastport" & investor_state_temp=="massachusetts"
replace investor_state_temp="scotland/new york" if investor_city_temp=="edinburgh" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="elizabeth" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="elizabethville" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="ellsworth" & investor_state_temp=="massachusetts"
replace investor_state_temp="new york" if investor_city_temp=="elmira" & investor_state_temp=="new jersey"
replace investor_state_temp="new jersey" if investor_city_temp=="englewood" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="exeter" & investor_state_temp=="california"
replace investor_state_temp="new hampshire" if investor_city_temp=="exeter" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="exeter" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="fairfield" & investor_state_temp=="massachusetts"
replace investor_state_temp="massachusetts" if investor_city_temp=="fall river" & investor_state_temp=="connecticut"
replace investor_state_temp="new york" if investor_city_temp=="fishkillonhudson" & investor_state_temp=="new hampshire"
replace investor_state_temp="massachusetts" if investor_city_temp=="fitchburg" & investor_state_temp=="new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="fitchburg" & investor_state_temp=="maine"
replace investor_state_temp="new hampshire" if investor_city_temp=="franklin" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="fredonia" & investor_state_temp=="new hampshire"
replace investor_state_temp="new york" if investor_city_temp=="fredonia" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="freeport" & investor_state_temp=="illinois"
replace investor_state_temp="pennsylvania" if investor_city_temp=="freeport" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="gettysburg" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="glen ridge" & investor_state_temp=="new york"
replace investor_state_temp="sweden/new york" if investor_city_temp=="gothenburg" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="grafton" & investor_state_temp=="maine"
replace investor_state_temp="north carolina" if investor_city_temp=="greensboro" & investor_state_temp=="new york"
replace investor_state_temp="north carolina" if investor_city_temp=="greensboro" & investor_state_temp=="pennsylvania"
replace investor_state_temp="north carolina" if investor_city_temp=="greensboro" & investor_state_temp=="connecticut"
replace investor_state_temp="north carolina" if investor_city_temp=="greensboro" & investor_state_temp=="virginia"
replace investor_state_temp="new jersey" if investor_city_temp=="hackensack" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="hackensack" & investor_state_temp=="new york"
replace investor_state_temp="canada" if investor_city_temp=="halifax" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="hamburg" & investor_state_temp=="michigan"
replace investor_state_temp="germany/new york" if investor_city_temp=="hamburg" & investor_state_temp=="germany"
replace investor_state_temp="germany/new york" if investor_city_temp=="hamburg" & investor_state_temp=="new york"
replace investor_state_temp="canada" if investor_city_temp=="hamilton" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="hanover" & investor_state_temp=="delaware"
replace investor_state_temp="pennsylvania" if investor_city_temp=="hanover" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="hanover" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="hanover" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="harrisburg" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="harrisburg" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="harrisburg" & investor_state_temp=="massachusetts"
replace investor_state_temp="scotland/connecticut" if investor_city_temp=="edinburgh/hartford" & investor_state_temp=="scotland/colorado"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="maine"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="michigan"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="rhode island"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="massachusetts"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="new hampshire"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="pennsylvania"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="maryland"
replace investor_state_temp="connecticut" if investor_city_temp=="hartford" & investor_state_temp=="new york"
replace investor_state_temp="scotland/connecticut" if investor_city_temp=="edinburgh/hartford" & investor_state_temp=="scotland/new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="hazleton" & investor_state_temp=="california"
replace investor_state_temp="new hampshire" if investor_city_temp=="hillsborough" & investor_state_temp=="north carolina"
replace investor_state_temp="massachusetts" if investor_city_temp=="hingham" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="hoboken" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="honesdale" & investor_state_temp=="california"
replace investor_state_temp="pennsylvania" if investor_city_temp=="honesdale" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="hopkinton" & investor_state_temp=="maine"
replace investor_state_temp="maine" if investor_city_temp=="houlton" & investor_state_temp=="missouri"
replace investor_state_temp="pennsylvania" if investor_city_temp=="indiana" & investor_state_temp=="rhode island"
replace investor_state_temp="pennsylvania" if investor_city_temp=="indiana" & investor_state_temp=="new york"
replace investor_state_temp="indiana" if investor_city_temp=="indianapolis" & investor_state_temp=="pennsylvania"
replace investor_state_temp="california" if investor_city_temp=="ione" & investor_state_temp=="maine"
replace investor_state_temp="california" if investor_city_temp=="ione" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="ione" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="ithaca" & investor_state_temp=="california"
replace investor_state_temp="new york" if investor_city_temp=="ithaca" & investor_state_temp=="new jersey"
replace investor_state_temp="new york" if investor_city_temp=="ithaca" & investor_state_temp=="nevada"
replace investor_state_temp="new york" if investor_city_temp=="ithaca" & investor_state_temp=="new hampshire"
replace investor_state_temp="new york" if investor_city_temp=="jamaica" & investor_state_temp=="new jersey"
replace investor_state_temp="new york" if investor_city_temp=="jamaica" & investor_state_temp=="new hampshire"
replace investor_state_temp="new york" if investor_city_temp=="jamaica" & investor_state_temp=="vermont"
replace investor_state_temp="new york" if investor_city_temp=="jamestown" & investor_state_temp=="tennessee"
replace investor_state_temp="new york" if investor_city_temp=="jamestown" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="jamestown" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="jenkintown" & investor_state_temp=="rhode island"
replace investor_state_temp="new jersey" if investor_city_temp=="jersey city" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="jersey city" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="jersey city" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="jersey shore" & investor_state_temp=="rhode island"
replace investor_state_temp="pennsylvania" if investor_city_temp=="jersey shore" & investor_state_temp=="new hampshire"
replace investor_state_temp="pennsylvania" if investor_city_temp=="jersey shore" & investor_state_temp=="connecticut"
replace investor_state_temp="pennsylvania" if investor_city_temp=="jersey shore" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="jersey shore" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="kane" & investor_state_temp=="california"
replace investor_state_temp="missouri" if investor_city_temp=="kansas city" & investor_state_temp=="maryland"
replace investor_state_temp="new hampshire" if investor_city_temp=="keene" & investor_state_temp=="massachusetts"
replace investor_state_temp="maine" if investor_city_temp=="kennebunk" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="kennebunk" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="kennebunk" & investor_state_temp=="missouri"
replace investor_state_temp="pennsylvania" if investor_city_temp=="kennett square" & investor_state_temp=="new hampshire"
replace investor_state_temp="rhode island" if investor_city_temp=="kingston" & investor_state_temp=="connecticut"
replace investor_state_temp="rhode island" if investor_city_temp=="kingston" & investor_state_temp=="maine"
replace investor_state_temp="pennsylvania" if investor_city_temp=="kingston" & investor_state_temp=="new york" & invname_hold_orig=="Deposit & Savings Bank"
replace investor_state_temp="rhode island" if investor_city_temp=="kingston" & investor_state_temp=="new york" & invname_hold_orig=="Kingston Trust Company"
replace investor_state_temp="new hampshire" if investor_city_temp=="laconia" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="lancaster" & investor_state_temp=="rhode island"
replace investor_state_temp="pennsylvania" if investor_city_temp=="lancaster" & investor_state_temp=="maine"
replace investor_state_temp="pennsylvania" if investor_city_temp=="lancaster" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="latrobe" & investor_state_temp=="iowa"
replace investor_state_temp="massachusetts" if investor_city_temp=="lawrence" & investor_state_temp=="pennsylvania"
replace investor_state_temp="pennsylvania" if investor_city_temp=="lebanon" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="lewiston" & investor_state_temp=="west virginia"
replace investor_state_temp="maine" if investor_city_temp=="lewiston" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="lewiston" & investor_state_temp=="missouri"
replace investor_state_temp="massachusetts" if investor_city_temp=="lexington" & investor_state_temp=="kentucky"
replace investor_state_temp="new hampshire" if investor_city_temp=="lisbon" & investor_state_temp=="pennsylvania"
replace investor_state_temp="connecticut" if investor_city_temp=="litchfield" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="littleton" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="littleton" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new hampshire" if investor_city_temp=="littleton" & investor_state_temp=="massachusetts"
replace investor_state_temp="england/new york" if investor_city_temp=="liverpool" & investor_state_temp=="massachusetts"
replace investor_state_temp="england/new york" if investor_city_temp=="liverpool" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="lock haven" & investor_state_temp=="maine"
replace investor_state_temp="pennsylvania" if investor_city_temp=="lock haven" & investor_state_temp=="connecticut"
replace investor_state_temp="england/illinois" if investor_city_temp=="london" & investor_state_temp=="illinois"
replace investor_state_temp="england/new york" if investor_city_temp=="london" & investor_state_temp=="new york"
replace investor_state_temp="great britain" if investor_city_temp=="london and edinburgh" & investor_state_temp=="great britain"
replace investor_state_temp="new jersey" if investor_city_temp=="long branch" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="los angeles" & investor_state_temp=="new jersey"
replace investor_state_temp="california" if investor_city_temp=="los angeles" & investor_state_temp=="rhode island"
replace investor_state_temp="california" if investor_city_temp=="los angeles" & investor_state_temp=="new hampshire"
replace investor_state_temp="california" if investor_city_temp=="los angeles" & investor_state_temp=="maine"
replace investor_state_temp="california" if investor_city_temp=="los angeles" & investor_state_temp=="massachusetts"
replace investor_state_temp="california" if investor_city_temp=="los angeles" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="los angeles" & investor_state_temp=="pennsylvania"
replace investor_state_temp="kentucky" if investor_city_temp=="louisville" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="lowell" & investor_state_temp=="new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="lowell" & investor_state_temp=="maine"
replace investor_state_temp="massachusetts" if investor_city_temp=="lowell" & investor_state_temp=="new hampshire"
replace investor_state_temp="massachusetts" if investor_city_temp=="lowell" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="lowell" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="ludlow" & investor_state_temp=="new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="lynn" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="machias" & investor_state_temp=="new hampshire"
replace investor_state_temp="indiana" if investor_city_temp=="madison" & investor_state_temp=="maryland"
replace investor_state_temp="indiana" if investor_city_temp=="madison" & investor_state_temp=="wisconsin"
replace investor_state_temp="new york" if investor_city_temp=="mamaroneck" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="virginia"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="rhode island"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="california"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="maine"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="new jersey"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="connecticut" & invname_hold_orig=="Amoskeag Savings Bank"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="manchester" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="mauch chunk" & investor_state_temp=="iowa"
replace investor_state_temp="pennsylvania" if investor_city_temp=="mcdonald" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="mckees rocks" & investor_state_temp=="new york"
replace investor_state_temp="tennessee" if investor_city_temp=="memphis" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="merced" & investor_state_temp=="ohio"
replace investor_state_temp="connecticut" if investor_city_temp=="meriden" & investor_state_temp=="massachusetts"
replace investor_state_temp="connecticut" if investor_city_temp=="middletown" & investor_state_temp=="canada"
replace investor_state_temp="connecticut" if investor_city_temp=="middletown" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="milford" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="montclair" & investor_state_temp=="new hampshire"
replace investor_state_temp="new jersey" if investor_city_temp=="montclair" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="montclair" & investor_state_temp=="michigan"
replace investor_state_temp="new jersey" if investor_city_temp=="montclair" & investor_state_temp=="connecticut"
replace investor_state_temp="new jersey" if investor_city_temp=="montclair" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="montclair" & investor_state_temp=="pennsylvania"
replace investor_state_temp="england/canada" if investor_city_temp=="montreal" & investor_state_temp=="england"
replace investor_state_temp="england/canada" if investor_city_temp=="london/montreal" & investor_state_temp=="england/new york"
replace investor_state_temp="canada" if investor_city_temp=="montreal" & investor_state_temp=="new york"
replace investor_state_temp="england/canada" if investor_city_temp=="liverpool/montreal" & investor_state_temp=="england/missouri"
replace investor_state_temp="scotland/canada" if investor_city_temp=="edinburgh/montreal" & investor_state_temp=="scotland/missouri"
replace investor_state_temp="new jersey" if investor_city_temp=="moorestown" & investor_state_temp=="connecticut"
replace investor_state_temp="new jersey" if investor_city_temp=="moorestown" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="moorestown" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="morristown" & investor_state_temp=="rhode island"
replace investor_state_temp="new jersey" if investor_city_temp=="morristown" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="mount holly" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="mount holly" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="mount vernon" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="mount vernon" & investor_state_temp=="new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="nantucket" & investor_state_temp=="connecticut"
replace investor_state_temp="california" if investor_city_temp=="napa" & investor_state_temp=="maine"
replace investor_state_temp="new hampshire" if investor_city_temp=="nashua" & investor_state_temp=="new jersey"
replace investor_state_temp="new hampshire" if investor_city_temp=="nashua" & investor_state_temp=="rhode island"
replace investor_state_temp="new hampshire" if investor_city_temp=="nashua" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="nashua" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="nevada city" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="new berlin" & investor_state_temp=="new jersey"
replace investor_state_temp="england/new york" if investor_city_temp=="new britain" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="new brunswick" & investor_state_temp=="new york"
replace investor_state_temp="connecticut" if investor_city_temp=="new haven" & investor_state_temp=="new york"
replace investor_state_temp="connecticut" if investor_city_temp=="new haven" & investor_state_temp=="massachusetts"
replace investor_state_temp="connecticut" if investor_city_temp=="new haven" & investor_state_temp=="pennsylvania"
replace investor_state_temp="connecticut" if investor_city_temp=="new haven" & investor_state_temp=="new jersey"
replace investor_state_temp="connecticut" if investor_city_temp=="new london" & investor_state_temp=="massachusetts"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp==""
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="ohio"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="indiana"
replace investor_state_temp="germany/new york" if investor_city_temp=="frankfort/new york" & investor_state_temp=="new york/germany"
replace investor_state_temp="england/massachusetts" if investor_city_temp=="new york" & investor_state_temp=="england"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg/new york" & investor_state_temp=="russia/kentucky"
replace investor_state_temp="scotland/new york" if investor_city_temp=="edinburgh/new york" & investor_state_temp=="new york/scotland"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="kentucky"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="california"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="connecticut"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="maine"
replace investor_state_temp="massachusetts" if investor_city_temp=="new york" & investor_state_temp=="rhode island" & invname_hold_orig=="Rubber Manufacturers' Mutual Insurance Company"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="rhode island"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="new jersey"
replace investor_state_temp="england/new york" if investor_city_temp=="liverpool/new york" & investor_state_temp=="england/new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="new york" & investor_state_temp=="pennsylvania" & invname_hold_orig=="John Hancock Mutual Life Insurance Company"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="new york" & investor_state_temp=="new hampshire"
replace investor_state_temp="new jersey" if investor_city_temp=="newark" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="newark" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="newark" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="newark" & investor_state_temp=="germany/new york"
replace investor_state_temp="new york" if investor_city_temp=="newburgh" & investor_state_temp=="maryland"
replace investor_state_temp="new york" if investor_city_temp=="newburgh" & investor_state_temp=="massachusetts"
replace investor_state_temp="new york" if investor_city_temp=="newburgh" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="newburyport" & investor_state_temp=="new york"
replace investor_state_temp="rhode island" if investor_city_temp=="newport" & investor_state_temp=="new jersey"
replace investor_state_temp="rhode island" if investor_city_temp=="newport" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="newton" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="niagara falls" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="norristown" & investor_state_temp=="iowa"
replace investor_state_temp="pennsylvania" if investor_city_temp=="norristown" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="northampton" & investor_state_temp=="new hampshire"
replace investor_state_temp="connecticut" if investor_city_temp=="norwich" & investor_state_temp=="new jersey"
replace investor_state_temp="connecticut" if investor_city_temp=="norwich" & investor_state_temp=="maine"
replace investor_state_temp="england/new york" if investor_city_temp=="norwich" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="nyack" & investor_state_temp=="rhode island"
replace investor_state_temp="new york" if investor_city_temp=="nyack" & investor_state_temp=="nevada"
replace investor_state_temp="new york" if investor_city_temp=="nyack" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="nyack" & investor_state_temp=="new jersey"
replace investor_state_temp="canada" if investor_city_temp=="ontario" & investor_state_temp=="california"
replace investor_state_temp="new jersey" if investor_city_temp=="orange" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="pasadena" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="passaic" & investor_state_temp=="california"
replace investor_state_temp="new jersey" if investor_city_temp=="passaic" & investor_state_temp=="new hampshire"
replace investor_state_temp="new jersey" if investor_city_temp=="passaic" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="paterson" & investor_state_temp=="maryland"
replace investor_state_temp="new jersey" if investor_city_temp=="paterson" & investor_state_temp=="california"
replace investor_state_temp="new jersey" if investor_city_temp=="paterson" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="paterson" & investor_state_temp=="new york"
replace investor_state_temp="rhode island" if investor_city_temp=="pawtucket" & investor_state_temp=="connecticut"
replace investor_state_temp="rhode island" if investor_city_temp=="pawtucket" & investor_state_temp=="maine"
replace investor_state_temp="rhode island" if investor_city_temp=="pawtucket" & investor_state_temp=="massachusetts"
replace investor_state_temp="rhode island" if investor_city_temp=="pawtucket" & investor_state_temp==""
replace investor_state_temp="rhode island" if investor_city_temp=="pawtucket" & investor_state_temp=="new hampshire"
replace investor_state_temp="rhode island" if investor_city_temp=="pawtucket" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="peabody" & investor_state_temp=="new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="peabody" & investor_state_temp=="connecticut"
replace investor_state_temp="massachusetts" if investor_city_temp=="peabody" & investor_state_temp=="maine"
replace investor_state_temp="new jersey" if investor_city_temp=="perth amboy" & investor_state_temp=="rhode island"
replace investor_state_temp="new jersey" if investor_city_temp=="perth amboy" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="peterborough" & investor_state_temp=="rhode island"
replace investor_state_temp="new hampshire" if investor_city_temp=="peterborough" & investor_state_temp=="maine"
replace investor_state_temp="rhode island" if investor_city_temp=="phenix" & investor_state_temp=="pennsylvania"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="delaware"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="canada"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="maryland"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="virginia"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="louisiana"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="iowa"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="california"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="connecticut"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="rhode island"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp==""
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia/philadelphia" & investor_state_temp=="new hampshire"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="philadelphia" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="maryland"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="illinois"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="virginia"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="connecticut"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="georgia"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="canada"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="iowa"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="rhode island"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="new hampshire"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="maine"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittsburg" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="pittsfield" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="pittsfield" & investor_state_temp=="connecticut"
replace investor_state_temp="massachusetts" if investor_city_temp=="pittsfield" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittston" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittston" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pittston" & investor_state_temp=="new jersey"
replace investor_state_temp="new jersey" if investor_city_temp=="plainfield" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="plainfield" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp==""
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="maryland"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="new jersey"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="missouri"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="massachusetts"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="rhode island"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="portland" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new hampshire" if investor_city_temp=="portsmouth" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new hampshire" if investor_city_temp=="portsmouth" & investor_state_temp=="massachusetts"
replace investor_state_temp="new hampshire" if investor_city_temp=="portsmouth" & investor_state_temp=="rhode island"
replace investor_state_temp="new hampshire" if investor_city_temp=="portsmouth" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pottsville" & investor_state_temp=="virginia"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pottsville" & investor_state_temp=="rhode island"
replace investor_state_temp="pennsylvania" if investor_city_temp=="pottsville" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="poughkeepsie" & investor_state_temp=="new jersey"
replace investor_state_temp="new york" if investor_city_temp=="poughkeepsie" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="princeton" & investor_state_temp=="new york"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="illinois"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="maine"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="connecticut"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="new hampshire"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="new jersey"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="pennsylvania"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="massachusetts"
replace investor_state_temp="rhode island" if investor_city_temp=="providence" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="quincy" & investor_state_temp=="california"
replace investor_state_temp="north carolina" if investor_city_temp=="raleigh" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="reading" & investor_state_temp=="connecticut"
replace investor_state_temp="pennsylvania" if investor_city_temp=="reading" & investor_state_temp=="rhode island"
replace investor_state_temp="california" if investor_city_temp=="redwood city" & investor_state_temp=="new york"
replace investor_state_temp="virginia" if investor_city_temp=="richmond" & investor_state_temp=="pennsylvania"
replace investor_state_temp="virginia" if investor_city_temp=="richmond" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="ridgewood" & investor_state_temp=="new hampshire"
replace investor_state_temp="new jersey" if investor_city_temp=="ridgewood" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="rochester" & investor_state_temp=="rhode island"
replace investor_state_temp="new york" if investor_city_temp=="rochester" & investor_state_temp=="nevada"
replace investor_state_temp="new york" if investor_city_temp=="rochester" & investor_state_temp=="connecticut"
replace investor_state_temp="new hampshire" if investor_city_temp=="rochester" & investor_state_temp=="massachusetts" & invname_hold_orig=="Rochester Loan & Banking Company"
replace investor_state_temp="new york" if investor_city_temp=="rochester" & investor_state_temp=="massachusetts" & invname_hold_orig=="Genesee Valley Trust Company"
replace investor_state_temp="new hampshire" if investor_city_temp=="rochester" & investor_state_temp=="massachusetts" & invname_hold_orig=="Norway Plains Savings Bank"
replace investor_state_temp="new york" if investor_city_temp=="rochester" & investor_state_temp=="new jersey"
replace investor_state_temp="new york" if investor_city_temp=="rochester" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="rochester" & investor_state_temp=="new york/new york"
replace investor_state_temp="illinois" if investor_city_temp=="rockford" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="rockland" & investor_state_temp=="missouri"
replace investor_state_temp="maine" if investor_city_temp=="rockport" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="roxbury" & investor_state_temp=="new jersey"
replace investor_state_temp="maine" if investor_city_temp=="saco" & investor_state_temp=="massachusetts"
replace investor_state_temp="maine" if investor_city_temp=="saco" & investor_state_temp=="michigan"
replace investor_state_temp="maine" if investor_city_temp=="saco" & investor_state_temp=="rhode island"
replace investor_state_temp="maine" if investor_city_temp=="saco" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="saco" & investor_state_temp=="missouri"
replace investor_state_temp="michigan" if investor_city_temp=="saginaw" & investor_state_temp=="california"
replace investor_state_temp="massachusetts" if investor_city_temp=="salem" & investor_state_temp=="kentucky"
replace investor_state_temp="massachusetts" if investor_city_temp=="salem" & investor_state_temp=="new hampshire"
replace investor_state_temp="massachusetts" if investor_city_temp=="salem" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="salmon falls" & investor_state_temp=="pennsylvania"
replace investor_state_temp="utah" if investor_city_temp=="salt lake city" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="san francisco" & investor_state_temp=="rhode island"
replace investor_state_temp="california" if investor_city_temp=="san francisco" & investor_state_temp=="new hampshire"
replace investor_state_temp="california" if investor_city_temp=="san luis obispo" & investor_state_temp=="massachusetts"
replace investor_state_temp="california" if investor_city_temp=="san luis obispo" & investor_state_temp=="colorado"
replace investor_state_temp="california" if investor_city_temp=="santa ana" & investor_state_temp=="new york"
replace investor_state_temp="california" if investor_city_temp=="santa cruz" & investor_state_temp=="rhode island"
replace investor_state_temp="new york" if investor_city_temp=="saratoga springs" & investor_state_temp=="rhode island"
replace investor_state_temp="new york" if investor_city_temp=="schenectady" & investor_state_temp=="new hampshire"
replace investor_state_temp="new york" if investor_city_temp=="schenectady" & investor_state_temp=="pennsylvania"
replace investor_state_temp="pennsylvania" if investor_city_temp=="scranton" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="scranton" & investor_state_temp=="louisiana"
replace investor_state_temp="pennsylvania" if investor_city_temp=="scranton" & investor_state_temp=="virginia"
replace investor_state_temp="pennsylvania" if investor_city_temp=="scranton" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="scranton" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="searsport" & investor_state_temp=="connecticut"
replace investor_state_temp="pennsylvania" if investor_city_temp=="shamokin" & investor_state_temp=="california"
replace investor_state_temp="pennsylvania" if investor_city_temp=="sharpsburg" & investor_state_temp=="california"
replace investor_state_temp="pennsylvania" if investor_city_temp=="shenandoah" & investor_state_temp=="rhode island"
replace investor_state_temp="pennsylvania" if investor_city_temp=="shenandoah" & investor_state_temp=="new york"
replace investor_state_temp="south dakota" if investor_city_temp=="sioux falls" & investor_state_temp=="north dakota"
replace investor_state_temp="pennsylvania" if investor_city_temp=="somerset" & investor_state_temp=="new hampshire"
replace investor_state_temp="new hampshire" if investor_city_temp=="somersworth" & investor_state_temp=="new jersey"
replace investor_state_temp="maine" if investor_city_temp=="south berwick" & investor_state_temp=="new york"
replace investor_state_temp="maine" if investor_city_temp=="south berwick" & investor_state_temp=="massachusetts"
replace investor_state_temp="maine" if investor_city_temp=="south berwick" & investor_state_temp=="missouri"
replace investor_state_temp="maine" if investor_city_temp=="south paris" & investor_state_temp=="missouri"
replace investor_state_temp="massachusetts" if investor_city_temp=="springfield" & investor_state_temp=="maine"
replace investor_state_temp="massachusetts" if investor_city_temp=="springfield" & investor_state_temp=="missouri"
replace investor_state_temp="massachusetts" if investor_city_temp=="springfield" & investor_state_temp=="new hampshire"
replace investor_state_temp="massachusetts" if investor_city_temp=="springfield" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="springfield" & investor_state_temp=="vermont"
replace investor_state_temp="massachusetts" if investor_city_temp=="springfield" & investor_state_temp=="maryland"
replace investor_state_temp="massachusetts" if investor_city_temp=="springfield" & investor_state_temp=="new york"
replace investor_state_temp="missouri" if investor_city_temp=="st louis" & investor_state_temp=="massachusetts"
replace investor_state_temp="missouri" if investor_city_temp=="st louis" & investor_state_temp=="maryland"
replace investor_state_temp="missouri" if investor_city_temp=="st louis" & investor_state_temp=="maine"
replace investor_state_temp="russia/new york" if investor_city_temp=="st petersburg" & investor_state_temp=="new york"
replace investor_state_temp="connecticut" if investor_city_temp=="stamford" & investor_state_temp=="canada"
replace investor_state_temp="connecticut" if investor_city_temp=="stamford" & investor_state_temp=="massachusetts"
replace investor_state_temp="pennsylvania" if investor_city_temp=="steelton" & investor_state_temp=="new jersey"
replace investor_state_temp="germany/illinois" if investor_city_temp=="stettin" & investor_state_temp=="illinois"
replace investor_state_temp="germany/illinois" if investor_city_temp=="stettin" & investor_state_temp=="germany"
replace investor_state_temp="california" if investor_city_temp=="stockton" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="summit" & investor_state_temp=="new york"
replace investor_state_temp="new jersey" if investor_city_temp=="summit" & investor_state_temp=="pennsylvania"
replace investor_state_temp="california" if investor_city_temp=="sutter creek" & investor_state_temp=="rhode island"
replace investor_state_temp="new york" if investor_city_temp=="syracuse" & investor_state_temp=="new jersey"
replace investor_state_temp="new york" if investor_city_temp=="syracuse" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="syracuse" & investor_state_temp=="new hampshire"
replace investor_state_temp="massachusetts" if investor_city_temp=="taunton" & investor_state_temp=="maine"
replace investor_state_temp="massachusetts" if investor_city_temp=="taunton" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="thomaston" & investor_state_temp=="missouri"
replace investor_state_temp="new hampshire" if investor_city_temp=="tilton" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="titusville" & investor_state_temp=="massachusetts"
replace investor_state_temp="kansas" if investor_city_temp=="topeka" & investor_state_temp=="canada"
replace investor_state_temp="canada" if investor_city_temp=="toronto" & investor_state_temp=="maine"
replace investor_state_temp="canada" if investor_city_temp=="toronto" & investor_state_temp=="pennsylvania"
replace investor_state_temp="connecticut" if investor_city_temp=="torrington" & investor_state_temp=="massachusetts"
replace investor_state_temp="new jersey" if investor_city_temp=="trenton" & investor_state_temp=="new hampshire"
replace investor_state_temp="new jersey" if investor_city_temp=="trenton" & investor_state_temp=="new york"
replace investor_state_temp="new york" if investor_city_temp=="utica" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new jersey" if investor_city_temp=="vineland" & investor_state_temp=="new york"
replace investor_state_temp="rhode island" if investor_city_temp=="wakefield" & investor_state_temp=="new york"
replace investor_state_temp="rhode island" if investor_city_temp=="wakefield" & investor_state_temp=="california"
replace investor_state_temp="rhode island" if investor_city_temp=="wakefield" & investor_state_temp=="new hampshire"
replace investor_state_temp="new hampshire" if investor_city_temp=="walpole" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new hampshire" if investor_city_temp=="walpole" & investor_state_temp=="new jersey"
replace investor_state_temp="virginia" if investor_city_temp=="waterford" & investor_state_temp=="west virginia"
replace investor_state_temp="canada" if investor_city_temp=="waterloo" & investor_state_temp=="pennsylvania"
replace investor_state_temp="new york" if investor_city_temp=="watertown" & investor_state_temp=="new jersey"
replace investor_state_temp="maine" if investor_city_temp=="waterville" & investor_state_temp=="missouri"
replace investor_state_temp="new york" if investor_city_temp=="waverly" & investor_state_temp=="california"
replace investor_state_temp="new york" if investor_city_temp=="waverly" & investor_state_temp=="new hampshire"
replace investor_state_temp="new york" if investor_city_temp=="waverly" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="wayne" & investor_state_temp=="maine"
replace investor_state_temp="pennsylvania" if investor_city_temp=="west chester" & investor_state_temp=="canada"
replace investor_state_temp="pennsylvania" if investor_city_temp=="west chester" & investor_state_temp=="iowa"
replace investor_state_temp="new jersey" if investor_city_temp=="west hoboken" & investor_state_temp=="rhode island"
replace investor_state_temp="new jersey" if investor_city_temp=="west hoboken" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="west newton" & investor_state_temp=="minnesota"
replace investor_state_temp="rhode island" if investor_city_temp=="westerly" & investor_state_temp=="new york"
replace investor_state_temp="rhode island" if investor_city_temp=="westerly" & investor_state_temp=="maryland"
replace investor_state_temp="rhode island" if investor_city_temp=="westerly" & investor_state_temp=="california"
replace investor_state_temp="new jersey" if investor_city_temp=="westfield" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="weymouth" & investor_state_temp=="maine"
replace investor_state_temp="west virginia" if investor_city_temp=="wheeling" & investor_state_temp=="california"
replace investor_state_temp="west virginia" if investor_city_temp=="wheeling" & investor_state_temp=="virginia"
replace investor_state_temp="new york" if investor_city_temp=="white plains" & investor_state_temp=="massachusetts"
replace investor_state_temp="rhode island" if investor_city_temp=="wickford" & investor_state_temp=="pennsylvania"
replace investor_state_temp="pennsylvania" if investor_city_temp=="wilkes barre" & investor_state_temp=="new jersey"
replace investor_state_temp="pennsylvania" if investor_city_temp=="wilkes barre" & investor_state_temp=="new york"
replace investor_state_temp="pennsylvania" if investor_city_temp=="wilkes barre" & investor_state_temp=="maine"
replace investor_state_temp="pennsylvania" if investor_city_temp=="williamsport" & investor_state_temp=="maine"
replace investor_state_temp="delaware" if investor_city_temp=="wilmington" & investor_state_temp=="rhode island"
replace investor_state_temp="delaware" if investor_city_temp=="wilmington" & investor_state_temp=="pennsylvania"
replace investor_state_temp="north carolina" if investor_city_temp=="wilmington" & investor_state_temp=="new york"
replace investor_state_temp="connecticut" if investor_city_temp=="winsted" & investor_state_temp=="new hampshire"
replace investor_state_temp="maine" if investor_city_temp=="wiscasset" & investor_state_temp=="new hampshire"
replace investor_state_temp="new jersey" if investor_city_temp=="woodbury" & investor_state_temp=="new york"
replace investor_state_temp="new hampshire" if investor_city_temp=="woodsville" & investor_state_temp=="rhode island"
replace investor_state_temp="rhode island" if investor_city_temp=="woonsocket" & investor_state_temp=="california"
replace investor_state_temp="rhode island" if investor_city_temp=="woonsocket" & investor_state_temp=="canada"
replace investor_state_temp="rhode island" if investor_city_temp=="woonsocket" & investor_state_temp=="maryland"
replace investor_state_temp="rhode island" if investor_city_temp=="woonsocket" & investor_state_temp=="massachusetts"
replace investor_state_temp="rhode island" if investor_city_temp=="woonsocket" & investor_state_temp=="pennsylvania"
replace investor_state_temp="rhode island" if investor_city_temp=="woonsocket" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="worcester" & investor_state_temp=="new jersey"
replace investor_state_temp="massachusetts" if investor_city_temp=="worcester" & investor_state_temp=="new york"
replace investor_state_temp="massachusetts" if investor_city_temp=="worcester" & investor_state_temp=="maine"
replace investor_state_temp="massachusetts" if investor_city_temp=="worcester" & investor_state_temp=="rhode island"
replace investor_state_temp="massachusetts" if investor_city_temp=="worcester" & investor_state_temp=="pennsylvania"
replace investor_state_temp="massachusetts" if investor_city_temp=="worcester" & investor_state_temp=="connecticut"
replace investor_state_temp="new york" if investor_city_temp=="yonkers" & investor_state_temp=="new jersey"
replace investor_state_temp="england/new york" if investor_city_temp=="york" & investor_state_temp=="new york" & invname_hold_orig=="Yorkshire Insurance Company, Ltd."
replace investor_city_temp="aixlachapelle\new york" if investor_city_temp=="aixlachapelle" & investor_state_temp=="germany/new york"
replace investor_city_temp="amsterdam/new york" if investor_city_temp=="amsterdam" & investor_state_temp=="holland/new york"
replace investor_city_temp="bridgton" if investor_city_temp=="bridgeton" & investor_state_temp=="massachusetts"
replace investor_city_temp="bridgton" if investor_city_temp=="bridgeton" & investor_state_temp=="maine"
replace investor_city_temp="bridgton" if investor_city_temp=="bridgeton" & investor_state_temp=="new jersey"
replace investor_city_temp="cambria" if investor_city_temp=="cambridge" & investor_state_temp=="pennsylvania"
replace investor_city_temp="centerville" if investor_city_temp=="centreville" & investor_state_temp=="california"
replace investor_city_temp="centerville" if investor_city_temp=="centreville" & investor_state_temp=="rhode island"
replace investor_city_temp="charleston" if investor_city_temp=="charlestown" & investor_state_temp=="west virginia"
replace investor_city_temp="columbus" if investor_city_temp=="columbia" & investor_state_temp=="georgia"
replace investor_city_temp="edinburgh/montreal" if investor_city_temp=="edinburgh" & investor_state_temp=="scotland/canada"
replace investor_city_temp="london & edinburgh" if investor_city_temp=="london/edinburgh" & investor_state_temp=="great britain/new york"
replace investor_city_temp="edinburgh/new york" if investor_city_temp=="edinburgh" & investor_state_temp=="scotland/new york"
replace investor_city_temp="edinburgh/new york" if investor_city_temp=="edinburgh" & investor_state_temp=="scotland/new york"
replace investor_city_temp="farmington" if investor_city_temp=="franklin" & investor_state_temp=="maine"
replace investor_city_temp="gardner" if investor_city_temp=="gardiner" & investor_state_temp=="massachusetts"
replace investor_city_temp="gardiner" if investor_city_temp=="gardner" & investor_state_temp=="maine"
replace investor_city_temp="gothenburg/new york" if investor_city_temp=="gothenburg" & investor_state_temp=="sweden/new york"
replace investor_city_temp="gothenburg/new york" if investor_city_temp=="gothenburg" & investor_state_temp=="sweden/new york"
replace investor_city_temp="hamburg/new york" if investor_city_temp=="hamburg" & investor_state_temp=="germany/new york"
replace investor_city_temp="hamburg/new york" if investor_city_temp=="hamburg" & investor_state_temp=="germany/new york"
replace investor_city_temp="hamburg/new york" if investor_city_temp=="hamburg" & investor_state_temp=="germany/new york"
replace investor_city_temp="edinburgh/montreal" if investor_city_temp=="edinburgh/hartford" & investor_state_temp=="scotland/canada"
replace investor_city_temp="houlton" if investor_city_temp=="houston" & investor_state_temp=="maine"
replace investor_city_temp="liverpool/new york" if investor_city_temp=="liverpool" & investor_state_temp=="england/new york"
replace investor_city_temp="liverpool/new york" if investor_city_temp=="liverpool" & investor_state_temp=="england/new york"
replace investor_city_temp="liverpool/new york" if investor_city_temp=="liverpool" & investor_state_temp=="england/new york"
replace investor_city_temp="london/chicago" if investor_city_temp=="london" & investor_state_temp=="england/illinois"
replace investor_city_temp="new lodon" if investor_city_temp=="london" & investor_state_temp=="connecticut"
replace investor_city_temp="london/new york" if investor_city_temp=="london" & investor_state_temp=="england/new york"
replace investor_city_temp="london/new york" if investor_city_temp=="london" & investor_state_temp=="england/new york"
replace investor_city_temp="london and edinburgh/new york" if investor_city_temp=="london and edinburgh" & investor_state_temp=="great britain/new york"
replace investor_city_temp="london and edinburgh" if investor_city_temp=="london and edinburgh" & investor_state_temp=="great britain"
replace investor_city_temp="south manchester" if investor_city_temp=="manchester" & investor_state_temp=="connecticut"
replace investor_city_temp="middletown" if investor_city_temp=="middleton" & investor_state_temp=="new york"
replace investor_city_temp="middletown" if investor_city_temp=="middleton" & investor_state_temp=="connecticut"
replace investor_city_temp="london/montreal" if investor_city_temp=="montreal" & investor_state_temp=="england/canada"
replace investor_city_temp="montreal/new york" if investor_city_temp=="montreal" & investor_state_temp=="canada"
replace investor_city_temp="munich/hartford" if investor_city_temp=="munich" & investor_state_temp=="germany/connecticut"
replace investor_city_temp="munich/new york" if investor_city_temp=="munich" & investor_state_temp=="germany/new york"
replace investor_city_temp="london/new york" if investor_city_temp=="new britain" & investor_state_temp=="england/new york"
replace investor_city_temp="london/boston" if investor_city_temp=="new york" & investor_state_temp=="england/massachusetts"
replace investor_city_temp="new haven" if investor_city_temp=="new york" & investor_state_temp=="connecticut"
replace investor_city_temp="buxton" if investor_city_temp=="new york" & investor_state_temp=="maine"
replace investor_city_temp="boston" if investor_city_temp=="new york" & investor_state_temp=="massachusetts"
replace investor_city_temp="boston" if investor_city_temp=="new york" & investor_state_temp=="massachusetts"
replace investor_city_temp="liverpool/new york" if investor_city_temp=="liverpool/norfolk" & investor_state_temp=="england/new york"
replace investor_city_temp="harwich" if investor_city_temp=="norwich" & investor_state_temp=="massachusetts"
replace investor_city_temp="norwich/new york" if investor_city_temp=="norwich" & investor_state_temp=="england/new york"
replace investor_city_temp="norwich/new york" if investor_city_temp=="norwich" & investor_state_temp=="england/new york"
replace investor_city_temp="waterloo/new york" if investor_city_temp=="waterloo/ontario" & investor_state_temp=="canada/new york"
replace investor_city_temp="philadelphia" if investor_city_temp=="philadelphia/philadelphia" & investor_state_temp=="pennsylvania"
replace investor_city_temp="dexter" if investor_city_temp=="philadelphia" & investor_state_temp=="maine"
replace investor_city_temp="portland" if investor_city_temp=="philadelphia" & investor_state_temp=="maine"
replace investor_city_temp="bath" if investor_city_temp=="philadelphia" & investor_state_temp=="maine"
replace investor_city_temp="st petersburg/new york" if investor_city_temp=="st petersburg" & investor_state_temp=="russia/new york"
replace investor_city_temp="st petersburg/new york" if investor_city_temp=="st petersburg" & investor_state_temp=="russia/new york"
replace investor_city_temp="stettin/chicago" if investor_city_temp=="stettin" & investor_state_temp=="germany/illinois"
replace investor_city_temp="stettin/chicago" if investor_city_temp=="stettin" & investor_state_temp=="germany/illinois"
replace investor_city_temp="york/new york" if investor_city_temp=="york" & investor_state_temp=="england/new york"
replace investor_city_temp="new york" if investor_city_temp=="york" & investor_state_temp=="new york"



cd "$root_do"
*Revise Dummy
cap drop investor_state_1 investor_state_2 
cap drop investor_state_3
cap drop dummy_investor_state_*
cap drop _merge dummy
cap drop tag

split investor_state_temp, p("/") gen(investor_state_)
foreach i in "1" "2"{
global x="investor_state_`i'"
replace $x=strtrim($x)
replace $x=stritrim($x)
replace $x=lower($x)
do City_State_Dummy.do
}

*Revise Dummy
cap drop investor_city_1 investor_city_2 
cap drop investor_city_3
cap drop dummy_investor_city_*
cap drop _merge dummy
cap drop tag

split investor_city_temp, p("/") gen(investor_city_)
foreach i in "1" "2"{
global x="investor_city_`i'"
replace $x=strtrim($x)
replace $x=stritrim($x)
replace $x=lower($x)
do City_State_Dummy.do
}
cap drop investor_state_3
replace dummy_investor_city_1=2 if dummy_investor_city_1==12 & industry!="Government"
replace dummy_investor_city_2=2 if dummy_investor_city_2==12 & industry!="Government"
replace dummy_investor_state_1=1 if dummy_investor_state_1==12 & industry!="Government"
replace dummy_investor_state_2=1 if dummy_investor_state_2==12 & industry!="Government"

label var investor_state_temp "Cleaned total region (US State/Foreign Country) for investor"
label var investor_state_1 "Cleaned Primary region (US State/Foreign Country) for investor"
label var investor_state_2 "Cleaned Secondary region (US State/Canada) for investor"
label var dummy_investor_state_1 "Primary region type: domestic or foreign"
label var dummy_investor_state_2 "Secondary region type: domestic or foreign"
label var investor_city_temp "Cleaned investor city, county or township"
label var investor_state_temp "Cleaned investor US state or foreign country"
label var investor_city_1 "Primary investor city, US or Foreign city"
label var investor_city_2 "Secondary investor city, US or Canada branch"
label var dummy_investor_city_1 "Primary city type: domestic or foreign"
label var dummy_investor_city_2 "Secondary city type: domestic or foreign"

cd "$root_do"
do Investor_Name_Dummy.do

order invname_hold_orig investor_id investor_name_master_match3 cname_hold_orig firm_id_holdings issue_id_holdings cname_hold_clean book_year_hold stock_type_hold coupon_hold min_coupon_hold max_coupon_hold maturity_year_hold min_mat_year_hold max_mat_year_hold class_hold investor_city_hold investor_state_hold investor_region1_final_hold investor_region2_final_hold par_value_clean_hold book_value_hold comments_hold investor_type nyse_bond_issuer_id industry cname_hold_temp group_rrry count_rrry group_par count_par group_par2 count_par2 group_geo count_geo group_geo2 count_geo2 group_str count_str invname_hold_temp group_investor investor_state_temp investor_state_1 investor_state_2 dummy_investor_state_1 dummy_investor_state_2 investor_city_temp investor_city_1 investor_city_2 dummy_investor_city_1 dummy_investor_city_2

cap drop _merge
cd "$root_data"
saveold Holdings_Data_InvestorClean_dummy.dta, replace

