*Remove city
replace $x=regexr($x,"new jersey$","") if investor_state_1=="new jersey"
replace $x=regexr($x,"wisconsin$","") if investor_state_1=="wisconsin"
replace $x=regexr($x,"pennsylvania$","") if investor_state_1=="pennsylvania"
replace $x=regexr($x,"massachusetts$","") if investor_state_1=="massachusetts"
replace $x=regexr($x,"connecticut$","") if investor_state_1=="connecticut"
replace $x=regexr($x,"new york$","") if investor_state_1=="new york"
replace $x=regexr($x,"rhode island$","") if investor_state_1=="rhode island"
replace $x=regexr($x,"new hampshire$","") if investor_state_1=="new hampshire"
replace $x=regexr($x,"maine$","") if investor_state_1=="maine"
replace $x=regexr($x,"illinois$","") if investor_state_1=="illinois"
replace $x=regexr($x,"california$","") if investor_state_1=="california"
replace $x=regexr($x,"maryland$","") if investor_state_1=="maryland"
replace $x=regexr($x,"canada$","") if investor_state_1=="canada"
replace $x=regexr($x,"england$","") if investor_state_1=="england"
replace $x=regexr($x,"south dakota$","") if investor_state_1=="south dakota"
replace $x=regexr($x,"ohio$","") if investor_state_1=="ohio"
replace $x=regexr($x,"scotland$","") if investor_state_1=="scotland"
replace $x=regexr($x,"minnesota$","") if investor_state_1=="minnesota"
replace $x=regexr($x,"delaware$","") if investor_state_1=="delaware"
replace $x=regexr($x,"virginia$","") if investor_state_1=="virginia"
replace $x=regexr($x,"west virginia$","") if investor_state_1=="west virginia"
replace $x=regexr($x,"missouri$","") if investor_state_1=="missouri"
replace $x=regexr($x,"michigan$","") if investor_state_1=="michigan"
replace $x=regexr($x,"vermont$","") if investor_state_1=="vermont"
replace $x=regexr($x,"arkansas$","") if investor_state_1=="arkansas"
replace $x=regexr($x,"north carolina$","") if investor_state_1=="north carolina"
replace $x=regexr($x,"kentucky$","") if investor_state_1=="kentucky"
replace $x=regexr($x,"louisiana$","") if investor_state_1=="louisiana"
replace $x=regexr($x,"georgia$","") if investor_state_1=="georgia"
replace $x=regexr($x,"russia$","") if investor_state_1=="russia"
replace $x=regexr($x,"dist. of columbia$","") if investor_state_1=="dist. of columbia"
replace $x=regexr($x,"alabama$","") if investor_state_1=="alabama"
replace $x=regexr($x,"indiana$","") if investor_state_1=="indiana"
replace $x=regexr($x,"tennessee$","") if investor_state_1=="tennessee"
replace $x=regexr($x,"nebraska$","") if investor_state_1=="nebraska"
replace $x=regexr($x,"washington$","") if investor_state_1=="washington"
replace $x=regexr($x,"texas$","") if investor_state_1=="texas"
replace $x=regexr($x,"utah$","") if investor_state_1=="utah"
replace $x=regexr($x,"iowa$","") if investor_state_1=="iowa"

*Replace state
replace $x=regexr($x,"jersey city$","") if investor_city_1=="jersey city"
replace $x=regexr($x,"milwaukee$","") if investor_city_1=="milwaukee"
replace $x=regexr($x,"kingston$","") if investor_city_1=="kingston"
replace $x=regexr($x,"coatesville$","") if investor_city_1=="coatesville"
replace $x=regexr($x,"wilkes barre$","") if investor_city_1=="wilkes barre"
replace $x=regexr($x,"baldwinville$","") if investor_city_1=="baldwinville"
replace $x=regexr($x,"hartford$","") if investor_city_1=="hartford"
replace $x=regexr($x,"philadelphia$","") if investor_city_1=="philadelphia"
replace $x=regexr($x,"meriden$","") if investor_city_1=="meriden"
replace $x=regexr($x,"allentown$","") if investor_city_1=="allentown"
replace $x=regexr($x,"worcester$","") if investor_city_1=="worcester"
replace $x=regexr($x,"new york$","") if investor_city_1=="new york"
replace $x=regexr($x,"scranton$","") if investor_city_1=="scranton"
replace $x=regexr($x,"whitinsville$","") if investor_city_1=="whitinsville"
replace $x=regexr($x,"shamokin$","") if investor_city_1=="shamokin"
replace $x=regexr($x,"wakefield$","") if investor_city_1=="wakefield"
replace $x=regexr($x,"west chester$","") if investor_city_1=="west chester"
replace $x=regexr($x,"portsmouth$","") if investor_city_1=="portsmouth"
replace $x=regexr($x,"holyoke$","") if investor_city_1=="holyoke"
replace $x=regexr($x,"rochester$","") if investor_city_1=="rochester"
replace $x=regexr($x,"new haven$","") if investor_city_1=="new haven"
replace $x=regexr($x,"jamestown$","") if investor_city_1=="jamestown"
replace $x=regexr($x,"saco$","") if investor_city_1=="saco"
replace $x=regexr($x,"arlington$","") if investor_city_1=="arlington"
replace $x=regexr($x,"woburn$","") if investor_city_1=="woburn"
replace $x=regexr($x,"watertown$","") if investor_city_1=="watertown"
replace $x=regexr($x,"albany$","") if investor_city_1=="albany"
replace $x=regexr($x,"chicago$","") if investor_city_1=="chicago"
replace $x=regexr($x,"concord$","") if investor_city_1=="concord"
replace $x=regexr($x,"west hoboken$","") if investor_city_1=="west hoboken"
replace $x=regexr($x,"chelsea$","") if investor_city_1=="chelsea"
replace $x=regexr($x,"danbury$","") if investor_city_1=="danbury"
replace $x=regexr($x,"yreka$","") if investor_city_1=="yreka"
replace $x=regexr($x,"binghamton$","") if investor_city_1=="binghamton"
replace $x=regexr($x,"new brunswick$","") if investor_city_1=="new brunswick"
replace $x=regexr($x,"glens falls$","") if investor_city_1=="glens falls"
replace $x=regexr($x,"andover$","") if investor_city_1=="andover"
replace $x=regexr($x,"norwalk$","") if investor_city_1=="norwalk"
replace $x=regexr($x,"pittston$","") if investor_city_1=="pittston"
replace $x=regexr($x,"york$","") if investor_city_1=="york"
replace $x=regexr($x,"falls village$","") if investor_city_1=="falls village"
replace $x=regexr($x,"gardner$","") if investor_city_1=="gardner"
replace $x=regexr($x,"quincy$","") if investor_city_1=="quincy"
replace $x=regexr($x,"westerly$","") if investor_city_1=="westerly"
replace $x=regexr($x,"gardena$","") if investor_city_1=="gardena"
replace $x=regexr($x,"baltimore$","") if investor_city_1=="baltimore"
replace $x=regexr($x,"montreal$","") if investor_city_1=="montreal"
replace $x=regexr($x,"springfield$","") if investor_city_1=="springfield"
replace $x=regexr($x,"lebanon$","") if investor_city_1=="lebanon"
replace $x=regexr($x,"clarion$","") if investor_city_1=="clarion"
replace $x=regexr($x,"utica$","") if investor_city_1=="utica"
replace $x=regexr($x,"portland$","") if investor_city_1=="portland"
replace $x=regexr($x,"lynn$","") if investor_city_1=="lynn"
replace $x=regexr($x,"buffalo$","") if investor_city_1=="buffalo"
replace $x=regexr($x,"randolph$","") if investor_city_1=="randolph"
replace $x=regexr($x,"oakland$","") if investor_city_1=="oakland"
replace $x=regexr($x,"mountain view$","") if investor_city_1=="mountain view"
replace $x=regexr($x,"meredith$","") if investor_city_1=="meredith"
replace $x=regexr($x,"newton$","") if investor_city_1=="newton"
replace $x=regexr($x,"woonsocket$","") if investor_city_1=="woonsocket"
replace $x=regexr($x,"salem$","") if investor_city_1=="salem"
replace $x=regexr($x,"cambridge$","") if investor_city_1=="cambridge"
replace $x=regexr($x,"rockville$","") if investor_city_1=="rockville"
replace $x=regexr($x,"richmond$","") if investor_city_1=="richmond"
replace $x=regexr($x,"rhinebeck$","") if investor_city_1=="rhinebeck"
replace $x=regexr($x,"litchfield$","") if investor_city_1=="litchfield"
replace $x=regexr($x,"bridgton$","") if investor_city_1=="bridgton"
replace $x=regexr($x,"sioux falls$","") if investor_city_1=="sioux falls"
replace $x=regexr($x,"auburn$","") if investor_city_1=="auburn"
replace $x=regexr($x,"san francisco$","") if investor_city_1=="san francisco"
replace $x=regexr($x,"white haven$","") if investor_city_1=="white haven"
replace $x=regexr($x,"franklin$","") if investor_city_1=="franklin"
replace $x=regexr($x,"lenox$","") if investor_city_1=="lenox"
replace $x=regexr($x,"bangor$","") if investor_city_1=="bangor"
replace $x=regexr($x,"manchester$","") if investor_city_1=="manchester"
replace $x=regexr($x,"pittsfield$","") if investor_city_1=="pittsfield"
replace $x=regexr($x,"pittsburg$","") if investor_city_1=="pittsburg"
replace $x=regexr($x,"newport$","") if investor_city_1=="newport"
replace $x=regexr($x,"middletown$","") if investor_city_1=="middletown"
replace $x=regexr($x,"los angeles$","") if investor_city_1=="los angeles"
replace $x=regexr($x,"ware$","") if investor_city_1=="ware"
replace $x=regexr($x,"roxbury$","") if investor_city_1=="roxbury"
replace $x=regexr($x,"providence$","") if investor_city_1=="providence"
replace $x=regexr($x,"passaic$","") if investor_city_1=="passaic"
replace $x=regexr($x,"machias$","") if investor_city_1=="machias"
replace $x=regexr($x,"colebrook$","") if investor_city_1=="colebrook"
replace $x=regexr($x,"barre$","") if investor_city_1=="barre"
replace $x=regexr($x,"belfast$","") if investor_city_1=="belfast"
replace $x=regexr($x,"haverhill$","") if investor_city_1=="haverhill"
replace $x=regexr($x,"nashua$","") if investor_city_1=="nashua"
replace $x=regexr($x,"weymouth$","") if investor_city_1=="weymouth"
replace $x=regexr($x,"lakeville$","") if investor_city_1=="lakeville"
replace $x=regexr($x,"provincetown$","") if investor_city_1=="provincetown"
replace $x=regexr($x,"nyack$","") if investor_city_1=="nyack"
replace $x=regexr($x,"greenfield$","") if investor_city_1=="greenfield"
replace $x=regexr($x,"trenton$","") if investor_city_1=="trenton"
replace $x=regexr($x,"brunswick$","") if investor_city_1=="brunswick"
replace $x=regexr($x,"thomaston$","") if investor_city_1=="thomaston"
replace $x=regexr($x,"warren$","") if investor_city_1=="warren"
replace $x=regexr($x,"lowell$","") if investor_city_1=="lowell"
replace $x=regexr($x,"harwich$","") if investor_city_1=="harwich"
replace $x=regexr($x,"apollo$","") if investor_city_1=="apollo"
replace $x=regexr($x,"erie$","") if investor_city_1=="erie"
replace $x=regexr($x,"elizabeth$","") if investor_city_1=="elizabeth"
replace $x=regexr($x,"plymouth$","") if investor_city_1=="plymouth"
replace $x=regexr($x,"coudersport$","") if investor_city_1=="coudersport"
replace $x=regexr($x,"walpole$","") if investor_city_1=="walpole"
replace $x=regexr($x,"jenkintown$","") if investor_city_1=="jenkintown"
replace $x=regexr($x,"wiscasset$","") if investor_city_1=="wiscasset"
replace $x=regexr($x,"lewiston$","") if investor_city_1=="lewiston"
replace $x=regexr($x,"yonkers$","") if investor_city_1=="yonkers"
replace $x=regexr($x,"cincinnati$","") if investor_city_1=="cincinnati"
replace $x=regexr($x,"dixon$","") if investor_city_1=="dixon"
replace $x=regexr($x,"sonora$","") if investor_city_1=="sonora"
replace $x=regexr($x,"camden$","") if investor_city_1=="camden"
replace $x=regexr($x,"pottsville$","") if investor_city_1=="pottsville"
replace $x=regexr($x,"newark$","") if investor_city_1=="newark"
replace $x=regexr($x,"newburgh$","") if investor_city_1=="newburgh"
replace $x=regexr($x,"edinburgh$","") if investor_city_1=="edinburgh"
replace $x=regexr($x,"bath$","") if investor_city_1=="bath"
replace $x=regexr($x,"bridgeport$","") if investor_city_1=="bridgeport"
replace $x=regexr($x,"bloomfield$","") if investor_city_1=="bloomfield"
replace $x=regexr($x,"st paul$","") if investor_city_1=="st paul"
replace $x=regexr($x,"pawtucket$","") if investor_city_1=="pawtucket"
replace $x=regexr($x,"webster$","") if investor_city_1=="webster"
replace $x=regexr($x,"medford$","") if investor_city_1=="medford"
replace $x=regexr($x,"wilmington$","") if investor_city_1=="wilmington"
replace $x=regexr($x,"fall river$","") if investor_city_1=="fall river"
replace $x=regexr($x,"somerville$","") if investor_city_1=="somerville"
replace $x=regexr($x,"gardiner$","") if investor_city_1=="gardiner"
replace $x=regexr($x,"freeland$","") if investor_city_1=="freeland"
replace $x=regexr($x,"biddeford$","") if investor_city_1=="biddeford"
replace $x=regexr($x,"haydenville$","") if investor_city_1=="haydenville"
replace $x=regexr($x,"port chester$","") if investor_city_1=="port chester"
replace $x=regexr($x,"abington$","") if investor_city_1=="abington"
replace $x=regexr($x,"moorestown$","") if investor_city_1=="moorestown"
replace $x=regexr($x,"honesdale$","") if investor_city_1=="honesdale"
replace $x=regexr($x,"troy$","") if investor_city_1=="troy"
replace $x=regexr($x,"london$","") if investor_city_1=="london"
replace $x=regexr($x,"titusville$","") if investor_city_1=="titusville"
replace $x=regexr($x,"easton$","") if investor_city_1=="easton"
replace $x=regexr($x,"east orange$","") if investor_city_1=="east orange"
replace $x=regexr($x,"new bedford$","") if investor_city_1=="new bedford"
replace $x=regexr($x,"carbondale$","") if investor_city_1=="carbondale"
replace $x=regexr($x,"everett$","") if investor_city_1=="everett"
replace $x=regexr($x,"reading$","") if investor_city_1=="reading"
replace $x=regexr($x,"brooklyn$","") if investor_city_1=="brooklyn"
replace $x=regexr($x,"jersey shore$","") if investor_city_1=="jersey shore"
replace $x=regexr($x,"waterville$","") if investor_city_1=="waterville"
replace $x=regexr($x,"marlborough$","") if investor_city_1=="marlborough"
replace $x=regexr($x,"chester$","") if investor_city_1=="chester"
replace $x=regexr($x,"centreville$","") if investor_city_1=="centreville"
replace $x=regexr($x,"alton$","") if investor_city_1=="alton"
replace $x=regexr($x,"danielson$","") if investor_city_1=="danielson"
replace $x=regexr($x,"natick$","") if investor_city_1=="natick"
replace $x=regexr($x,"wheeling$","") if investor_city_1=="wheeling"
replace $x=regexr($x,"farmington$","") if investor_city_1=="farmington"
replace $x=regexr($x,"south paris$","") if investor_city_1=="south paris"
replace $x=regexr($x,"burlington$","") if investor_city_1=="burlington"
replace $x=regexr($x,"rockland$","") if investor_city_1=="rockland"
replace $x=regexr($x,"saratoga springs$","") if investor_city_1=="saratoga springs"
replace $x=regexr($x,"doylestown$","") if investor_city_1=="doylestown"
replace $x=regexr($x,"waterbury$","") if investor_city_1=="waterbury"
replace $x=regexr($x,"st clair$","") if investor_city_1=="st clair"
replace $x=regexr($x,"liverpool$","") if investor_city_1=="liverpool"
replace $x=regexr($x,"yarmouthport$","") if investor_city_1=="yarmouthport"
replace $x=regexr($x,"poughkeepsie$","") if investor_city_1=="poughkeepsie"
replace $x=regexr($x,"ithaca$","") if investor_city_1=="ithaca"
replace $x=regexr($x,"toronto$","") if investor_city_1=="toronto"
replace $x=regexr($x,"newtown$","") if investor_city_1=="newtown"
replace $x=regexr($x,"conway$","") if investor_city_1=="conway"
replace $x=regexr($x,"waterloo$","") if investor_city_1=="waterloo"
replace $x=regexr($x,"south framingham$","") if investor_city_1=="south framingham"
replace $x=regexr($x,"ansonia$","") if investor_city_1=="ansonia"
replace $x=regexr($x,"chicopee$","") if investor_city_1=="chicopee"
replace $x=regexr($x,"mount holly$","") if investor_city_1=="mount holly"
replace $x=regexr($x,"st louis$","") if investor_city_1=="st louis"
replace $x=regexr($x,"woodbury$","") if investor_city_1=="woodbury"
replace $x=regexr($x,"dedham$","") if investor_city_1=="dedham"
replace $x=regexr($x,"hingham$","") if investor_city_1=="hingham"
replace $x=regexr($x,"sunbury$","") if investor_city_1=="sunbury"
replace $x=regexr($x,"foxborough$","") if investor_city_1=="foxborough"
replace $x=regexr($x,"dover$","") if investor_city_1=="dover"
replace $x=regexr($x,"mount vernon$","") if investor_city_1=="mount vernon"
replace $x=regexr($x,"ridgewood$","") if investor_city_1=="ridgewood"
replace $x=regexr($x,"skowhegan$","") if investor_city_1=="skowhegan"
replace $x=regexr($x,"williamsport$","") if investor_city_1=="williamsport"
replace $x=regexr($x,"winsted$","") if investor_city_1=="winsted"
replace $x=regexr($x,"kennebunk$","") if investor_city_1=="kennebunk"
replace $x=regexr($x,"essex$","") if investor_city_1=="essex"
replace $x=regexr($x,"eastport$","") if investor_city_1=="eastport"
replace $x=regexr($x,"ludlow$","") if investor_city_1=="ludlow"
replace $x=regexr($x,"new britain$","") if investor_city_1=="new britain"
replace $x=regexr($x,"grass valley$","") if investor_city_1=="grass valley"
replace $x=regexr($x,"searsport$","") if investor_city_1=="searsport"
replace $x=regexr($x,"harrisburg$","") if investor_city_1=="harrisburg"
replace $x=regexr($x,"norwich$","") if investor_city_1=="norwich"
replace $x=regexr($x,"stamford$","") if investor_city_1=="stamford"
replace $x=regexr($x,"hershey$","") if investor_city_1=="hershey"
replace $x=regexr($x,"paterson$","") if investor_city_1=="paterson"
replace $x=regexr($x,"east boston$","") if investor_city_1=="east boston"
replace $x=regexr($x,"fitchburg$","") if investor_city_1=="fitchburg"
replace $x=regexr($x,"syracuse$","") if investor_city_1=="syracuse"
replace $x=regexr($x,"ashland$","") if investor_city_1=="ashland"
replace $x=regexr($x,"detroit$","") if investor_city_1=="detroit"
replace $x=regexr($x,"colfax$","") if investor_city_1=="colfax"
replace $x=regexr($x,"southington$","") if investor_city_1=="southington"
replace $x=regexr($x,"east jaffrey$","") if investor_city_1=="east jaffrey"
replace $x=regexr($x,"hallowell$","") if investor_city_1=="hallowell"
replace $x=regexr($x,"naugatuck$","") if investor_city_1=="naugatuck"
replace $x=regexr($x,"hyde park$","") if investor_city_1=="hyde park"
replace $x=regexr($x,"florence$","") if investor_city_1=="florence"
replace $x=regexr($x,"hagerstown$","") if investor_city_1=="hagerstown"
replace $x=regexr($x,"schenectady$","") if investor_city_1=="schenectady"
replace $x=regexr($x,"bristol$","") if investor_city_1=="bristol"
replace $x=regexr($x,"lawrence$","") if investor_city_1=="lawrence"
replace $x=regexr($x,"atlantic city$","") if investor_city_1=="atlantic city"
replace $x=regexr($x,"freeport$","") if investor_city_1=="freeport"
replace $x=regexr($x,"north brookfield$","") if investor_city_1=="north brookfield"
replace $x=regexr($x,"gorham$","") if investor_city_1=="gorham"
replace $x=regexr($x,"wareham$","") if investor_city_1=="wareham"
replace $x=regexr($x,"stoneham$","") if investor_city_1=="stoneham"
replace $x=regexr($x,"keene$","") if investor_city_1=="keene"
replace $x=regexr($x,"jamaica$","") if investor_city_1=="jamaica"
replace $x=regexr($x,"nantucket$","") if investor_city_1=="nantucket"
replace $x=regexr($x,"fordyce$","") if investor_city_1=="fordyce"
replace $x=regexr($x,"shelton$","") if investor_city_1=="shelton"
replace $x=regexr($x,"lancaster$","") if investor_city_1=="lancaster"
replace $x=regexr($x,"dunsmuir$","") if investor_city_1=="dunsmuir"
replace $x=regexr($x,"south norwalk$","") if investor_city_1=="south norwalk"
replace $x=regexr($x,"taunton$","") if investor_city_1=="taunton"
replace $x=regexr($x,"lewisburg$","") if investor_city_1=="lewisburg"
replace $x=regexr($x,"derby$","") if investor_city_1=="derby"
replace $x=regexr($x,"womelsdorf$","") if investor_city_1=="womelsdorf"
replace $x=regexr($x,"lockport$","") if investor_city_1=="lockport"
replace $x=regexr($x,"mauch chunk$","") if investor_city_1=="mauch chunk"
replace $x=regexr($x,"altoona$","") if investor_city_1=="altoona"
replace $x=regexr($x,"summit$","") if investor_city_1=="summit"
replace $x=regexr($x,"laconia$","") if investor_city_1=="laconia"
replace $x=regexr($x,"greensburg$","") if investor_city_1=="greensburg"
replace $x=regexr($x,"fredonia$","") if investor_city_1=="fredonia"
replace $x=regexr($x,"adams$","") if investor_city_1=="adams"
replace $x=regexr($x,"montclair$","") if investor_city_1=="montclair"
replace $x=regexr($x,"northampton$","") if investor_city_1=="northampton"
replace $x=regexr($x,"white plains$","") if investor_city_1=="white plains"
replace $x=regexr($x,"turners falls$","") if investor_city_1=="turners falls"
replace $x=regexr($x,"lock haven$","") if investor_city_1=="lock haven"
replace $x=regexr($x,"exeter$","") if investor_city_1=="exeter"
replace $x=regexr($x,"athol$","") if investor_city_1=="athol"
replace $x=regexr($x,"belmont$","") if investor_city_1=="belmont"
replace $x=regexr($x,"augusta$","") if investor_city_1=="augusta"
replace $x=regexr($x,"south weymouth$","") if investor_city_1=="south weymouth"
replace $x=regexr($x,"hanover$","") if investor_city_1=="hanover"
replace $x=regexr($x,"new bethlehem$","") if investor_city_1=="new bethlehem"
replace $x=regexr($x,"salinas$","") if investor_city_1=="salinas"
replace $x=regexr($x,"bryn mawr$","") if investor_city_1=="bryn mawr"
replace $x=regexr($x,"leominster$","") if investor_city_1=="leominster"
replace $x=regexr($x,"fairfield$","") if investor_city_1=="fairfield"
replace $x=regexr($x,"amherst$","") if investor_city_1=="amherst"
replace $x=regexr($x,"greensboro$","") if investor_city_1=="greensboro"
replace $x=regexr($x,"peterborough$","") if investor_city_1=="peterborough"
replace $x=regexr($x,"eureka$","") if investor_city_1=="eureka"
replace $x=regexr($x,"littleton$","") if investor_city_1=="littleton"
replace $x=regexr($x,"matteawan$","") if investor_city_1=="matteawan"
replace $x=regexr($x,"merrimac$","") if investor_city_1=="merrimac"
replace $x=regexr($x,"whitman$","") if investor_city_1=="whitman"
replace $x=regexr($x,"easthampton$","") if investor_city_1=="easthampton"
replace $x=regexr($x,"deep river$","") if investor_city_1=="deep river"
replace $x=regexr($x,"archbald$","") if investor_city_1=="archbald"
replace $x=regexr($x,"shenandoah$","") if investor_city_1=="shenandoah"
replace $x=regexr($x,"sharon$","") if investor_city_1=="sharon"
replace $x=regexr($x,"quakertown$","") if investor_city_1=="quakertown"
replace $x=regexr($x,"rockport$","") if investor_city_1=="rockport"
replace $x=regexr($x,"pottstown$","") if investor_city_1=="pottstown"
replace $x=regexr($x,"medway$","") if investor_city_1=="medway"
replace $x=regexr($x,"westfield$","") if investor_city_1=="westfield"
replace $x=regexr($x,"winchester$","") if investor_city_1=="winchester"
replace $x=regexr($x,"mifflinburg$","") if investor_city_1=="mifflinburg"
replace $x=regexr($x,"putnam$","") if investor_city_1=="putnam"
replace $x=regexr($x,"wheatland$","") if investor_city_1=="wheatland"
replace $x=regexr($x,"milford$","") if investor_city_1=="milford"
replace $x=regexr($x,"huntingdon$","") if investor_city_1=="huntingdon"
replace $x=regexr($x,"sharpsburg$","") if investor_city_1=="sharpsburg"
replace $x=regexr($x,"calais$","") if investor_city_1=="calais"
replace $x=regexr($x,"orange$","") if investor_city_1=="orange"
replace $x=regexr($x,"north easton$","") if investor_city_1=="north easton"
replace $x=regexr($x,"plainfield$","") if investor_city_1=="plainfield"
replace $x=regexr($x,"beverly$","") if investor_city_1=="beverly"
replace $x=regexr($x,"palmer$","") if investor_city_1=="palmer"
replace $x=regexr($x,"somersworth$","") if investor_city_1=="somersworth"
replace $x=regexr($x,"media$","") if investor_city_1=="media"
replace $x=regexr($x,"san luis obispo$","") if investor_city_1=="san luis obispo"
replace $x=regexr($x,"redding$","") if investor_city_1=="redding"
replace $x=regexr($x,"niagara falls$","") if investor_city_1=="niagara falls"
replace $x=regexr($x,"beaver$","") if investor_city_1=="beaver"
replace $x=regexr($x,"sacramento$","") if investor_city_1=="sacramento"
replace $x=regexr($x,"ayer$","") if investor_city_1=="ayer"
replace $x=regexr($x,"north eastern$","") if investor_city_1=="north eastern"
replace $x=regexr($x,"meadville$","") if investor_city_1=="meadville"
replace $x=regexr($x,"oil city$","") if investor_city_1=="oil city"
replace $x=regexr($x,"norway$","") if investor_city_1=="norway"
replace $x=regexr($x,"tacony$","") if investor_city_1=="tacony"
replace $x=regexr($x,"healdsburg$","") if investor_city_1=="healdsburg"
replace $x=regexr($x,"southport$","") if investor_city_1=="southport"
replace $x=regexr($x,"johnstown$","") if investor_city_1=="johnstown"
replace $x=regexr($x,"chambersburg$","") if investor_city_1=="chambersburg"
replace $x=regexr($x,"annville$","") if investor_city_1=="annville"
replace $x=regexr($x,"phillips$","") if investor_city_1=="phillips"
replace $x=regexr($x,"phoenixville$","") if investor_city_1=="phoenixville"
replace $x=regexr($x,"norristown$","") if investor_city_1=="norristown"
replace $x=regexr($x,"leicester$","") if investor_city_1=="leicester"
replace $x=regexr($x,"east weymouth$","") if investor_city_1=="east weymouth"
replace $x=regexr($x,"chico$","") if investor_city_1=="chico"
replace $x=regexr($x,"alameda$","") if investor_city_1=="alameda"
replace $x=regexr($x,"greenville$","") if investor_city_1=="greenville"
replace $x=regexr($x,"olyphant$","") if investor_city_1=="olyphant"
replace $x=regexr($x,"millbury$","") if investor_city_1=="millbury"
replace $x=regexr($x,"morrisville$","") if investor_city_1=="morrisville"
replace $x=regexr($x,"georgetown$","") if investor_city_1=="georgetown"
replace $x=regexr($x,"louisville$","") if investor_city_1=="louisville"
replace $x=regexr($x,"harrison$","") if investor_city_1=="harrison"
replace $x=regexr($x,"windber$","") if investor_city_1=="windber"
replace $x=regexr($x,"kittanning$","") if investor_city_1=="kittanning"
replace $x=regexr($x,"south san francisco$","") if investor_city_1=="south san francisco"
replace $x=regexr($x,"new orleans$","") if investor_city_1=="new orleans"
replace $x=regexr($x,"east bridgewater$","") if investor_city_1=="east bridgewater"
replace $x=regexr($x,"new london$","") if investor_city_1=="new london"
replace $x=regexr($x,"canaan$","") if investor_city_1=="canaan"
replace $x=regexr($x,"waverly$","") if investor_city_1=="waverly"
replace $x=regexr($x,"morristown$","") if investor_city_1=="morristown"
replace $x=regexr($x,"wallingford$","") if investor_city_1=="wallingford"
replace $x=regexr($x,"ukiah$","") if investor_city_1=="ukiah"
replace $x=regexr($x,"buxton$","") if investor_city_1=="buxton"
replace $x=regexr($x,"winters$","") if investor_city_1=="winters"
replace $x=regexr($x,"windsor locks$","") if investor_city_1=="windsor locks"
replace $x=regexr($x,"cranford$","") if investor_city_1=="cranford"
replace $x=regexr($x,"suffield$","") if investor_city_1=="suffield"
replace $x=regexr($x,"lee$","") if investor_city_1=="lee"
replace $x=regexr($x,"elmira$","") if investor_city_1=="elmira"
replace $x=regexr($x,"englewood$","") if investor_city_1=="englewood"
replace $x=regexr($x,"allegheny$","") if investor_city_1=="allegheny"
replace $x=regexr($x,"fulton$","") if investor_city_1=="fulton"
replace $x=regexr($x,"bayonne$","") if investor_city_1=="bayonne"
replace $x=regexr($x,"marysville$","") if investor_city_1=="marysville"
replace $x=regexr($x,"tremont$","") if investor_city_1=="tremont"
replace $x=regexr($x,"stockton$","") if investor_city_1=="stockton"
replace $x=regexr($x,"wickford$","") if investor_city_1=="wickford"
replace $x=regexr($x,"middleborough$","") if investor_city_1=="middleborough"
replace $x=regexr($x,"california$","") if investor_city_1=="california"
replace $x=regexr($x,"punxsutawney$","") if investor_city_1=="punxsutawney"
replace $x=regexr($x,"du bois$","") if investor_city_1=="du bois"
replace $x=regexr($x,"peabody$","") if investor_city_1=="peabody"
replace $x=regexr($x,"brockton$","") if investor_city_1=="brockton"
replace $x=regexr($x,"dorchester$","") if investor_city_1=="dorchester"
replace $x=regexr($x,"lakewood$","") if investor_city_1=="lakewood"
replace $x=regexr($x,"lansdowne$","") if investor_city_1=="lansdowne"
replace $x=regexr($x,"wellfleet$","") if investor_city_1=="wellfleet"
replace $x=regexr($x,"covington$","") if investor_city_1=="covington"
replace $x=regexr($x,"fortuna$","") if investor_city_1=="fortuna"
replace $x=regexr($x,"south farmington$","") if investor_city_1=="south farmington"
replace $x=regexr($x,"kutztown$","") if investor_city_1=="kutztown"
replace $x=regexr($x,"south berwick$","") if investor_city_1=="south berwick"
replace $x=regexr($x,"glen lyon$","") if investor_city_1=="glen lyon"
replace $x=regexr($x,"houlton$","") if investor_city_1=="houlton"
replace $x=regexr($x,"winchendon$","") if investor_city_1=="winchendon"
replace $x=regexr($x,"athens$","") if investor_city_1=="athens"
replace $x=regexr($x,"suisun$","") if investor_city_1=="suisun"
replace $x=regexr($x,"south braintree$","") if investor_city_1=="south braintree"
replace $x=regexr($x,"williamstown$","") if investor_city_1=="williamstown"
replace $x=regexr($x,"new rochelle$","") if investor_city_1=="new rochelle"
replace $x=regexr($x,"porterville$","") if investor_city_1=="porterville"
replace $x=regexr($x,"hudson$","") if investor_city_1=="hudson"
replace $x=regexr($x,"hoboken$","") if investor_city_1=="hoboken"
replace $x=regexr($x,"bakersfield$","") if investor_city_1=="bakersfield"
replace $x=regexr($x,"walnut creek$","") if investor_city_1=="walnut creek"
replace $x=regexr($x,"st petersburg$","") if investor_city_1=="st petersburg"
replace $x=regexr($x,"guilford$","") if investor_city_1=="guilford"
replace $x=regexr($x,"toms river$","") if investor_city_1=="toms river"
replace $x=regexr($x,"braddock$","") if investor_city_1=="braddock"
replace $x=regexr($x,"sayre$","") if investor_city_1=="sayre"
replace $x=regexr($x,"woodland$","") if investor_city_1=="woodland"
replace $x=regexr($x,"gloucester$","") if investor_city_1=="gloucester"
replace $x=regexr($x,"long beach$","") if investor_city_1=="long beach"
replace $x=regexr($x,"somerset$","") if investor_city_1=="somerset"
replace $x=regexr($x,"hamilton$","") if investor_city_1=="hamilton"
replace $x=regexr($x,"bethlehem$","") if investor_city_1=="bethlehem"
replace $x=regexr($x,"fairhaven$","") if investor_city_1=="fairhaven"
replace $x=regexr($x,"washington$","") if investor_city_1=="washington"
replace $x=regexr($x,"charlestown$","") if investor_city_1=="charlestown"
replace $x=regexr($x,"mobile$","") if investor_city_1=="mobile"
replace $x=regexr($x,"farrell$","") if investor_city_1=="farrell"
replace $x=regexr($x,"brewer$","") if investor_city_1=="brewer"
replace $x=regexr($x,"west newton$","") if investor_city_1=="west newton"
replace $x=regexr($x,"monson$","") if investor_city_1=="monson"
replace $x=regexr($x,"ipswich$","") if investor_city_1=="ipswich"
replace $x=regexr($x,"lykens$","") if investor_city_1=="lykens"
replace $x=regexr($x,"bridgewater$","") if investor_city_1=="bridgewater"
replace $x=regexr($x,"hamburg$","") if investor_city_1=="hamburg"
replace $x=regexr($x,"mineola$","") if investor_city_1=="mineola"
replace $x=regexr($x,"perth amboy$","") if investor_city_1=="perth amboy"
replace $x=regexr($x,"carlisle$","") if investor_city_1=="carlisle"
replace $x=regexr($x,"ellsworth$","") if investor_city_1=="ellsworth"
replace $x=regexr($x,"petersburg$","") if investor_city_1=="petersburg"
replace $x=regexr($x,"waynesboro$","") if investor_city_1=="waynesboro"
replace $x=regexr($x,"norwell$","") if investor_city_1=="norwell"
replace $x=regexr($x,"napa$","") if investor_city_1=="napa"
replace $x=regexr($x,"pasadena$","") if investor_city_1=="pasadena"
replace $x=regexr($x,"new oxford$","") if investor_city_1=="new oxford"
replace $x=regexr($x,"east cambridge$","") if investor_city_1=="east cambridge"
replace $x=regexr($x,"ridgefield$","") if investor_city_1=="ridgefield"
replace $x=regexr($x,"salamanca$","") if investor_city_1=="salamanca"
replace $x=regexr($x,"bellevue$","") if investor_city_1=="bellevue"
replace $x=regexr($x,"red bluff$","") if investor_city_1=="red bluff"
replace $x=regexr($x,"indianapolis$","") if investor_city_1=="indianapolis"
replace $x=regexr($x,"wellsboro$","") if investor_city_1=="wellsboro"
replace $x=regexr($x,"oswego$","") if investor_city_1=="oswego"
replace $x=regexr($x,"halifax$","") if investor_city_1=="halifax"
replace $x=regexr($x,"seneca falls$","") if investor_city_1=="seneca falls"
replace $x=regexr($x,"perth$","") if investor_city_1=="perth"
replace $x=regexr($x,"rome$","") if investor_city_1=="rome"
replace $x=regexr($x,"mcdonald$","") if investor_city_1=="mcdonald"
replace $x=regexr($x,"canton$","") if investor_city_1=="canton"
replace $x=regexr($x,"cortland$","") if investor_city_1=="cortland"
replace $x=regexr($x,"beaver falls$","") if investor_city_1=="beaver falls"
replace $x=regexr($x,"boothbay harbor$","") if investor_city_1=="boothbay harbor"
replace $x=regexr($x,"littlestown$","") if investor_city_1=="littlestown"
replace $x=regexr($x,"torrington$","") if investor_city_1=="torrington"
replace $x=regexr($x,"rock island$","") if investor_city_1=="rock island"
replace $x=regexr($x,"lexington$","") if investor_city_1=="lexington"
replace $x=regexr($x,"waltham$","") if investor_city_1=="waltham"
replace $x=regexr($x,"tilton$","") if investor_city_1=="tilton"
replace $x=regexr($x,"newburyport$","") if investor_city_1=="newburyport"
replace $x=regexr($x,"woodsville$","") if investor_city_1=="woodsville"
replace $x=regexr($x,"charleroi$","") if investor_city_1=="charleroi"
replace $x=regexr($x,"memphis$","") if investor_city_1=="memphis"
replace $x=regexr($x,"shelburne falls$","") if investor_city_1=="shelburne falls"
replace $x=regexr($x,"mystic$","") if investor_city_1=="mystic"
replace $x=regexr($x,"west toronto$","") if investor_city_1=="west toronto"
replace $x=regexr($x,"st marys$","") if investor_city_1=="st marys"
replace $x=regexr($x,"hillsborough$","") if investor_city_1=="hillsborough"
replace $x=regexr($x,"dillsburg$","") if investor_city_1=="dillsburg"
replace $x=regexr($x,"monongahela$","") if investor_city_1=="monongahela"
replace $x=regexr($x,"duquesne$","") if investor_city_1=="duquesne"
replace $x=regexr($x,"clinton$","") if investor_city_1=="clinton"
replace $x=regexr($x,"shrewsbury$","") if investor_city_1=="shrewsbury"
replace $x=regexr($x,"omaha$","") if investor_city_1=="omaha"
replace $x=regexr($x,"angels camp$","") if investor_city_1=="angels camp"
replace $x=regexr($x,"santa cruz$","") if investor_city_1=="santa cruz"
replace $x=regexr($x,"winnipeg$","") if investor_city_1=="winnipeg"
replace $x=regexr($x,"fresno$","") if investor_city_1=="fresno"
replace $x=regexr($x,"nevada city$","") if investor_city_1=="nevada city"
replace $x=regexr($x,"hazleton$","") if investor_city_1=="hazleton"
replace $x=regexr($x,"woodstown$","") if investor_city_1=="woodstown"
replace $x=regexr($x,"south bethlehem$","") if investor_city_1=="south bethlehem"
replace $x=regexr($x,"bethel$","") if investor_city_1=="bethel"
replace $x=regexr($x,"raleigh$","") if investor_city_1=="raleigh"
replace $x=regexr($x,"patchogue$","") if investor_city_1=="patchogue"
replace $x=regexr($x,"north adams$","") if investor_city_1=="north adams"
replace $x=regexr($x,"pinole$","") if investor_city_1=="pinole"
replace $x=regexr($x,"moodus$","") if investor_city_1=="moodus"
replace $x=regexr($x,"indiana$","") if investor_city_1=="indiana"
replace $x=regexr($x,"glen ridge$","") if investor_city_1=="glen ridge"
replace $x=regexr($x,"berwick$","") if investor_city_1=="berwick"
replace $x=regexr($x,"kingfield$","") if investor_city_1=="kingfield"
replace $x=regexr($x,"pawling$","") if investor_city_1=="pawling"
replace $x=regexr($x,"salmon falls$","") if investor_city_1=="salmon falls"
replace $x=regexr($x,"norfolk$","") if investor_city_1=="norfolk"
replace $x=regexr($x,"san bernardino$","") if investor_city_1=="san bernardino"
replace $x=regexr($x,"stafford springs$","") if investor_city_1=="stafford springs"
replace $x=regexr($x,"seattle$","") if investor_city_1=="seattle"
replace $x=regexr($x,"butler$","") if investor_city_1=="butler"
replace $x=regexr($x,"vineland$","") if investor_city_1=="vineland"
replace $x=regexr($x,"stroudsburg$","") if investor_city_1=="stroudsburg"
replace $x=regexr($x,"maiden$","") if investor_city_1=="maiden"
replace $x=regexr($x,"suffolk$","") if investor_city_1=="suffolk"
replace $x=regexr($x,"dinuba$","") if investor_city_1=="dinuba"
replace $x=regexr($x,"willows$","") if investor_city_1=="willows"
replace $x=regexr($x,"houston$","") if investor_city_1=="houston"
replace $x=regexr($x,"willits$","") if investor_city_1=="willits"
replace $x=regexr($x,"willimantic$","") if investor_city_1=="willimantic"
replace $x=regexr($x,"spencer$","") if investor_city_1=="spencer"
replace $x=regexr($x,"roslyn$","") if investor_city_1=="roslyn"
replace $x=regexr($x,"newton centre$","") if investor_city_1=="newton centre"
replace $x=regexr($x,"southbridge$","") if investor_city_1=="southbridge"
replace $x=regexr($x,"brookline$","") if investor_city_1=="brookline"
replace $x=regexr($x,"clearfield$","") if investor_city_1=="clearfield"
replace $x=regexr($x,"connellsville$","") if investor_city_1=="connellsville"
replace $x=regexr($x,"williams$","") if investor_city_1=="williams"
replace $x=regexr($x,"wilkinsburg$","") if investor_city_1=="wilkinsburg"
replace $x=regexr($x,"catskill$","") if investor_city_1=="catskill"
replace $x=regexr($x,"malden$","") if investor_city_1=="malden"
replace $x=regexr($x,"waynesburg$","") if investor_city_1=="waynesburg"
replace $x=regexr($x,"oak park$","") if investor_city_1=="oak park"
replace $x=regexr($x,"hemet$","") if investor_city_1=="hemet"
replace $x=regexr($x,"salt lake city$","") if investor_city_1=="salt lake city"
replace $x=regexr($x,"danvers$","") if investor_city_1=="danvers"
replace $x=regexr($x,"holliston$","") if investor_city_1=="holliston"
replace $x=regexr($x,"new kensington$","") if investor_city_1=="new kensington"
replace $x=regexr($x,"glen cove$","") if investor_city_1=="glen cove"
replace $x=regexr($x,"madison$","") if investor_city_1=="madison"
replace $x=regexr($x,"cohasset$","") if investor_city_1=="cohasset"
replace $x=regexr($x,"great barrington$","") if investor_city_1=="great barrington"
replace $x=regexr($x,"dayton$","") if investor_city_1=="dayton"
replace $x=regexr($x,"royersford$","") if investor_city_1=="royersford"
replace $x=regexr($x,"grafton$","") if investor_city_1=="grafton"
replace $x=regexr($x,"collinsville$","") if investor_city_1=="collinsville"
replace $x=regexr($x,"skaneateles$","") if investor_city_1=="skaneateles"
replace $x=regexr($x,"mahanoy city$","") if investor_city_1=="mahanoy city"
replace $x=regexr($x,"hammonton$","") if investor_city_1=="hammonton"
replace $x=regexr($x,"new milford$","") if investor_city_1=="new milford"
replace $x=regexr($x,"whittier$","") if investor_city_1=="whittier"
replace $x=regexr($x,"hopkinton$","") if investor_city_1=="hopkinton"
replace $x=regexr($x,"whiting$","") if investor_city_1=="whiting"
replace $x=regexr($x,"lincoln$","") if investor_city_1=="lincoln"
replace $x=regexr($x,"san pedro$","") if investor_city_1=="san pedro"
replace $x=regexr($x,"new brighton$","") if investor_city_1=="new brighton"
replace $x=regexr($x,"elizabethtown$","") if investor_city_1=="elizabethtown"
replace $x=regexr($x,"kern$","") if investor_city_1=="kern"
replace $x=regexr($x,"hammond$","") if investor_city_1=="hammond"
replace $x=regexr($x,"westport$","") if investor_city_1=="westport"
replace $x=regexr($x,"westminster$","") if investor_city_1=="westminster"
replace $x=regexr($x,"cohoes$","") if investor_city_1=="cohoes"
replace $x=regexr($x,"san jose$","") if investor_city_1=="san jose"
replace $x=regexr($x,"long branch$","") if investor_city_1=="long branch"
replace $x=regexr($x,"dubuque$","") if investor_city_1=="dubuque"
replace $x=regexr($x,"marblehead$","") if investor_city_1=="marblehead"
replace $x=regexr($x,"mount carmel$","") if investor_city_1=="mount carmel"
replace $x=regexr($x,"piscataquis$","") if investor_city_1=="piscataquis"
replace $x=regexr($x,"dexter$","") if investor_city_1=="dexter"
replace $x=regexr($x,"westchester county$","") if investor_city_1=="westchester county"
replace $x=regexr($x,"westborough$","") if investor_city_1=="westborough"
replace $x=regexr($x,"mamaroneck$","") if investor_city_1=="mamaroneck"
replace $x=regexr($x,"west pittston$","") if investor_city_1=="west pittston"
replace $x=regexr($x,"saginaw$","") if investor_city_1=="saginaw"
replace $x=regexr($x,"cleveland$","") if investor_city_1=="cleveland"
replace $x=regexr($x,"west new brighton$","") if investor_city_1=="west new brighton"
replace $x=regexr($x,"palmyra$","") if investor_city_1=="palmyra"
replace $x=regexr($x,"amesbury$","") if investor_city_1=="amesbury"
replace $x=regexr($x,"centerville$","") if investor_city_1=="centerville"
replace $x=regexr($x,"mcsherrystown$","") if investor_city_1=="mcsherrystown"
replace $x=regexr($x,"wayne$","") if investor_city_1=="wayne"
replace $x=regexr($x,"latrobe$","") if investor_city_1=="latrobe"
replace $x=regexr($x,"san diego$","") if investor_city_1=="san diego"
replace $x=regexr($x,"cornwall$","") if investor_city_1=="cornwall"
replace $x=regexr($x,"san leandro$","") if investor_city_1=="san leandro"
replace $x=regexr($x,"bridgeton$","") if investor_city_1=="bridgeton"
replace $x=regexr($x,"penobscot$","") if investor_city_1=="penobscot"
replace $x=regexr($x,"watsonville$","") if investor_city_1=="watsonville"
replace $x=regexr($x,"pwad�iphio$","") if investor_city_1=="pwad�iphio"
replace $x=regexr($x,"holmesburg$","") if investor_city_1=="holmesburg"
replace $x=regexr($x,"weehawken$","") if investor_city_1=="weehawken"
replace $x=regexr($x,"boston$","") if investor_city_1=="boston"
replace $x=regexr($x,"jewett city$","") if investor_city_1=="jewett city"
replace $x=regexr($x,"riverside$","") if investor_city_1=="riverside"
replace $x=regexr($x,"leroy$","") if investor_city_1=="leroy"
replace $x=regexr($x,"walden$","") if investor_city_1=="walden"
replace $x=regexr($x,"visalia$","") if investor_city_1=="visalia"
replace $x=regexr($x,"new berlin$","") if investor_city_1=="new berlin"
replace $x=regexr($x,"marianna$","") if investor_city_1=="marianna"
replace $x=regexr($x,"hayward$","") if investor_city_1=="hayward"
replace $x=regexr($x,"lynchburg$","") if investor_city_1=="lynchburg"
replace $x=regexr($x,"chicopee falls$","") if investor_city_1=="chicopee falls"
replace $x=regexr($x,"taylor$","") if investor_city_1=="taylor"
replace $x=regexr($x,"livermore$","") if investor_city_1=="livermore"
replace $x=regexr($x,"asbury park$","") if investor_city_1=="asbury park"
replace $x=regexr($x,"fishkill$","") if investor_city_1=="fishkill"
replace $x=regexr($x,"des moines$","") if investor_city_1=="des moines"
replace $x=regexr($x,"hillsborough bridge$","") if investor_city_1=="hillsborough bridge"
replace $x=regexr($x,"milton$","") if investor_city_1=="milton"
replace $x=regexr($x,"st helena$","") if investor_city_1=="st helena"
replace $x=regexr($x,"gothenburg$","") if investor_city_1=="gothenburg"
replace $x=regexr($x,"colusa$","") if investor_city_1=="colusa"
replace $x=regexr($x,"greenwich$","") if investor_city_1=="greenwich"
replace $x=regexr($x,"hackensack$","") if investor_city_1=="hackensack"
replace $x=regexr($x,"south manchester$","") if investor_city_1=="south manchester"
replace $x=regexr($x,"stapleton$","") if investor_city_1=="stapleton"
replace $x=regexr($x,"crawfordsville$","") if investor_city_1=="crawfordsville"
replace $x=regexr($x,"warwick$","") if investor_city_1=="warwick"
replace $x=regexr($x,"canonsburg$","") if investor_city_1=="canonsburg"
replace $x=regexr($x,"oroville$","") if investor_city_1=="oroville"
replace $x=regexr($x,"new castle$","") if investor_city_1=="new castle"
replace $x=regexr($x,"kensington$","") if investor_city_1=="kensington"
replace $x=regexr($x,"ardmore$","") if investor_city_1=="ardmore"
replace $x=regexr($x,"sebastopol$","") if investor_city_1=="sebastopol"
replace $x=regexr($x,"raritan$","") if investor_city_1=="raritan"
replace $x=regexr($x,"mckeesport$","") if investor_city_1=="mckeesport"
replace $x=regexr($x,"waterford$","") if investor_city_1=="waterford"
replace $x=regexr($x,"mckees rocks$","") if investor_city_1=="mckees rocks"
replace $x=regexr($x,"attleborough$","") if investor_city_1=="attleborough"
replace $x=regexr($x,"merced$","") if investor_city_1=="merced"
replace $x=regexr($x,"clairton$","") if investor_city_1=="clairton"
replace $x=regexr($x,"uxbridge$","") if investor_city_1=="uxbridge"
replace $x=regexr($x,"rio vista$","") if investor_city_1=="rio vista"
replace $x=regexr($x,"cornwallonhudson$","") if investor_city_1=="cornwallonhudson"
replace $x=regexr($x,"kane$","") if investor_city_1=="kane"
replace $x=regexr($x,"middleton$","") if investor_city_1=="middleton"
replace $x=regexr($x,"san rafael$","") if investor_city_1=="san rafael"
replace $x=regexr($x,"wappinger falls$","") if investor_city_1=="wappinger falls"
replace $x=regexr($x,"grove city$","") if investor_city_1=="grove city"
replace $x=regexr($x,"charleston$","") if investor_city_1=="charleston"
replace $x=regexr($x,"allegheny city$","") if investor_city_1=="allegheny city"
replace $x=regexr($x,"east pittsburgh$","") if investor_city_1=="east pittsburgh"
replace $x=regexr($x,"goshen$","") if investor_city_1=="goshen"
replace $x=regexr($x,"ventura$","") if investor_city_1=="ventura"
replace $x=regexr($x,"vandergrift$","") if investor_city_1=="vandergrift"
replace $x=regexr($x,"whitefield$","") if investor_city_1=="whitefield"
replace $x=regexr($x,"germantown$","") if investor_city_1=="germantown"
replace $x=regexr($x,"vallejo$","") if investor_city_1=="vallejo"
replace $x=regexr($x,"ocean park$","") if investor_city_1=="ocean park"
replace $x=regexr($x,"antioch$","") if investor_city_1=="antioch"
replace $x=regexr($x,"munich$","") if investor_city_1=="munich"
replace $x=regexr($x,"avalon$","") if investor_city_1=="avalon"
replace $x=regexr($x,"dobbs ferry$","") if investor_city_1=="dobbs ferry"
replace $x=regexr($x,"south yarmouth$","") if investor_city_1=="south yarmouth"
replace $x=regexr($x,"jackson$","") if investor_city_1=="jackson"
replace $x=regexr($x,"uniontown$","") if investor_city_1=="uniontown"
replace $x=regexr($x,"hellam$","") if investor_city_1=="hellam"
replace $x=regexr($x,"tulare$","") if investor_city_1=="tulare"
replace $x=regexr($x,"dravosburg$","") if investor_city_1=="dravosburg"
replace $x=regexr($x,"monterey$","") if investor_city_1=="monterey"
replace $x=regexr($x,"kennett square$","") if investor_city_1=="kennett square"
replace $x=regexr($x,"flushing$","") if investor_city_1=="flushing"
replace $x=regexr($x,"new hartford$","") if investor_city_1=="new hartford"
replace $x=regexr($x,"santa barbara$","") if investor_city_1=="santa barbara"
replace $x=regexr($x,"mt pleasant$","") if investor_city_1=="mt pleasant"
replace $x=regexr($x,"east berlin$","") if investor_city_1=="east berlin"
replace $x=regexr($x,"lisbon$","") if investor_city_1=="lisbon"
replace $x=regexr($x,"lakeport$","") if investor_city_1=="lakeport"
replace $x=regexr($x,"san mateo$","") if investor_city_1=="san mateo"
replace $x=regexr($x,"sonoma$","") if investor_city_1=="sonoma"
replace $x=regexr($x,"oneida$","") if investor_city_1=="oneida"
replace $x=regexr($x,"cromwell$","") if investor_city_1=="cromwell"
replace $x=regexr($x,"oklahoma city$","") if investor_city_1=="oklahoma city"
replace $x=regexr($x,"hollister$","") if investor_city_1=="hollister"
replace $x=regexr($x,"elizabethville$","") if investor_city_1=="elizabethville"
replace $x=regexr($x,"atlantic$","") if investor_city_1=="atlantic"
replace $x=regexr($x,"amsterdam$","") if investor_city_1=="amsterdam"
replace $x=regexr($x,"atlanta$","") if investor_city_1=="atlanta"
replace $x=regexr($x,"berkeley$","") if investor_city_1=="berkeley"
replace $x=regexr($x,"homestead$","") if investor_city_1=="homestead"
replace $x=regexr($x,"branford$","") if investor_city_1=="branford"
replace $x=regexr($x,"belle vernon$","") if investor_city_1=="belle vernon"
replace $x=regexr($x,"santa clara$","") if investor_city_1=="santa clara"
replace $x=regexr($x,"danville$","") if investor_city_1=="danville"
replace $x=regexr($x,"dunmore$","") if investor_city_1=="dunmore"
replace $x=regexr($x,"monrovia$","") if investor_city_1=="monrovia"
replace $x=regexr($x,"carnegie$","") if investor_city_1=="carnegie"
replace $x=regexr($x,"old forge$","") if investor_city_1=="old forge"
replace $x=regexr($x,"greensville$","") if investor_city_1=="greensville"
replace $x=regexr($x,"tolland$","") if investor_city_1=="tolland"
replace $x=regexr($x,"fort jones$","") if investor_city_1=="fort jones"
replace $x=regexr($x,"valley view$","") if investor_city_1=="valley view"
replace $x=regexr($x,"reedley$","") if investor_city_1=="reedley"
replace $x=regexr($x,"alvarado$","") if investor_city_1=="alvarado"
replace $x=regexr($x,"ashaway$","") if investor_city_1=="ashaway"
replace $x=regexr($x,"gridley$","") if investor_city_1=="gridley"
replace $x=regexr($x,"minneapolis$","") if investor_city_1=="minneapolis"
replace $x=regexr($x,"rutherford$","") if investor_city_1=="rutherford"
replace $x=regexr($x,"tarrytown$","") if investor_city_1=="tarrytown"
replace $x=regexr($x,"tarentum$","") if investor_city_1=="tarentum"
replace $x=regexr($x,"lodi$","") if investor_city_1=="lodi"
replace $x=regexr($x,"derry$","") if investor_city_1=="derry"
replace $x=regexr($x,"quebec$","") if investor_city_1=="quebec"
replace $x=regexr($x,"monongahela city$","") if investor_city_1=="monongahela city"
replace $x=regexr($x,"sag harbor$","") if investor_city_1=="sag harbor"
replace $x=regexr($x,"boothbay$","") if investor_city_1=="boothbay"
replace $x=regexr($x,"stockholm$","") if investor_city_1=="stockholm"
replace $x=regexr($x,"stettin$","") if investor_city_1=="stettin"
replace $x=regexr($x,"steelton$","") if investor_city_1=="steelton"
replace $x=regexr($x,"brattleboro$","") if investor_city_1=="brattleboro"
replace $x=regexr($x,"bass river$","") if investor_city_1=="bass river"
replace $x=regexr($x,"muskogee$","") if investor_city_1=="muskogee"
replace $x=regexr($x,"north scranton$","") if investor_city_1=="north scranton"
replace $x=regexr($x,"alexandria$","") if investor_city_1=="alexandria"
replace $x=regexr($x,"gettysburg$","") if investor_city_1=="gettysburg"
replace $x=regexr($x,"fishkillonhudson$","") if investor_city_1=="fishkillonhudson"
replace $x=regexr($x,"brighton$","") if investor_city_1=="brighton"
replace $x=regexr($x,"knoxville$","") if investor_city_1=="knoxville"
replace $x=regexr($x,"brewster$","") if investor_city_1=="brewster"
replace $x=regexr($x,"smethport$","") if investor_city_1=="smethport"
replace $x=regexr($x,"san fernando$","") if investor_city_1=="san fernando"
replace $x=regexr($x,"st johnsbury$","") if investor_city_1=="st johnsbury"
replace $x=regexr($x,"albert lea$","") if investor_city_1=="albert lea"
replace $x=regexr($x,"hummelstown$","") if investor_city_1=="hummelstown"
replace $x=regexr($x,"denver$","") if investor_city_1=="denver"
replace $x=regexr($x,"topeka$","") if investor_city_1=="topeka"
replace $x=regexr($x,"princeton$","") if investor_city_1=="princeton"
replace $x=regexr($x,"columbia$","") if investor_city_1=="columbia"
replace $x=regexr($x,"red bank$","") if investor_city_1=="red bank"
replace $x=regexr($x,"west brighton$","") if investor_city_1=="west brighton"
replace $x=regexr($x,"mansfield$","") if investor_city_1=="mansfield"
replace $x=regexr($x,"crescent city$","") if investor_city_1=="crescent city"
replace $x=regexr($x,"spokane$","") if investor_city_1=="spokane"
replace $x=regexr($x,"berlin$","") if investor_city_1=="berlin"
replace $x=regexr($x,"petaluma$","") if investor_city_1=="petaluma"
replace $x=regexr($x,"eden$","") if investor_city_1=="eden"
replace $x=regexr($x,"st john$","") if investor_city_1=="st john"
replace $x=regexr($x,"south pasadena$","") if investor_city_1=="south pasadena"
replace $x=regexr($x,"sandy spring$","") if investor_city_1=="sandy spring"
replace $x=regexr($x,"melrose$","") if investor_city_1=="melrose"
replace $x=regexr($x,"riverhead$","") if investor_city_1=="riverhead"
replace $x=regexr($x,"scottdale$","") if investor_city_1=="scottdale"
replace $x=regexr($x,"long island city$","") if investor_city_1=="long island city"
replace $x=regexr($x,"pine bluff$","") if investor_city_1=="pine bluff"
replace $x=regexr($x,"fox chase$","") if investor_city_1=="fox chase"
replace $x=regexr($x,"seymour$","") if investor_city_1=="seymour"
replace $x=regexr($x,"sewickley$","") if investor_city_1=="sewickley"
replace $x=regexr($x,"ocean city$","") if investor_city_1=="ocean city"
replace $x=regexr($x,"phenix$","") if investor_city_1=="phenix"
replace $x=regexr($x,"o$","") if investor_city_1=="o"
replace $x=regexr($x,"galveston$","") if investor_city_1=="galveston"
replace $x=regexr($x,"rutland$","") if investor_city_1=="rutland"
replace $x=regexr($x,"santa rosa$","") if investor_city_1=="santa rosa"
replace $x=regexr($x,"frederick$","") if investor_city_1=="frederick"
replace $x=regexr($x,"santa maria$","") if investor_city_1=="santa maria"
replace $x=regexr($x,"chestertown$","") if investor_city_1=="chestertown"
replace $x=regexr($x,"bellefonte$","") if investor_city_1=="bellefonte"
replace $x=regexr($x,"kansas city$","") if investor_city_1=="kansas city"
replace $x=regexr($x,"placerville$","") if investor_city_1=="placerville"
replace $x=regexr($x,"san dimas$","") if investor_city_1=="san dimas"
replace $x=regexr($x,"fort worth$","") if investor_city_1=="fort worth"
replace $x=regexr($x,"schuylkill haven$","") if investor_city_1=="schuylkill haven"
replace $x=regexr($x,"mercer$","") if investor_city_1=="mercer"
replace $x=regexr($x,"bishop$","") if investor_city_1=="bishop"
replace $x=regexr($x,"millvale$","") if investor_city_1=="millvale"
replace $x=regexr($x,"stuyvesant$","") if investor_city_1=="stuyvesant"
replace $x=regexr($x,"new canaan$","") if investor_city_1=="new canaan"
replace $x=regexr($x,"lemoyne$","") if investor_city_1=="lemoyne"
replace $x=regexr($x,"college point$","") if investor_city_1=="college point"
replace $x=regexr($x,"odessa$","") if investor_city_1=="odessa"
replace $x=regexr($x,"rockford$","") if investor_city_1=="rockford"
replace $x=regexr($x,"freeburg$","") if investor_city_1=="freeburg"
replace $x=regexr($x,"clarksville$","") if investor_city_1=="clarksville"
replace $x=regexr($x,"sanger$","") if investor_city_1=="sanger"
replace $x=regexr($x,"santa ana$","") if investor_city_1=="santa ana"
replace $x=regexr($x,"santa paula$","") if investor_city_1=="santa paula"
replace $x=regexr($x,"wales$","") if investor_city_1=="wales"
replace $x=regexr($x,"pirrston$","") if investor_city_1=="pirrston"
replace $x=regexr($x,"toledo$","") if investor_city_1=="toledo"
replace $x=regexr($x,"half moon bay$","") if investor_city_1=="half moon bay"
replace $x=regexr($x,"turtle creek$","") if investor_city_1=="turtle creek"
replace $x=regexr($x,"redwood city$","") if investor_city_1=="redwood city"
replace $x=regexr($x,"redlands$","") if investor_city_1=="redlands"
replace $x=regexr($x,"dallas$","") if investor_city_1=="dallas"
replace $x=regexr($x,"lewistown$","") if investor_city_1=="lewistown"
replace $x=regexr($x,"peoria$","") if investor_city_1=="peoria"
replace $x=regexr($x,"glen rock$","") if investor_city_1=="glen rock"
replace $x=regexr($x,"sausalito$","") if investor_city_1=="sausalito"
replace $x=regexr($x,"berkshire$","") if investor_city_1=="berkshire"
replace $x=regexr($x,"new bern$","") if investor_city_1=="new bern"
replace $x=regexr($x,"lansford$","") if investor_city_1=="lansford"
replace $x=regexr($x,"ione$","") if investor_city_1=="ione"
replace $x=regexr($x,"bakersville$","") if investor_city_1=="bakersville"
replace $x=regexr($x,"ellenville$","") if investor_city_1=="ellenville"
replace $x=regexr($x,"loyalton$","") if investor_city_1=="loyalton"
replace $x=regexr($x,"hollis$","") if investor_city_1=="hollis"
replace $x=regexr($x,"maynard$","") if investor_city_1=="maynard"
replace $x=regexr($x,"oceanside$","") if investor_city_1=="oceanside"
replace $x=regexr($x,"millville$","") if investor_city_1=="millville"
replace $x=regexr($x,"columbus$","") if investor_city_1=="columbus"
replace $x=regexr($x,"jeannette$","") if investor_city_1=="jeannette"
replace $x=regexr($x,"monessen$","") if investor_city_1=="monessen"
replace $x=regexr($x,"pomona$","") if investor_city_1=="pomona"
replace $x=regexr($x,"pleasanton$","") if investor_city_1=="pleasanton"
replace $x=regexr($x,"cloverdale$","") if investor_city_1=="cloverdale"
replace $x=regexr($x,"selma$","") if investor_city_1=="selma"
replace $x=regexr($x,"pittsburgh$","") if investor_city_1=="pittsburgh"
replace $x=regexr($x,"cologne$","") if investor_city_1=="cologne"
replace $x=regexr($x,"donora$","") if investor_city_1=="donora"
replace $x=regexr($x,"stevens point$","") if investor_city_1=="stevens point"
replace $x=regexr($x,"holtville$","") if investor_city_1=="holtville"
replace $x=regexr($x,"gilroy$","") if investor_city_1=="gilroy"
replace $x=regexr($x,"see industrial and miscellaneous section$","") if investor_city_1=="see industrial and miscellaneous section"
replace $x=regexr($x,"zurich$","") if investor_city_1=="zurich"
replace $x=regexr($x,"paso robles$","") if investor_city_1=="paso robles"
replace $x=regexr($x,"marion$","") if investor_city_1=="marion"
replace $x=regexr($x,"basle$","") if investor_city_1=="basle"
replace $x=regexr($x,"pacific grove$","") if investor_city_1=="pacific grove"
replace $x=regexr($x,"barton landing$","") if investor_city_1=="barton landing"
replace $x=regexr($x,"glassport$","") if investor_city_1=="glassport"
replace $x=regexr($x,"aixlachapelle$","") if investor_city_1=="aixlachapelle"
replace $x=regexr($x,"arroyo grande$","") if investor_city_1=="arroyo grande"
replace $x=regexr($x,"palo alto$","") if investor_city_1=="palo alto"
replace $x=regexr($x,"fort bragg$","") if investor_city_1=="fort bragg"
replace $x=regexr($x,"newman$","") if investor_city_1=="newman"
replace $x=regexr($x,"campbell$","") if investor_city_1=="campbell"
replace $x=regexr($x,"hawley$","") if investor_city_1=="hawley"
replace $x=regexr($x,"southold$","") if investor_city_1=="southold"
replace $x=regexr($x,"ontario$","") if investor_city_1=="ontario"
replace $x=regexr($x,"valley ford$","") if investor_city_1=="valley ford"
replace $x=regexr($x,"davenport$","") if investor_city_1=="davenport"
replace $x=regexr($x,"colusa county$","") if investor_city_1=="colusa county"
replace $x=regexr($x,"redondo beach$","") if investor_city_1=="redondo beach"
replace $x=regexr($x,"ellwood$","") if investor_city_1=="ellwood"
replace $x=regexr($x,"ottawa$","") if investor_city_1=="ottawa"
replace $x=regexr($x,"turlock$","") if investor_city_1=="turlock"
replace $x=regexr($x,"point arena$","") if investor_city_1=="point arena"
replace $x=regexr($x,"susanville$","") if investor_city_1=="susanville"
replace $x=regexr($x,"conshohocken$","") if investor_city_1=="conshohocken"
replace $x=regexr($x,"anaheim$","") if investor_city_1=="anaheim"
replace $x=regexr($x,"braintree$","") if investor_city_1=="braintree"
replace $x=regexr($x,"castle shannon$","") if investor_city_1=="castle shannon"
replace $x=regexr($x,"onondaga & syracuse$","") if investor_city_1=="onondaga & syracuse"
replace $x=regexr($x,"blackstone$","") if investor_city_1=="blackstone"
replace $x=regexr($x,"onondaga$","") if investor_city_1=="onondaga"
replace $x=regexr($x,"bel air$","") if investor_city_1=="bel air"
replace $x=regexr($x,"st gall$","") if investor_city_1=="st gall"
replace $x=regexr($x,"proctor$","") if investor_city_1=="proctor"
replace $x=regexr($x,"terryville$","") if investor_city_1=="terryville"
replace $x=regexr($x,"coraopolis$","") if investor_city_1=="coraopolis"
replace $x=regexr($x,"yuba city$","") if investor_city_1=="yuba city"
replace $x=regexr($x,"north attleborough$","") if investor_city_1=="north attleborough"
replace $x=regexr($x,"montpelier$","") if investor_city_1=="montpelier"
replace $x=regexr($x,"venice$","") if investor_city_1=="venice"
replace $x=regexr($x,"macon$","") if investor_city_1=="macon"
replace $x=regexr($x,"town of union$","") if investor_city_1=="town of union"
replace $x=regexr($x,"ellwood city$","") if investor_city_1=="ellwood city"
replace $x=regexr($x,"sutter creek$","") if investor_city_1=="sutter creek"
replace $x=regexr($x,"stonington$","") if investor_city_1=="stonington"
replace $x=regexr($x,"huntington park$","") if investor_city_1=="huntington park"
replace $x=regexr($x,"rimouski$","") if investor_city_1=="rimouski"
replace $x=regexr($x,"parsons$","") if investor_city_1=="parsons"
replace $x=regexr($x,"bridgeville$","") if investor_city_1=="bridgeville"
replace $x=regexr($x,"morgan hill$","") if investor_city_1=="morgan hill"
replace $x=regexr($x,"sherman$","") if investor_city_1=="sherman"
replace $x=regexr($x,"outerville$","") if investor_city_1=="outerville"
replace $x=regexr($x,"darien$","") if investor_city_1=="darien"
replace $x=regexr($x,"san berna$","") if investor_city_1=="san berna"
replace $x=regexr($x,"brackenridge$","") if investor_city_1=="brackenridge"
replace $x=regexr($x,"guerneville$","") if investor_city_1=="guerneville"
replace $x=regexr($x,"white river junction$","") if investor_city_1=="white river junction"
replace $x=regexr($x,"corona$","") if investor_city_1=="corona"
replace $x=regexr($x,"cal$","") if investor_city_1=="cal"
replace $x=regexr($x,"barton$","") if investor_city_1=="barton"
replace $x=regexr($x,"mannheim$","") if investor_city_1=="mannheim"
replace $x=regexr($x,"jacksonville$","") if investor_city_1=="jacksonville"
replace $x=regexr($x,"black diamond$","") if investor_city_1=="black diamond"
replace $x=regexr($x,"bradford$","") if investor_city_1=="bradford"
replace $x=regexr($x,"brawley$","") if investor_city_1=="brawley"
replace $x=regexr($x,"portland me$","") if investor_city_1=="portland me"
replace $x=regexr($x,"sioux city$","") if investor_city_1=="sioux city"
replace $x=regexr($x,"biggs$","") if investor_city_1=="biggs"
replace $x=regexr($x,"mahoning$","") if investor_city_1=="mahoning"
replace $x=regexr($x,"brookville$","") if investor_city_1=="brookville"
replace $x=regexr($x,"milburn$","") if investor_city_1=="milburn"
replace $x=regexr($x,"lansing$","") if investor_city_1=="lansing"
replace $x=regexr($x,"burlington flats$","") if investor_city_1=="burlington flats"
replace $x=regexr($x,"calexico$","") if investor_city_1=="calexico"
replace $x=regexr($x,"ferndale$","") if investor_city_1=="ferndale"
replace $x=regexr($x,"ebensburg$","") if investor_city_1=="ebensburg"
replace $x=regexr($x,"meridian$","") if investor_city_1=="meridian"
replace $x=regexr($x,"wyalusing$","") if investor_city_1=="wyalusing"
replace $x=regexr($x,"folsom$","") if investor_city_1=="folsom"
replace $x=regexr($x,"charlestown district$","") if investor_city_1=="charlestown district"
replace $x=regexr($x,"martinez$","") if investor_city_1=="martinez"
replace $x=regexr($x,"warrenv mass$","") if investor_city_1=="warrenv mass"
replace $x=regexr($x,"mcconnellsburg$","") if investor_city_1=="mcconnellsburg"
replace $x=regexr($x,"south boston$","") if investor_city_1=="south boston"
replace $x=regexr($x,"dartmouth$","") if investor_city_1=="dartmouth"
replace $x=regexr($x,"los banos$","") if investor_city_1=="los banos"
replace $x=regexr($x,"shanghai$","") if investor_city_1=="shanghai"
replace $x=regexr($x,"sandusky$","") if investor_city_1=="sandusky"
replace $x=regexr($x,"seaport$","") if investor_city_1=="seaport"
replace $x=regexr($x,"higganum$","") if investor_city_1=="higganum"
replace $x=regexr($x,"montgomery county$","") if investor_city_1=="montgomery county"
replace $x=regexr($x,"dutch flat$","") if investor_city_1=="dutch flat"
replace $x=regexr($x,"chatfield$","") if investor_city_1=="chatfield"
replace $x=regexr($x,"elsinore$","") if investor_city_1=="elsinore"
replace $x=regexr($x,"nashville$","") if investor_city_1=="nashville"
replace $x=regexr($x,"london and edinburgh$","") if investor_city_1=="london and edinburgh"
replace $x=regexr($x,"escondido$","") if investor_city_1=="escondido"
replace $x=regexr($x,"gonzales$","") if investor_city_1=="gonzales"
replace $x=regexr($x,"fayette city$","") if investor_city_1=="fayette city"
replace $x=regexr($x,"birstol$","") if investor_city_1=="birstol"
replace $x=regexr($x,"lyndonville$","") if investor_city_1=="lyndonville"
replace $x=regexr($x,"ambridge$","") if investor_city_1=="ambridge"
replace $x=regexr($x,"green lyon$","") if investor_city_1=="green lyon"
replace $x=regexr($x,"freehold$","") if investor_city_1=="freehold"
replace $x=regexr($x,"edgewater$","") if investor_city_1=="edgewater"
replace $x=regexr($x,"honolulu$","") if investor_city_1=="honolulu"
replace $x=regexr($x,"oakdale$","") if investor_city_1=="oakdale"
replace $x=regexr($x,"walla walla$","") if investor_city_1=="walla walla"
replace $x=regexr($x,"valley city$","") if investor_city_1=="valley city"
replace $x=regexr($x,"marshfield$","") if investor_city_1=="marshfield"
replace $x=regexr($x,"woodstock$","") if investor_city_1=="woodstock"
replace $x=regexr($x,"jonestown$","") if investor_city_1=="jonestown"
replace $x=regexr($x,"paris$","") if investor_city_1=="paris"
replace $x=regexr($x,"south bend$","") if investor_city_1=="south bend"
replace $x=regexr($x,"new enterprise$","") if investor_city_1=="new enterprise"
replace $x=regexr($x,"freestone$","") if investor_city_1=="freestone"
replace $x=regexr($x,"national city$","") if investor_city_1=="national city"
replace $x=regexr($x,"west philadelphia$","") if investor_city_1=="west philadelphia"
replace $x=regexr($x,"mahoning city$","") if investor_city_1=="mahoning city"
replace $x=regexr($x,"misc$","") if investor_city_1=="misc"
replace $x=regexr($x,"conn$","") if investor_city_1=="conn"
replace $x=regexr($x,"vancouver$","") if investor_city_1=="vancouver"
replace $x=regexr($x,"albion$","") if investor_city_1=="albion"
replace $x=regexr($x,"dursburg$","") if investor_city_1=="dursburg"
replace $x=regexr($x,"port huron$","") if investor_city_1=="port huron"
replace $x=regexr($x,"highland$","") if investor_city_1=="highland"
replace $x=regexr($x,"inglewood$","") if investor_city_1=="inglewood"
replace $x=regexr($x,"frankfort$","") if investor_city_1=="frankfort"
replace $x=regexr($x,"mass$","") if investor_city_1=="mass"
replace $x=regexr($x,"oklahoma$","") if investor_city_1=="oklahoma"
replace $x=regexr($x,"stafford$","") if investor_city_1=="stafford"
replace $x=regexr($x,"west rutland$","") if investor_city_1=="west rutland"
replace $x=regexr($x,"the hague$","") if investor_city_1=="the hague"
replace $x=regexr($x,"london & aberdeen$","") if investor_city_1=="london & aberdeen"
replace $x=regexr($x,"liverpool & london$","") if investor_city_1=="liverpool & london"
replace $x=regexr($x,"madrid$","") if investor_city_1=="madrid"
replace $x=regexr($x,"frankfort on main$","") if investor_city_1=="frankfort on main"
replace $x=regexr($x,"frankfortontown$","") if investor_city_1=="frankfortontown"
replace $x=regexr($x,"moscow$","") if investor_city_1=="moscow"
replace $x=regexr($x,"london & edinburgh$","") if investor_city_1=="london & edinburgh"
replace $x=regexr($x,"salamandra & st petersburg$","") if investor_city_1=="salamandra & st petersburg"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="new york city"

*Replace state
replace $x=regexr($x,"new jersey$","") if investor_state_1=="new jersey"
replace $x=regexr($x,"wisconsin$","") if investor_state_1=="wisconsin"
replace $x=regexr($x,"pennsylvania$","") if investor_state_1=="pennsylvania"
replace $x=regexr($x,"massachusetts$","") if investor_state_1=="massachusetts"
replace $x=regexr($x,"connecticut$","") if investor_state_1=="connecticut"
replace $x=regexr($x,"new york$","") if investor_state_1=="new york"
replace $x=regexr($x,"rhode island$","") if investor_state_1=="rhode island"
replace $x=regexr($x,"new hampshire$","") if investor_state_1=="new hampshire"
replace $x=regexr($x,"maine$","") if investor_state_1=="maine"
replace $x=regexr($x,"illinois$","") if investor_state_1=="illinois"
replace $x=regexr($x,"california$","") if investor_state_1=="california"
replace $x=regexr($x,"maryland$","") if investor_state_1=="maryland"
replace $x=regexr($x,"canada$","") if investor_state_1=="canada"
replace $x=regexr($x,"england$","") if investor_state_1=="england"
replace $x=regexr($x,"south dakota$","") if investor_state_1=="south dakota"
replace $x=regexr($x,"ohio$","") if investor_state_1=="ohio"
replace $x=regexr($x,"scotland$","") if investor_state_1=="scotland"
replace $x=regexr($x,"minnesota$","") if investor_state_1=="minnesota"
replace $x=regexr($x,"delaware$","") if investor_state_1=="delaware"
replace $x=regexr($x,"virginia$","") if investor_state_1=="virginia"
replace $x=regexr($x,"west virginia$","") if investor_state_1=="west virginia"
replace $x=regexr($x,"missouri$","") if investor_state_1=="missouri"
replace $x=regexr($x,"michigan$","") if investor_state_1=="michigan"
replace $x=regexr($x,"vermont$","") if investor_state_1=="vermont"
replace $x=regexr($x,"arkansas$","") if investor_state_1=="arkansas"
replace $x=regexr($x,"north carolina$","") if investor_state_1=="north carolina"
replace $x=regexr($x,"kentucky$","") if investor_state_1=="kentucky"
replace $x=regexr($x,"louisiana$","") if investor_state_1=="louisiana"
replace $x=regexr($x,"georgia$","") if investor_state_1=="georgia"
replace $x=regexr($x,"russia$","") if investor_state_1=="russia"
replace $x=regexr($x,"dist. of columbia$","") if investor_state_1=="dist. of columbia"
replace $x=regexr($x,"alabama$","") if investor_state_1=="alabama"
replace $x=regexr($x,"indiana$","") if investor_state_1=="indiana"
replace $x=regexr($x,"tennessee$","") if investor_state_1=="tennessee"
replace $x=regexr($x,"nebraska$","") if investor_state_1=="nebraska"
replace $x=regexr($x,"washington$","") if investor_state_1=="washington"
replace $x=regexr($x,"texas$","") if investor_state_1=="texas"
replace $x=regexr($x,"utah$","") if investor_state_1=="utah"
replace $x=regexr($x,"iowa$","") if investor_state_1=="iowa"

* Multiple states
replace $x=regexr($x,"canada$","") if investor_state_temp=="canada/connecticut"
replace $x=regexr($x,"connecticut$","") if investor_state_temp=="canada/connecticut"
replace $x=regexr($x,"canada$","") if investor_state_temp=="canada/illinois"
replace $x=regexr($x,"illinois$","") if investor_state_temp=="canada/illinois"
replace $x=regexr($x,"canada$","") if investor_state_temp=="canada/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="canada/new york"
replace $x=regexr($x,"china$","") if investor_state_temp=="china/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="china/new york"
replace $x=regexr($x,"england & scotland$","") if investor_state_temp=="england & scotland/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="england & scotland/new york"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/canada"
replace $x=regexr($x,"canada$","") if investor_state_temp=="england/canada"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/connecticut"
replace $x=regexr($x,"connecticut$","") if investor_state_temp=="england/connecticut"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/illinois"
replace $x=regexr($x,"illinois$","") if investor_state_temp=="england/illinois"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/massachusetts"
replace $x=regexr($x,"massachusetts$","") if investor_state_temp=="england/massachusetts"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/missouri"
replace $x=regexr($x,"missouri$","") if investor_state_temp=="england/missouri"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/new jersey"
replace $x=regexr($x,"new jersey$","") if investor_state_temp=="england/new jersey"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="england/new york"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/pennsylvania"
replace $x=regexr($x,"pennsylvania$","") if investor_state_temp=="england/pennsylvania"
replace $x=regexr($x,"england$","") if investor_state_temp=="england/virginia"
replace $x=regexr($x,"virginia$","") if investor_state_temp=="england/virginia"
replace $x=regexr($x,"france$","") if investor_state_temp=="france/connecticut"
replace $x=regexr($x,"connecticut$","") if investor_state_temp=="france/connecticut"
replace $x=regexr($x,"france$","") if investor_state_temp=="france/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="france/new york"
replace $x=regexr($x,"france$","") if investor_state_temp=="france/rhode island"
replace $x=regexr($x,"rhode island$","") if investor_state_temp=="france/rhode island"
replace $x=regexr($x,"germany$","") if investor_state_temp=="germany/connecticut"
replace $x=regexr($x,"connecticut$","") if investor_state_temp=="germany/connecticut"
replace $x=regexr($x,"germany$","") if investor_state_temp=="germany/illinois"
replace $x=regexr($x,"illinois$","") if investor_state_temp=="germany/illinois"
replace $x=regexr($x,"germany$","") if investor_state_temp=="germany/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="germany/new york"
replace $x=regexr($x,"great britain$","") if investor_state_temp=="great britain/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="great britain/new york"
replace $x=regexr($x,"holland$","") if investor_state_temp=="holland/illinois"
replace $x=regexr($x,"illinois$","") if investor_state_temp=="holland/illinois"
replace $x=regexr($x,"holland$","") if investor_state_temp=="holland/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="holland/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="new york/germany"
replace $x=regexr($x,"germany$","") if investor_state_temp=="new york/germany"
replace $x=regexr($x,"new york$","") if investor_state_temp=="new york/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="new york/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="new york/scotland"
replace $x=regexr($x,"scotland$","") if investor_state_temp=="new york/scotland"
replace $x=regexr($x,"russia$","") if investor_state_temp=="russia/connecticut"
replace $x=regexr($x,"connecticut$","") if investor_state_temp=="russia/connecticut"
replace $x=regexr($x,"russia$","") if investor_state_temp=="russia/kentucky"
replace $x=regexr($x,"kentucky$","") if investor_state_temp=="russia/kentucky"
replace $x=regexr($x,"russia$","") if investor_state_temp=="russia/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="russia/new york"
replace $x=regexr($x,"scotland$","") if investor_state_temp=="scotland/canada"
replace $x=regexr($x,"canada$","") if investor_state_temp=="scotland/canada"
replace $x=regexr($x,"scotland$","") if investor_state_temp=="scotland/colorado"
replace $x=regexr($x,"colorado$","") if investor_state_temp=="scotland/colorado"
replace $x=regexr($x,"scotland$","") if investor_state_temp=="scotland/connecticut"
replace $x=regexr($x,"connecticut$","") if investor_state_temp=="scotland/connecticut"
replace $x=regexr($x,"scotland$","") if investor_state_temp=="scotland/missouri"
replace $x=regexr($x,"missouri$","") if investor_state_temp=="scotland/missouri"
replace $x=regexr($x,"scotland$","") if investor_state_temp=="scotland/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="scotland/new york"
replace $x=regexr($x,"scotland$","") if investor_state_temp=="scotland/pennsylvania"
replace $x=regexr($x,"pennsylvania$","") if investor_state_temp=="scotland/pennsylvania"
replace $x=regexr($x,"spain$","") if investor_state_temp=="spain/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="spain/new york"
replace $x=regexr($x,"sweden$","") if investor_state_temp=="sweden/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="sweden/new york"
replace $x=regexr($x,"switzerland$","") if investor_state_temp=="switzerland/connecticut"
replace $x=regexr($x,"connecticut$","") if investor_state_temp=="switzerland/connecticut"
replace $x=regexr($x,"switzerland$","") if investor_state_temp=="switzerland/new york"
replace $x=regexr($x,"new york$","") if investor_state_temp=="switzerland/new york"


*Multiple cities
replace $x=subinstr($x,"/"," ",.) if strpos(investor_city_temp,"/")
replace $x=subinstr($x,"/"," ",.) if strpos(investor_state_temp,"/")
replace $x=regexr($x,"aixlachapelle$","") if investor_city_temp=="aixlachapelle/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="aixlachapelle/new york"
replace $x=regexr($x,"albany$","") if investor_city_temp=="albany/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="albany/new york"
replace $x=regexr($x,"amsterdam$","") if investor_city_temp=="amsterdam/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="amsterdam/new york"
replace $x=regexr($x,"amsterdam$","") if investor_city_temp=="amsterdam/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="amsterdam/new york city"
replace $x=regexr($x,"basle$","") if investor_city_temp=="basle/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="basle/hartford"
replace $x=regexr($x,"basle$","") if investor_city_temp=="basle/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="basle/new york"
replace $x=regexr($x,"berlin$","") if investor_city_temp=="berlin/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="berlin/new york"
replace $x=regexr($x,"cologne$","") if investor_city_temp=="cologne/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="cologne/new york"
replace $x=regexr($x,"edinburgh$","") if investor_city_temp=="edinburgh/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="edinburgh/hartford"
replace $x=regexr($x,"edinburgh$","") if investor_city_temp=="edinburgh/london"
replace $x=regexr($x,"london$","") if investor_city_temp=="edinburgh/london"
replace $x=regexr($x,"edinburgh$","") if investor_city_temp=="edinburgh/montreal"
replace $x=regexr($x,"montreal$","") if investor_city_temp=="edinburgh/montreal"
replace $x=regexr($x,"edinburgh$","") if investor_city_temp=="edinburgh/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="edinburgh/new york"
replace $x=regexr($x,"edinburgh$","") if investor_city_temp=="edinburgh/toronto"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="edinburgh/toronto"
replace $x=regexr($x,"frankfort on main$","") if investor_city_temp=="frankfort on main/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="frankfort on main/new york"
replace $x=regexr($x,"frankfort$","") if investor_city_temp=="frankfort/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="frankfort/new york"
replace $x=regexr($x,"frankfortontown$","") if investor_city_temp=="frankfortontown/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="frankfortontown/new york"
replace $x=regexr($x,"gothenburg$","") if investor_city_temp=="gothenburg/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="gothenburg/new york"
replace $x=regexr($x,"hamburg$","") if investor_city_temp=="hamburg/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="hamburg/new york"
replace $x=regexr($x,"hamburg$","") if investor_city_temp=="hamburg/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="hamburg/new york city"
replace $x=regexr($x,"liverpool & london$","") if investor_city_temp=="liverpool & london/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="liverpool & london/new york"
replace $x=regexr($x,"liverpool$","") if investor_city_temp=="liverpool/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="liverpool/hartford"
replace $x=regexr($x,"liverpool$","") if investor_city_temp=="liverpool/montreal"
replace $x=regexr($x,"montreal$","") if investor_city_temp=="liverpool/montreal"
replace $x=regexr($x,"liverpool$","") if investor_city_temp=="liverpool/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="liverpool/new york"
replace $x=regexr($x,"liverpool$","") if investor_city_temp=="liverpool/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="liverpool/new york city"
replace $x=regexr($x,"liverpool$","") if investor_city_temp=="liverpool/norfolk"
replace $x=regexr($x,"norfolk$","") if investor_city_temp=="liverpool/norfolk"
replace $x=regexr($x,"liverpool$","") if investor_city_temp=="liverpool/toronto"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="liverpool/toronto"
replace $x=regexr($x,"london & aberdeen$","") if investor_city_temp=="london & aberdeen/montreal"
replace $x=regexr($x,"montreal$","") if investor_city_temp=="london & aberdeen/montreal"
replace $x=regexr($x,"london & edinburgh$","") if investor_city_temp=="london & edinburgh/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="london & edinburgh/new york"
replace $x=regexr($x,"london and edinburgh$","") if investor_city_temp=="london and edinburgh/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="london and edinburgh/new york"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/boston"
replace $x=regexr($x,"boston$","") if investor_city_temp=="london/boston"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/chicago"
replace $x=regexr($x,"chicago$","") if investor_city_temp=="london/chicago"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/edinburgh"
replace $x=regexr($x,"edinburgh$","") if investor_city_temp=="london/edinburgh"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="london/hartford"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/montreal"
replace $x=regexr($x,"montreal$","") if investor_city_temp=="london/montreal"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="london/new york"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="london/new york city"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/ontario"
replace $x=regexr($x,"ontario$","") if investor_city_temp=="london/ontario"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/philadelphia"
replace $x=regexr($x,"philadelphia$","") if investor_city_temp=="london/philadelphia"
replace $x=regexr($x,"london$","") if investor_city_temp=="london/toronto"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="london/toronto"
replace $x=regexr($x,"madrid$","") if investor_city_temp=="madrid/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="madrid/new york"
replace $x=regexr($x,"mannheim$","") if investor_city_temp=="mannheim/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="mannheim/new york"
replace $x=regexr($x,"moscow$","") if investor_city_temp=="moscow/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="moscow/new york"
replace $x=regexr($x,"munich$","") if investor_city_temp=="munich/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="munich/hartford"
replace $x=regexr($x,"munich$","") if investor_city_temp=="munich/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="munich/new york"
replace $x=regexr($x,"munich$","") if investor_city_temp=="munich/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="munich/new york city"
replace $x=regexr($x,"new london$","") if investor_city_temp=="new london/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="new london/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="new york/west new brighton"
replace $x=regexr($x,"west new brighton$","") if investor_city_temp=="new york/west new brighton"
replace $x=regexr($x,"norwich$","") if investor_city_temp=="norwich/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="norwich/new york"
replace $x=regexr($x,"norwich$","") if investor_city_temp=="norwich/toronto"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="norwich/toronto"
replace $x=regexr($x,"onondaga$","") if investor_city_temp=="onondaga/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="onondaga/new york"
replace $x=regexr($x,"onondaga$","") if investor_city_temp=="onondaga/syracuse"
replace $x=regexr($x,"syracuse$","") if investor_city_temp=="onondaga/syracuse"
replace $x=regexr($x,"paris$","") if investor_city_temp=="paris/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="paris/hartford"
replace $x=regexr($x,"paris$","") if investor_city_temp=="paris/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="paris/new york"
replace $x=regexr($x,"paris$","") if investor_city_temp=="paris/providence"
replace $x=regexr($x,"providence$","") if investor_city_temp=="paris/providence"
replace $x=regexr($x,"perth$","") if investor_city_temp=="perth/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="perth/new york"
replace $x=regexr($x,"perth$","") if investor_city_temp=="perth/philadelphia"
replace $x=regexr($x,"philadelphia$","") if investor_city_temp=="perth/philadelphia"
replace $x=regexr($x,"perth$","") if investor_city_temp=="perth/toronto"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="perth/toronto"
replace $x=regexr($x,"petersburg$","") if investor_city_temp=="petersburg/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="petersburg/new york"
replace $x=regexr($x,"philadelphia$","") if investor_city_temp=="philadelphia/philadelphia"
replace $x=regexr($x,"philadelphia$","") if investor_city_temp=="philadelphia/philadelphia"
replace $x=regexr($x,"salamandra & st petersburg$","") if investor_city_temp=="salamandra & st petersburg/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="salamandra & st petersburg/new york"
replace $x=regexr($x,"shanghai$","") if investor_city_temp=="shanghai/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="shanghai/new york"
replace $x=regexr($x,"shanghai$","") if investor_city_temp=="shanghai/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="shanghai/new york city"
replace $x=regexr($x,"st petersburg$","") if investor_city_temp=="st petersburg/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="st petersburg/hartford"
replace $x=regexr($x,"st petersburg$","") if investor_city_temp=="st petersburg/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="st petersburg/new york"
replace $x=regexr($x,"st petersburg$","") if investor_city_temp=="st petersburg/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="st petersburg/new york city"
replace $x=regexr($x,"stettin$","") if investor_city_temp=="stettin/chicago"
replace $x=regexr($x,"chicago$","") if investor_city_temp=="stettin/chicago"
replace $x=regexr($x,"stettin$","") if investor_city_temp=="stettin/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="stettin/new york"
replace $x=regexr($x,"stockholm$","") if investor_city_temp=="stockholm/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="stockholm/new york"
replace $x=regexr($x,"stockholm$","") if investor_city_temp=="stockholm/new york city"
replace $x=regexr($x,"new york city$","") if investor_city_temp=="stockholm/new york city"
replace $x=regexr($x,"the hague$","") if investor_city_temp=="the hague/chicago"
replace $x=regexr($x,"chicago$","") if investor_city_temp=="the hague/chicago"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="toronto/chicago"
replace $x=regexr($x,"chicago$","") if investor_city_temp=="toronto/chicago"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="toronto/hartford"
replace $x=regexr($x,"hartford$","") if investor_city_temp=="toronto/hartford"
replace $x=regexr($x,"toronto$","") if investor_city_temp=="toronto/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="toronto/new york"
replace $x=regexr($x,"waterloo$","") if investor_city_temp=="waterloo/ontario"
replace $x=regexr($x,"ontario$","") if investor_city_temp=="waterloo/ontario"
replace $x=regexr($x,"york$","") if investor_city_temp=="york/montreal"
replace $x=regexr($x,"montreal$","") if investor_city_temp=="york/montreal"
replace $x=regexr($x,"york$","") if investor_city_temp=="york/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="york/new york"
replace $x=regexr($x,"zurich$","") if investor_city_temp=="zurich/new york"
replace $x=regexr($x,"new york$","") if investor_city_temp=="zurich/new york"
