replace investor_city_hold=proper(investor_city_hold)
replace invname_hold_temp=subinword(invname_hold_temp,"ltd","limited",.)
replace invname_hold_temp=subinword(invname_hold_temp,"liab","liability",.)
replace invname_hold_temp=subinword(invname_hold_temp,"ins","insurance",.)
replace invname_hold_temp=subinword(invname_hold_temp,"company","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"and","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"erie insurance","fire insurance",.)
replace invname_hold_temp=subinword(invname_hold_temp,"ft","and",.)
replace invname_hold_temp=subinword(invname_hold_temp,"accid","accident",.)
replace invname_hold_temp=subinword(invname_hold_temp,"guar","guaranty",.)
replace invname_hold_temp=subinword(invname_hold_temp,"american samoa","assurance",.)
replace invname_hold_temp=subinword(invname_hold_temp,"assur","assurance",.)
replace invname_hold_temp=subinword(invname_hold_temp,"asso","association",.)
replace invname_hold_temp=subinword(invname_hold_temp,"assn","assurance",.)
replace invname_hold_temp=subinword(invname_hold_temp,"br","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"branch","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"u s a","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"us","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"u s","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"usa","",.)
replace invname_hold_temp=subinword(invname_hold_temp,"insur","insurance",.)



replace invname_hold_temp="home savings bank" if invname_hold_orig=="ome Savings Bank"
replace invname_hold_temp="athol savins bank" if invname_hold_orig=="nol Savings Bank"
replace invname_hold_temp="augusta savings bank" if invname_hold_orig=="3ta Savings Bank"
replace invname_hold_temp="people savings bank" if invname_hold_orig=="s Savings Bank"
replace invname_hold_temp="bridgeport savings bank" if invname_hold_orig=="port Savings Bank"
replace invname_hold_temp="stunner savings bank" if invname_hold_orig=="nner Savings Bank"
replace invname_hold_temp="fairfield Savings Bank." if invname_hold_orig=="rfield Savings Bank."
replace invname_hold_temp="gorham savings bank" if invname_hold_orig=="ham Savings Bank"
replace invname_hold_temp="lexington savings bank" if invname_hold_orig=="Savings Bank"
replace invname_hold_temp="medford savings bank" if invname_hold_orig=="dford Savings Bank"
replace invname_hold_temp="meriden savings bank" if invname_hold_orig=="en Savings Bank"
replace invname_hold_temp="city savings bank" if invname_hold_orig=="ty Savings Bank"
replace invname_hold_temp="meriden savings bank" if invname_hold_orig=="n Savings Bank"
replace invname_hold_temp="middletown savings bank" if invname_hold_orig=="town Savings Bank"
replace invname_hold_temp="groton savings bank" if invname_hold_orig=="on Savings Bank"
replace invname_hold_temp="mariners savings bank" if invname_hold_orig=="ers' Savings Bank"
replace invname_hold_temp="newtown savings bank" if invname_hold_orig=="Own Savings Bank"
replace invname_hold_temp="norwich savings bank" if invname_hold_orig=="avings Bank"
replace invname_hold_temp="ridgefield savings bank" if invname_hold_orig=="eld Savings Bank"
replace invname_hold_temp="people savings bank" if invname_hold_orig==";'a Savings Bank"
replace invname_hold_temp="somersworth savings bank" if invname_hold_orig=="worth Savings Bank"
replace invname_hold_temp="stamford savings bank" if invname_hold_orig=="ford Savings Bank"
replace invname_hold_temp="stamford savings bank" if invname_hold_orig=="d Savings Bank"
replace invname_hold_temp="taunton savings bank" if invname_hold_orig=="mton Savings Bank"
replace invname_hold_temp="wakefield savings bank" if invname_hold_orig=="befield Savings Bank"
replace invname_hold_temp="walden savings bank" if invname_hold_orig=="den Savings Bank"
replace invname_hold_temp="winsted savings bank" if invname_hold_orig=="ed Savings Bank"
replace invname_hold_temp="republic life insurance" if invname_hold_orig=="lie Life Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Bom Fire Insurance Company"
replace invname_hold_temp="aetna life insurance" if invname_hold_orig=="na Life Insurance Company"
replace invname_hold_temp="connecticut general life insurance" if invname_hold_orig=="Life Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="Dome Life Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Hume Fire Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="Hone Life Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="rne Life Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="Rome Life Insurance Company"
replace invname_hold_temp="scranton life insurance" if invname_hold_orig=="ton Life Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Bone Fire Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Homo Fire Insurance Company"
replace invname_hold_temp="wildey savings bank" if invname_hold_orig=="Wildey Savings Bank"
replace invname_hold_temp="wildey savings bank" if invname_hold_orig=="WUdey Savings Bank"
replace invname_hold_temp="wildey savings bank" if invname_hold_orig=="Wlldey Savings Bank"
replace invname_hold_temp="malden savings bank" if invname_hold_orig=="Male en Savings Bank"
replace invname_hold_temp="malden savings bank" if invname_hold_orig=="Malden Savings Bank"
replace invname_hold_temp="meriden savings bank" if invname_hold_orig=="Merlden Savings Bank"
replace invname_hold_temp="hampden savings bank" if invname_hold_orig=="Cnmden Savings Bank"
replace invname_hold_temp="salem savings bank" if invname_hold_orig=="Salem Savings Bank"
replace invname_hold_temp="hampden savings bank" if invname_hold_orig=="Campden Savings Bank"
replace invname_hold_temp="walden savings bank" if invname_hold_orig=="Walden Savings Bank"
replace invname_hold_temp="warren savings bank" if invname_hold_orig=="Warren Savings Bank"
replace invname_hold_temp="astor trust" if invname_hold_orig=="Astir Trust Company"
replace invname_hold_temp="astor trust" if invname_hold_orig=="stor Trust Company"
replace invname_hold_temp="astor trust" if invname_hold_orig=="istor Trust Company"
replace invname_hold_temp="astor trust" if invname_hold_orig=="Astor Trust Company"
replace invname_hold_temp="willimantic trust" if invname_hold_orig=="antic Trust Company"
replace invname_hold_temp="easton trust" if invname_hold_orig=="Eastern Trust Company"
replace invname_hold_temp="easton trust" if invname_hold_orig=="Eastlan Trust Company"
replace invname_hold_temp="franklin fire insurance" if invname_hold_orig=="Franklin F ire Insurance Company"
replace invname_hold_temp="franklin fire insurance" if invname_hold_orig=="Franklin l ire Insurance Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="Monton Mutual Fire Insurance Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="Minion Mutual Fire Insurance Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="Manton Mutual Fire Insurance Company"
replace invname_hold_temp="mechanics savings bank" if invname_hold_orig=="hanics' Savings Bank"
replace invname_hold_temp="mechanics savings bank" if invname_hold_orig=="Panics'Savings Bank"
replace invname_hold_temp="slater trust" if invname_hold_orig=="Sinter Trust Company"
replace invname_hold_temp="slater trust" if invname_hold_orig=="Slater Trust Company"
replace invname_hold_temp="dollar savings bank" if invname_hold_orig=="Hollar Savings Bank"
replace invname_hold_temp="dollar savings bank" if invname_hold_orig=="Dnllnr Snvings Bnnk"
replace invname_hold_temp="dorchester savings bank" if invname_hold_orig=="Dorcester Savings Bank."
replace invname_hold_temp="aetna insurance" if invname_hold_orig=="na Insurance Company"
replace invname_hold_temp="sea insurance" if invname_hold_orig=="Sea Insurance Company  Ltd"
replace invname_hold_temp="sun insurance" if invname_hold_orig=="Sun Insurance Company"
replace invname_hold_temp="home insurance" if invname_hold_orig=="Dome Insurance company"
replace invname_hold_temp="home insurance" if invname_hold_orig=="Home Insurance Company"
replace invname_hold_temp="social union assurance" if invname_hold_orig=="he Insurance Company"
replace invname_hold_temp="cranford trust" if invname_hold_orig=="Cranford Trust Company"
replace invname_hold_temp="frankford trust" if invname_hold_orig=="Frankfort Trust Company"
replace invname_hold_temp="frankford trust" if invname_hold_orig=="Frankford Trust Company"
replace invname_hold_temp="providence institution for savings" if invname_hold_orig=="Providence Institution for Savings,"
replace invname_hold_temp="provident institution for savings" if invname_hold_orig=="Provident Institution tor Savings"
replace invname_hold_temp="provident institution for savings" if invname_hold_orig=="Provident Institution for Savings,"
replace invname_hold_temp="providence institution for savings" if invname_hold_orig=="Provide e Institution for Savings"
replace invname_hold_temp="morristown trust" if invname_hold_orig=="Morristown Trust Company"
replace invname_hold_temp="norristown trust" if invname_hold_orig=="Norristown Trust Company"
replace invname_hold_temp="albany trust" if invname_hold_orig=="Albany Trut Company"
replace invname_hold_temp="albany trust" if invname_hold_orig=="Albany Trust Company"
replace invname_hold_temp="albany trust" if invname_hold_orig=="Alba Trust Company"
replace invname_hold_temp="merrimac river savings bank" if invname_hold_orig=="merrimack Kiver Savings Bank"
replace invname_hold_temp="merrimac river savings bank" if invname_hold_orig=="Merrimack River Savings Bank"
replace invname_hold_temp="merrimac river savings bank" if invname_hold_orig=="merimackRiver Savings Bank"
replace invname_hold_temp="gardner savings bank" if invname_hold_orig=="Gardner Savings Bank"
replace invname_hold_temp="gardiner savings bank" if invname_hold_orig=="Gardiner Savings Bank"
replace invname_hold_temp="gardner savings bank" if invname_hold_orig=="Gardner Saiings Bank"
replace invname_hold_temp="marine insurance" if invname_hold_orig=="m Marine Insurance Company  Ltd."
replace invname_hold_temp="maine insurance" if invname_hold_orig==">me Insurance Company"
replace invname_hold_temp="providence mutual fire insurance" if invname_hold_orig=="Providence Mutual Fir Insurance Company"
replace invname_hold_temp="providence mutual life insurance" if invname_hold_orig=="Providence Mutual lire Insurance Company"
replace invname_hold_temp="providence mutual fire insurance" if invname_hold_orig=="Providence Mutual Fire Insurance Company"
replace invname_hold_temp="salisbury savings society" if invname_hold_orig=="bury Savings Society."
replace invname_hold_temp="norwalk savings society" if invname_hold_orig=="Ik Savings Society"
replace invname_hold_temp="norwalk savings society" if invname_hold_orig=="ralk Savings Society"
replace invname_hold_temp="norwalk savings society" if invname_hold_orig=="ilk Savings Society"
replace invname_hold_temp="norwich savings society" if invname_hold_orig=="ich Savings Society"
replace invname_hold_temp="hackensack trust" if invname_hold_orig=="lack Trust Company"
replace invname_hold_temp="land trust" if invname_hold_orig=="Land Trust Company"
replace invname_hold_temp="reading trust" if invname_hold_orig=="ling Trust Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="ton Mutual Fire Insurance Company"
replace invname_hold_temp="worcester mutual fire insurance" if invname_hold_orig=="ter Mutual Fire Insurance Company"
replace invname_hold_temp="new england mutual life insurance" if invname_hold_orig=="New England Mutual I.ife Insurance Company"
replace invname_hold_temp="nation five cents savings bank" if invname_hold_orig=="Natiok Five Cents Savings Bank"
replace invname_hold_temp="john hancock mutual fire insurance" if invname_hold_orig=="John Havock Mutual Life Insurance Company"
replace invname_hold_temp="order of the golden seal" if invname_hold_orig=="Order of the Golden Sed"
replace invname_hold_temp="order of the golden seal" if invname_hold_orig=="Order of the Golden Seal"
replace invname_hold_temp="order of the golden seal" if invname_hold_orig=="Order of the Colder Seal"
replace invname_hold_temp="east boston savings bank" if invname_hold_orig=="st Boston Savings Bank"
replace invname_hold_temp="allemania fire insurance" if invname_hold_orig=="Allemania Fire Insurance Company"
replace invname_hold_temp="allemania fire insurance" if invname_hold_orig=="Allemama Fire Insurance Company"
replace invname_hold_temp="erie county savings bank" if invname_hold_orig=="Ene County Savings Bank"
replace invname_hold_temp="monroe county savings bank" if invname_hold_orig=="roe County Savings Bank"
replace invname_hold_temp="rhinebeck savings bank" if invname_hold_orig=="llhinebeck Savings Bank"
replace invname_hold_temp="rhinebeck savings bank" if invname_hold_orig=="Rliinebeck Savings Bank"
replace invname_hold_temp="rhinebeck savings bank" if invname_hold_orig=="Rhinebeck Savings Bank"
replace invname_hold_temp="state bank of dunsmuir" if invname_hold_orig=="Mate Bank of Dunsmuir"
replace invname_hold_temp="colonial trust" if invname_hold_orig=="Colonial Trust Company"
replace invname_hold_temp="colonial trust" if invname_hold_orig=="ilonial Trust Company"
replace invname_hold_temp="hamburg savings bank" if invname_hold_orig=="amburg Savings Bank"
replace invname_hold_temp="flatbush trust" if invname_hold_orig=="Flatburg Trust Company"
replace invname_hold_temp="rome savings bank" if invname_hold_orig=="Koine Savings Bank"
replace invname_hold_temp="orient insurance" if invname_hold_orig=="ricnt Insurance Company"
replace invname_hold_temp="orient insurance" if invname_hold_orig=="ient Insurance Company"
replace invname_hold_temp="orient insurance" if invname_hold_orig=="Orient Insurance Company"
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Assurance Society of the U"
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Assurance Society of the U. S."
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Insurance Socity"
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Assurance Society"
replace invname_hold_temp="banker trust" if invname_hold_orig=="Jankers Trust Company"
replace invname_hold_temp="banker trust" if invname_hold_orig=="Bankets Trust Company"
replace invname_hold_temp="union trust" if invname_hold_orig=="Union Tmst Company"
replace invname_hold_temp="nassau county trust" if invname_hold_orig=="Nasaa County Trust Company"
replace invname_hold_temp="nassau county trust" if invname_hold_orig=="Nassau County Trust Company"
replace invname_hold_temp="hudson trust" if invname_hold_orig=="idson Trust Company"
replace invname_hold_temp="holyoke mutual fire insurance" if invname_hold_orig=="tlyoke Mutual Fire Insurance Company"
replace invname_hold_temp="first mortgage guaranty and trust" if invname_hold_orig=="Firt Mortgnge Guaranty & Trust Company"
replace invname_hold_temp="rittenhouse trust" if invname_hold_orig=="Kittenbouse Trust Company"
replace invname_hold_temp="farmers and mechanic savings bank" if invname_hold_orig=="Farmere & Mechanics' Savings Bank"
replace invname_hold_temp="merchants and farmers mutual fire insurance" if invname_hold_orig=="Merchants' & Farmers' M.utual Fire Insurance Co."
replace invname_hold_temp="cape ann savings bank" if invname_hold_orig=="Cape Anil Savings Bank"
replace invname_hold_temp="national fire insurance" if invname_hold_orig=="ional Fire Insurance Co."
replace invname_hold_temp="underwriters of new york and boston lloyds" if invname_hold_orig=="Underwriters of New York and Boston Lloyds"
replace invname_hold_temp="underwriters of new york and boston lloyds" if invname_hold_orig=="Underwriters at New York & Boston, Lloyds"
replace invname_hold_temp="underwriters of new york and boston lloyds" if invname_hold_orig=="Underwriters of New York at Boston Lloyds"
replace invname_hold_temp="apollo trust" if invname_hold_orig=="Apollo Trust Company"
replace invname_hold_temp="apollo trust" if invname_hold_orig=="ApoUo Trust Company"
replace invname_hold_temp="national savings bank" if invname_hold_orig=="Nation Savings Bank"
replace invname_hold_temp="middlesex mutual assurance" if invname_hold_orig=="Middlesex Mutual Assurance Company"
replace invname_hold_temp="middlesex mutual insurance" if invname_hold_orig=="Middlesex Mutual Insurance Company"
replace invname_hold_temp="glen lyon bank" if invname_hold_orig=="lien Lyon Bank"
replace invname_hold_temp="standard fire assurance" if invname_hold_orig=="andard Fire Insurance Company"
replace invname_hold_temp="marine insurance company" if invname_hold_orig=="Ma  rine Insurance Company, Ltd"
replace invname_hold_temp="sun mutual insurance" if invname_hold_orig=="Snn Mutual Insurance Company"
replace invname_hold_temp="institution for savings newburyport and vicinity" if invname_hold_orig=="Institution for Savings, Newburyport and Vicin"
replace invname_hold_temp="institution for savings newburyport and vicinity" if invname_hold_orig=="Institution for Savings Newburyport & Vic"
replace invname_hold_temp="employers liability assurance" if invname_hold_orig=="Employers' Liability Assur. Corp."
replace invname_hold_temp="employers liability assurance" if invname_hold_orig=="Employer's Liability Ass. Corp."
replace invname_hold_temp="monroe county savings bank" if invname_hold_orig=="Afonroe County Savings Bank"
replace invname_hold_temp="sun life assurance" if invname_hold_orig=="Sim Life Assurance Company"
replace invname_hold_temp="boiler inspection and insurance" if invname_hold_orig=="BoUer Inspection & Insurance Company"
replace invname_hold_temp="guardian assurance" if invname_hold_orig=="Cardian Assurance Co., Ltd."
replace invname_hold_temp="insurance of north america" if invname_hold_orig=="wurance Company of North America"
replace invname_hold_temp="insurance of north america" if invname_hold_orig=="nirance Company of North America"
replace invname_hold_temp="provident institution for savings" if invname_hold_orig=="evident Institution for Savings"
replace invname_hold_temp="providence institution for savings" if invname_hold_orig=="Evidence Institution for Savings"
replace invname_hold_temp="illinois life insurance" if invname_hold_orig=="Ill.inois Life Insurance Company"
replace invname_hold_temp="illinois fire insurance" if invname_hold_orig=="Ill.inois Fire Insurance Company"
replace invname_hold_temp="hanover fire insurance" if invname_hold_orig=="over Fire Insurance Company"
replace invname_hold_temp="hanover fire insurance" if invname_hold_orig=="er Fire Insurance Company"
replace invname_hold_temp="essex county trust" if invname_hold_orig==">ex County Trust Company"
replace invname_hold_temp="nassau county trust" if invname_hold_orig=="iu County Trust Company"
replace invname_hold_temp="teutonia fire insurance" if invname_hold_orig=="Teutoma Fire Insurance Company"
replace invname_hold_temp="people savings bank" if invname_hold_orig=="'copies' Savings Bank"
replace invname_hold_temp="general accid fire and life assur" if invname_hold_orig=="General Accid,Fire & Life Assur, Corp,"
replace invname_hold_temp="general accid fire and life assur" if invname_hold_orig=="General Acc.. Fire & Life Assur. Corp. Ltd."
replace invname_hold_temp="new england mutual life insurance" if invname_hold_orig=="land" & investor_city_hold=="Boston"
replace invname_hold_temp="iona savings bank" if invname_hold_orig=="lona Savings Bank"


replace invname_hold_temp="nederland limited liability life insurance" if invname_hold_temp=="land Limited Liability Life Ins. Co." & investor_city_temp=="amsterdam/new york"
replace invname_hold_temp="nederland limited liability life insurance" if invname_hold_temp=="Nederland Ltd. Liab. Life Ins. Co." & investor_city_temp=="amsterdam/new york"
replace invname_hold_temp="nederland limited liability life insurance" if invname_hold_temp=="Nederland Ltd. Liabilty Life Ins. Co." & investor_city_temp=="amsterdam/new york"
replace invname_hold_temp="nederland limited liability life insurance" if invname_hold_temp=="Nederland Ltd. Liability Life Insurance Company" & investor_city_temp=="amsterdam/new york"
replace invname_hold_temp="nederland limited liability life insurance" if invname_hold_temp=="Nederland Limited Liability Life Ins. Co." & investor_city_temp=="amsterdam/new york"
replace invname_hold_temp="nederland limited liability life insurance" if invname_hold_temp=="Nederlanil Life Insurance Co." & investor_city_temp=="amsterdam/new york"
replace invname_hold_temp="athol savings bank" if invname_hold_temp=="Athol Savings Bank, Athol, Mass" & investor_city_temp=="athol"
replace invname_hold_temp="templeton savings bank" if invname_hold_temp=="npleton Savings Bank" & investor_city_temp=="baldwinville"
replace invname_hold_temp="maryland life insurance" if invname_hold_temp=="yland Life Insurance Company" & investor_city_temp=="baltimore"
replace invname_hold_temp="german fire insurance" if invname_hold_temp=="Gennan Fire Insurance Company" & investor_city_temp=="baltimore"
replace invname_hold_temp="maryland life insurance" if invname_hold_temp=="Maryumd Life Insurance Company" & investor_city_temp=="baltimore"
replace invname_hold_temp="merchants insurance" if invname_hold_temp=="men iants' Insurance Company" & investor_city_temp=="bangor"
replace invname_hold_temp="penobiscot savings bank" if invname_hold_temp=="scot Savings Bank." & investor_city_temp=="bangor"
replace invname_hold_temp="mechanic trust" if invname_hold_temp=="rchanics' Trust Company" & investor_city_temp=="bayonne"
replace invname_hold_temp="binghamton savings bank" if invname_hold_temp=="Eihgb&mton Savings Bank" & investor_city_temp=="binghamton"
replace invname_hold_temp="mechanic and farmers savings bank of bridgeport" if invname_hold_temp=="lanics' & Farmers' Savings Bank of Bridgeport" & investor_city_temp=="bridgeport"
replace invname_hold_temp="mechanic and farmers savings bank" if invname_hold_temp=="mechanics' 4 Farmers' Savings Bank" & investor_city_temp=="bridgeport"
replace invname_hold_temp="hamburg savings bank" if invname_hold_temp=="nburg Savings Bank" & investor_city_temp=="brooklyn"
replace invname_hold_temp="hamburg savings bank" if invname_hold_temp=="amburg Savings Bank" & investor_city_temp=="brooklyn"
replace invname_hold_temp="long island loan and trust" if invname_hold_temp=="Long Island Lo;in & Trust Company" & investor_city_temp=="brooklyn"
replace invname_hold_temp="wiiliamsburgh city fire insurance" if invname_hold_temp=="Wiiliamsburgh City Eire Insurance Company" & investor_city_temp=="brooklyn"
replace invname_hold_temp="wiiliamsburgh city fire insurance" if invname_hold_temp=="Wiiliamsburgh City Fire Insurance Company" & investor_city_temp=="brooklyn"
replace invname_hold_temp="wiiliamsburgh city fire insurance" if invname_hold_temp=="WIll.iamsburgh City Eire Insurance Company" & investor_city_temp=="brooklyn"
replace invname_hold_temp="wiiliamsburgh city fire insurance" if invname_hold_temp=="Williamsburg City Firfe Instance Company" & investor_city_temp=="brooklyn"
replace invname_hold_temp="wiiliamsburgh city fire insurance" if invname_hold_temp=="Wllliainsburgh City Fire Insurance Company" & investor_city_temp=="brooklyn"
replace invname_hold_temp="topsham and brunswick twenty five cents savings bank" if invname_hold_temp=="am & Brunswick Twenty-five Cent Saw Bank" & investor_city_temp=="brunswick"
replace invname_hold_temp="topsham and brunswick twenty five cents savings bank" if invname_hold_temp=="Topsham & Brunswick 25 Cent Savings Bank" & investor_city_temp=="brunswick"
replace invname_hold_temp="topsham and brunswick twenty five cents savings bank" if invname_hold_temp=="Topsham & Brunswick Twenty-five Cents Sav," & investor_city_temp=="brunswick"
replace invname_hold_temp="topsham and brunswick twenty five cents savings bank" if invname_hold_temp=="Topsham & Brunswick Twenty-Five Cents Savings Bank. Brunswick." & investor_city_temp=="brunswick"
replace invname_hold_temp="topsham and brunswick twenty five cents savings bank" if invname_hold_temp=="Topsham & Brunswick Twenty-five Cents Sav. Bank" & investor_city_temp=="brunswick"
replace invname_hold_temp="buffalo german insurance" if invname_hold_temp=="Buffalo German Ins. Co." & investor_city_temp=="buffalo"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="j-bondale Miners' & Mechanics' Savings Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carbondale Mineral Mechanics' Savings Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carbondale Miners & Me.chanics Savings Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carbondale Miners & mechanics Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carbondale Miners' & mechanics' Sav" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carbondale Miners & mechanics' Savings Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carbondale Miners & mechanics Savings Bank Carbondale" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carbondale Miners & Merchants' Savings Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp=="Carl�ondale Miners & Mechanics' Savings Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="carbondae miners mechanic savings bank" if invname_hold_temp==">ndale Miners' & Mechanics' Savings Bank" & investor_city_temp=="carbondale"
replace invname_hold_temp="pioneer dime bank" if invname_hold_temp=="Pioneer Dime Bank Carbondale" & investor_city_temp=="carbondale"
replace invname_hold_temp="chambersburg trust" if invname_hold_temp=="ambereburg Trust Company" & investor_city_temp=="chambersburg"
replace invname_hold_temp="farmers and mechanic trust of chambersburg" if invname_hold_temp=="Farmers' & Merchants' Trust Co. of Chambersburg" & investor_city_temp=="chambersburg"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="delaware county trust,safe deposit & title insurance company" & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Tr. Safe Deposit & Title Ins. Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust" & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust & Safe Deposit & Title Ins. Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust, Safe Dep. & Title Insurance Company" & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust Safe Deposit & Ins. Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust  Safe Deposit & Insurance Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust,Safe Deposit & Title Ins. Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust, Safe Deposit & Title Insurance Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust,Safe Deposit. Title & Ins. Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware County Trust Safe Dep. & Title Ins. Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware Safe Deposit & Title Ins, Co County Trust" & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware Co. Trust" & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware Co. Trust, Safe Deposit & Title Ins. Co." & investor_city_temp=="chester"
replace invname_hold_temp="delaware county trust safe deposit and title insurance company" if invname_hold_temp=="Delaware Co. Trust  Safe Deposit & Title Insurance Co." & investor_city_temp=="chester"
replace invname_hold_temp="national brewers insurance" if invname_hold_temp=="nal Brewers' Insurance Company" & investor_city_temp=="chicago"
replace invname_hold_temp="american life insurance of illinois" if invname_hold_temp=="American Life Insurance Company of Ill.inois" & investor_city_temp=="chicago"
replace invname_hold_temp="calumet insurance of illinois" if invname_hold_temp=="Calumet Insurance Company of Ill.inois" & investor_city_temp=="chicago"
replace invname_hold_temp="central national fire insurance" if invname_hold_temp=="Central Nfltlonal Eire Insurance Company" & investor_city_temp=="chicago"
replace invname_hold_temp="illinois life insurance" if invname_hold_temp=="Ill.inois Life Ins. Co." & investor_city_temp=="chicago"
replace invname_hold_temp="illinois surety" if invname_hold_temp=="Ill.inois Surety Company" & investor_city_temp=="chicago"
replace invname_hold_temp="illinois life insurance" if invname_hold_temp=="Illinois Life Insurance CompaN. Y." & investor_city_temp=="chicago"
replace invname_hold_temp="lakeview trust and savings bank" if invname_hold_temp=="Lake Ville Trust & Savings Bank" & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Ins. Co. of the United States of America" & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Ins. Co.  of U. S. A." & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Co," & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Company of the U. S." & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Company of the U. S.of A" & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Company of the U. S. of America" & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Company of the United States" & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Company of U. S. A." & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Co. of United States" & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Co. of United States Am." & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Company of U. S. A" & investor_city_temp=="chicago"
replace invname_hold_temp="national life insurance of the united states of america" if invname_hold_temp=="National Life Insurance Company  U. S. A." & investor_city_temp=="chicago"
replace invname_hold_temp="eureka fire and marine insurance" if invname_hold_temp=="Eureka Fire ft Marine Insurance Company" & investor_city_temp=="cincinnati"
replace invname_hold_temp="retail druggists mutual fire insurance" if invname_hold_temp=="Retail Druggists' Mutual Fire Ins. Co." & investor_city_temp=="cincinnati"
replace invname_hold_temp="sun mutual insurance" if invname_hold_temp=="Sim Mutual Insurance Company" & investor_city_temp=="cincinnati"
replace invname_hold_temp="middlesex mutual fire insurance" if invname_hold_temp=="ddlesex Mutual Fire Insurance Company" & investor_city_temp=="concord"
replace invname_hold_temp="capital fire insurance" if invname_hold_temp=="Capital Eire Insurance Company" & investor_city_temp=="concord"
replace invname_hold_temp="concord mutual fire insurance" if invname_hold_temp=="Concord Mutual Fire Ins. Co." & investor_city_temp=="concord"
replace invname_hold_temp="manufacturers and merchants mutual fire insurance" if invname_hold_temp=="Manufacturers & Merchants' Mutual Fire Ins. Co." & investor_city_temp=="concord"
replace invname_hold_temp="manufacturers and merchants mutual fire insurance" if invname_hold_temp=="Manufacturers & Merchants' Mutual Fire Insurance Co." & investor_city_temp=="concord"
replace invname_hold_temp="manufacturers and merchants mutual fire insurance" if invname_hold_temp=="Manufacturers & Merchants' Mutual Life Ins. Co." & investor_city_temp=="concord"
replace invname_hold_temp="merrimac county savings bank" if invname_hold_temp=="Merrimack County Savings Basic" & investor_city_temp=="concord"
replace invname_hold_temp="new hamphire bank" if invname_hold_temp=="Ne wHampshire Bank" & investor_city_temp=="concord"
replace invname_hold_temp="new hampshire savings bank" if invname_hold_temp=="New Hampshire" & investor_city_temp=="concord"
replace invname_hold_temp="new hampshire savings bank" if invname_hold_temp=="New Hampshire Savings Bank" & investor_city_temp=="concord"
replace invname_hold_temp="new hampshire savings bank" if invname_hold_temp=="New Hampshire Savings Bank. Concord" & investor_city_temp=="concord"
replace invname_hold_temp="new hampshire savings bank" if invname_hold_temp=="New Hampshire Savings Bank. Concord. N. H" & investor_city_temp=="concord"
replace invname_hold_temp="new hampshire savings bank" if invname_hold_temp=="New Harnpshire Savings Bank" & investor_city_temp=="concord"
replace invname_hold_temp="underwriters fire insurance" if invname_hold_temp=="Underwriters' Eire Insurance Company" & investor_city_temp=="concord"
replace invname_hold_temp="savings bank of danbury" if invname_hold_temp=="gs Bank of Danbury" & investor_city_temp=="danbury"
replace invname_hold_temp="greenburgh savings bank" if invname_hold_temp=="jlreensburgh Savings Bank" & investor_city_temp=="dobbs ferry"
replace invname_hold_temp="people bank of erie" if invname_hold_temp=="s Bank of Erie" & investor_city_temp=="erie"
replace invname_hold_temp="people bank of erie" if invname_hold_temp=="Bank" & investor_city_temp=="erie"
replace invname_hold_temp="people bank of erie" if invname_hold_temp=="People" & investor_city_temp=="erie"
replace invname_hold_temp="security savings and trust" if invname_hold_temp=="Securities Savings & Trust Company" & investor_city_temp=="erie"
replace invname_hold_temp="security savings and trust" if invname_hold_temp=="Security Savings ft Trust Company" & investor_city_temp=="erie"
replace invname_hold_temp="security savings and trust" if invname_hold_temp=="Security Savings 4 Trust Company" & investor_city_temp=="erie"
replace invname_hold_temp="fairfield savings bank" if invname_hold_temp=="rfield Savings Bank." & investor_city_temp=="fairfield"
replace invname_hold_temp="gorham savings bank" if invname_hold_temp=="Gorlmm Savings Bank" & investor_city_temp=="gorham"
replace invname_hold_temp="gorham savings bank" if invname_hold_temp=="Gorham Savings Bank" & investor_city_temp=="gorham"
replace invname_hold_temp="hackensack trust" if invname_hold_temp=="Hackensack Trust Company" & investor_city_temp=="hackensack"
replace invname_hold_temp="hackensack trust" if invname_hold_temp=="Hackensack Trust Company of Hackensack" & investor_city_temp=="hackensack"
replace invname_hold_temp="hackensack trust" if invname_hold_temp=="Hnckensnck Trust Company" & investor_city_temp=="hackensack"
replace invname_hold_temp="hamburgh and bremen fire insurance" if invname_hold_temp=="g-Bremen Fire Insurance Company" & investor_city_temp=="hamburg/new york"
replace invname_hold_temp="hamburgh and bremen fire insurance" if invname_hold_temp=="Hamburg & Bremen Fire Ins. Co." & investor_city_temp=="hamburg/new york"
replace invname_hold_temp="connecticut mutual life insurance" if invname_hold_temp=="necticut Mutual Life Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="mechanic savings bank" if invname_hold_temp=="nics' Savinra Bank" & investor_city_temp=="hartford"
replace invname_hold_temp="society for savings" if invname_hold_temp=="ty for Savings" & investor_city_temp=="hartford"
replace invname_hold_temp="traveler insurance" if invname_hold_temp=="lers' Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="aetna insurance" if invname_hold_temp=="Aetna Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="aetna life insurance" if invname_hold_temp=="Aetna Iife Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="connecticut fire insurance" if invname_hold_temp=="Connecticut Eire Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="connecticut federal life insurance" if invname_hold_temp=="Conn.ecticut General Life Ins Co" & investor_city_temp=="hartford"
replace invname_hold_temp="connecticut mutual life insurance" if invname_hold_temp=="Connecticut Mutual Life Ins" & investor_city_temp=="hartford"
replace invname_hold_temp="connecticut mutual life insurance" if invname_hold_temp=="Conn.ecticut Mutual Life Insurance CompaN. Y." & investor_city_temp=="hartford"
replace invname_hold_temp="connecticut mutual life insurance" if invname_hold_temp=="Connecticut Mutual Life Insurance Company Hartford" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford county mutual fire insurance" if invname_hold_temp=="Hartford County Mutual Fire Ins. Co" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford fire insurance" if invname_hold_temp=="Hartford Eire Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler & Inspection & Insurance Co" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler & Inspection 4 Insurance Co" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Insp. & Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Insp. k Ins Company" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Insp. & Ins. Co." & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Inspection & Ins. Co." & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Inspection & Insurance Co.." & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Inspection & Insurance Cor" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Inspection ft Insurance Co" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford steam boiler inspection and insurance" if invname_hold_temp=="Hartford Steam Boiler Inspection Insurance Co." & investor_city_temp=="hartford"
replace invname_hold_temp="hartford life insurance" if invname_hold_temp==".i.irtf..rd Life Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="hartford life insurance" if invname_hold_temp=="I Life Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="aetna insurance" if invname_hold_temp=="Letna Insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="orient insurance" if invname_hold_temp=="Orient Iterance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="phoenix insurance" if invname_hold_temp=="Phoenix Company" & investor_city_temp=="hartford"
replace invname_hold_temp="mechanic savings bank" if invname_hold_temp=="Saivings Bank" & investor_city_temp=="hartford"
replace invname_hold_temp="society for savings" if invname_hold_temp=="Society or Savings" & investor_city_temp=="hartford"
replace invname_hold_temp="south side savings bank" if invname_hold_temp=="Scottish Union National Insurance Company (U. S. Br." & investor_city_temp=="hartford"
replace invname_hold_temp="aetna insurance" if invname_hold_temp=="ST. pAl Vetna insurance Company" & investor_city_temp=="hartford"
replace invname_hold_temp="standard fire insurance" if invname_hold_temp=="Starndadard Fire Insurance  Company" & investor_city_temp=="hartford"
replace invname_hold_temp="traveler insurance" if invname_hold_temp=="Travelers' Ins. Co." & investor_city_temp=="hartford"
replace invname_hold_temp="traveler insurance life department" if invname_hold_temp=="Travelers' Insurance Company (Life Dept.)." & investor_city_temp=="hartford"
replace invname_hold_temp="aetna insurance" if invname_hold_temp=="(U. S. Branch" & investor_city_temp=="hartford"
replace invname_hold_temp="hingham institution for savings" if invname_hold_temp=="ffinghftTw Institution for Savings" & investor_city_temp=="hingham"
replace invname_hold_temp="hingham mutual fire insurance" if invname_hold_temp=="Hiiigham Mutual Fire Insurance Company" & investor_city_temp=="hingham"
replace invname_hold_temp="hingham institution for savings" if invname_hold_temp=="Hingham Institution for Savings" & investor_city_temp=="hingham"
replace invname_hold_temp="hingham institution for savings" if invname_hold_temp=="Hingham Institution for Savings. Hingham. Mass.............." & investor_city_temp=="hingham"
replace invname_hold_temp="trust of new jersey" if invname_hold_temp=="list Company of New Jersey" & investor_city_temp=="hoboken"
replace invname_hold_temp="hudson city savings institution" if invname_hold_temp=="son City Savings Institution" & investor_city_temp=="hudson"
replace invname_hold_temp="mercantile trust" if invname_hold_temp=="tile Trust Company" & investor_city_temp=="jersey city"
replace invname_hold_temp="colonial life insurance of america" if invname_hold_temp=="Colonial Life Ins Co of America" & investor_city_temp=="jersey city"
replace invname_hold_temp="fifth ward savings bank" if invname_hold_temp=="Fi&h Ward Savings Bank" & investor_city_temp=="jersey city"
replace invname_hold_temp="lincoln trust of new jersey" if invname_hold_temp=="Lincoyln Trust Company of Jersey." & investor_city_temp=="jersey city"
replace invname_hold_temp="new jersey title guaranty and trust" if invname_hold_temp=="New Jersey Title Guar. & Trust Company" & investor_city_temp=="jersey city"
replace invname_hold_temp="corporation trust" if invname_hold_temp=="Corporation Trust Company" & investor_city_temp=="jersey city"
replace invname_hold_temp="first bank of kern" if invname_hold_temp=="st Bank of Kern" & investor_city_temp=="kern"
replace invname_hold_temp="ulster county savings institution" if invname_hold_temp=="ter County Savings Institution" & investor_city_temp=="kingston"
replace invname_hold_temp="salisbury savings society" if invname_hold_temp=="ry Savings Society" & investor_city_temp=="lakeville"
replace invname_hold_temp="farmers trust" if invname_hold_temp=="FarnifeJfs' Trust Company" & investor_city_temp=="lancaster"
replace invname_hold_temp="northern trust and savings" if invname_hold_temp=="Northern Trust k Savings Company" & investor_city_temp=="lancaster"
replace invname_hold_temp="union trust" if invname_hold_temp=="Union Trust tympany" & investor_city_temp=="lancaster"
replace invname_hold_temp="masioma savings bank" if invname_hold_temp=="iscoma Savings Bank" & investor_city_temp=="lebanon"
replace invname_hold_temp="litchfield mutual fire insurance" if invname_hold_temp=="chfield Mutual Fire Insurance Company" & investor_city_temp=="litchfield"
replace invname_hold_temp="litchfield mutual fire insurance" if invname_hold_temp=="Litchfield Mutual Fire Ins. Co." & investor_city_temp=="litchfield"
replace invname_hold_temp="london and lancashire fire insurance" if invname_hold_temp=="q & Lancashire Fire Insurance Company" & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="british and foreign marine insurance" if invname_hold_temp=="& Foreign Marine Insurance Company  Ltd." & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="british and foreign marine insurance" if invname_hold_temp=="British and Foreign" & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="british and foreign marine insurance" if invname_hold_temp=="British & Foreign Mar. Ins. Co. Ltd." & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="british and foreign marine insurance" if invname_hold_temp=="British & Foreign Marine Ins. Co.. Ltd." & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="liverpool and london globe insurance" if invname_hold_temp=="Liverpool & London/New York & Globe Insurance Company" & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="liverpool and london globe insurance" if invname_hold_temp=="Llverj>ooI ft London & Globe Insurance Company" & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="london and lancashire fire insurance" if invname_hold_temp=="London & Lanc. Fire Ins. Co." & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="london and lancaster fire insurance" if invname_hold_temp=="London & Lane. Fire Inusurance Co." & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="standard marine insurance" if invname_hold_temp=="Standard Marinelns. Co.  Ltd." & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="thames and mersey marine insurance" if invname_hold_temp=="Thames & mersey Ma  rine Insurance Co" & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="union marine insurance companyltd" if invname_hold_temp=="Union Mar. Ins. Co. Ltd." & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="union marine insurance company" if invname_hold_temp=="Union Marine Insurance CompanyLtd" & investor_city_temp=="liverpool/new york"
replace invname_hold_temp="marine insurance" if invname_hold_temp=="ine Ins. Co." & investor_city_temp=="london"
replace invname_hold_temp="alliance assurance" if invname_hold_temp=="Alliance Assur. Co." & investor_city_temp=="london"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Un. Assur. Co." & investor_city_temp=="london"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Union As. Co." & investor_city_temp=="london"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Union Assur. Co." & investor_city_temp=="london"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Union Assurance Company, U. S. Branch" & investor_city_temp=="london"
replace invname_hold_temp="london and lancashire life and federal assurance association" if invname_hold_temp=="London & Lancashire Life & General Assurance Assn.  Ltd." & investor_city_temp=="london"
replace invname_hold_temp="london assurance" if invname_hold_temp=="London Assurance Coro." & investor_city_temp=="london"
replace invname_hold_temp="london guaranty and accident" if invname_hold_temp=="London Guar & Acc Co" & investor_city_temp=="london"
replace invname_hold_temp="marine insurance" if invname_hold_temp=="Marine Ins. Co." & investor_city_temp=="london"
replace invname_hold_temp="north british and mercantile insurance" if invname_hold_temp=="North British & merc. Ins. Co." & investor_city_temp=="london"
replace invname_hold_temp="northern assurance" if invname_hold_temp=="Northern Assur. Co." & investor_city_temp=="london"
replace invname_hold_temp="northern assurance" if invname_hold_temp=="Northern Assurance Company, U. S. Branch" & investor_city_temp=="london"
replace invname_hold_temp="norwich union fire insurance" if invname_hold_temp=="Norwich Union Fire Ins,Co," & investor_city_temp=="london"
replace invname_hold_temp="ocean accid and guaranty" if invname_hold_temp=="Ocean Accident & Guar. Corp." & investor_city_temp=="london"
replace invname_hold_temp="corporation of the london assurance" if invname_hold_temp=="Corporation of the London Assurance" & investor_city_temp=="london"
replace invname_hold_temp="palatine insurance" if invname_hold_temp=="Palatine Ins. Co." & investor_city_temp=="london"
replace invname_hold_temp="phoenix assurance" if invname_hold_temp=="Phoenix Assur. Co." & investor_city_temp=="london"
replace invname_hold_temp="star life assurance society" if invname_hold_temp=="Star Life Assur. Society" & investor_city_temp=="london"
replace invname_hold_temp="sun ins office" if invname_hold_temp=="Sun Insurance Off." & investor_city_temp=="london"
replace invname_hold_temp="union assurance society" if invname_hold_temp=="Union Assurance Soc,Ltd," & investor_city_temp=="london"
replace invname_hold_temp="assurance" if invname_hold_temp=="asurance Co." & investor_city_temp=="london/new york"
replace invname_hold_temp="indiana insurance office" if invname_hold_temp=="in Ins. Office" & investor_city_temp=="london/new york"
replace invname_hold_temp="assurance" if invname_hold_temp=="Assur. Co.. Ltd." & investor_city_temp=="london/new york"
replace invname_hold_temp="commercial illinois assurance" if invname_hold_temp=="Commercial I'll. Assur. Co." & investor_city_temp=="london/new york"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Union As. Co.. London" & investor_city_temp=="london/new york"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Union As. Co.. London/New York. Eng./N. Y" & investor_city_temp=="london/new york"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Union Assur. Co.. London/New York" & investor_city_temp=="london/new york"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Commercial Union Assurance Association" & investor_city_temp=="london/new york"
replace invname_hold_temp="commercial union assurance" if invname_hold_temp=="Com. Union Assurance Co." & investor_city_temp=="london/new york"
replace invname_hold_temp="european accident insurance" if invname_hold_temp=="European Accident Ins. Co.,  Ltd." & investor_city_temp=="london/new york"
replace invname_hold_temp="london assurance" if invname_hold_temp=="London As. Corporation" & investor_city_temp=="london/new york"
replace invname_hold_temp="london assurance" if invname_hold_temp=="London Assur. Corporation" & investor_city_temp=="london/new york"
replace invname_hold_temp="london assurance" if invname_hold_temp=="London Assurance comp" & investor_city_temp=="london/new york"
replace invname_hold_temp="london assurance london" if invname_hold_temp=="London Assurance Corp.. London" & investor_city_temp=="london/new york"
replace invname_hold_temp="north british and mercantile insurance" if invname_hold_temp=="North British & merc. Ins. Co  London" & investor_city_temp=="london/new york"
replace invname_hold_temp="north british and mercantile insurance" if invname_hold_temp=="North British k Mercantile Ins. Co." & investor_city_temp=="london/new york"
replace invname_hold_temp="northern assurance" if invname_hold_temp=="Northern As. Co" & investor_city_temp=="london/new york"
replace invname_hold_temp="ocean accident and guaranty london" if invname_hold_temp=="Ocean Acc. & Guarantee Corp.. London" & investor_city_temp=="london/new york"
replace invname_hold_temp="ocean accident and guarantee" if invname_hold_temp=="Ocean Accident &GuaranteeCorp." & investor_city_temp=="london/new york"
replace invname_hold_temp="phoenix assurance london" if invname_hold_temp=="Phoenix Assur. Co  Ltd  London" & investor_city_temp=="london/new york"
replace invname_hold_temp="phoenix assurance society" if invname_hold_temp=="Phoenix Assur. Soc. Ltd" & investor_city_temp=="london/new york"
replace invname_hold_temp="royal exchange and assurance" if invname_hold_temp=="Royal Exchange &ssur." & investor_city_temp=="london/new york"
replace invname_hold_temp="royal exchange assurance" if invname_hold_temp=="Royal Exchange Ass'n" & investor_city_temp=="london/new york"
replace invname_hold_temp="sun insurance offiice" if invname_hold_temp=="Sun Ins Office London Eng" & investor_city_temp=="london/new york"
replace invname_hold_temp="sun insurance offiice" if invname_hold_temp=="Sun Insurance Office London/New York" & investor_city_temp=="london/new york"

