
replace $x="buxton" if $x=="buxt on"
replace $x="boston" if $x=="baston"
replace $x="boston" if $x=="buston"
replace $x="canton" if $x=="conton"
replace $x="boston" if $x=="ponton"
replace $x="boston" if $x=="ronton"
replace $x="boston" if $x=="roston"
replace $x="boston" if $x=="rostov"
replace $x="easton" if $x=="eaton"
replace $x="scranton" if $x=="rcranton"
replace $x="scranton" if $x=="scran ton"
replace $x="scranton" if $x=="scranto"
replace $x="scranton" if $x=="seranton"
replace $x="philadelphia" if $x=="phdadelphia"
replace $x="philadelphia" if $x=="phi ladelphia"
replace $x="philadelphia" if $x=="phialdelphia"
replace $x="philadelphia" if $x=="philaadelphia"
replace $x="philadelphia" if $x=="philadel phia"
replace $x="philadelphia" if $x=="philadelpha"
replace $x="philadelphia" if $x=="philadelphi"
replace $x="philadelphia" if $x=="philadelphie"
replace $x="philadelphia" if $x=="philadelphla"
replace $x="philadelphia" if $x=="philadephia"
replace $x="philadelphia" if $x=="philadlphia"
replace $x="philadelphia" if $x=="philadtlphia"
replace $x="philadelphia" if $x=="phildelphia"
replace $x="philadelphia" if $x=="philladelphia"
replace $x="philadelphia" if $x=="phladelphia"
replace $x="philadelphia" if $x=="phlladelphia"
replace $x="philadelphia" if $x=="phuadelphia"
replace $x="philadelphia" if $x=="phusdelphia"
replace $x="philadelphia" if $x=="piladelphia"
replace $x="pittsfield" if $x=="pilttsfield"
replace $x="pittsfield" if $x=="pittfield"
replace $x="pittsfield" if $x=="pitts field"
replace $x="pittsfield" if $x=="pittsffeld"
replace $x="pittsfield" if $x=="pittsfieid"
replace $x="pittsfield" if $x=="pittsfleld"
replace $x="pittsfield" if $x=="pittslield"
replace $x="pittsfield" if $x=="pittsrield"
replace $x="pittsfield" if $x=="pittstield"
replace $x="pittsfield" if $x=="plitsfield"
replace $x="pittsfield" if $x=="plttsfield"
replace $x="pittsfield" if $x=="plttsfleld"
replace $x="pittsfield" if $x=="ptttsfield"
replace $x="pittsfield" if $x=="rittsfield"
replace $x="pittsfield" if $x=="tittsfield"
replace $x="pittsburg" if $x=="ittsburg"
replace $x="pittsburg" if $x=="pitsburg"
replace $x="pittsburg" if $x=="pittburgh"
replace $x="pittsburg" if $x=="pittcburgh"
replace $x="pittsburg" if $x=="pittsbnrg"
replace $x="pittsburg" if $x=="pittsbu rgh"
replace $x="pittsburg" if $x=="pittsbuegh"
replace $x="pittsburg" if $x=="pittsbugh"
replace $x="pittsburg" if $x=="pittsbuigh"
replace $x="pittsburg" if $x=="pittsbureh"
replace $x="pittsburg" if $x=="pittsburgh"
replace $x="pittsburg" if $x=="pittsburghh"
replace $x="pittsburg" if $x=="pittsburs"
replace $x="pittsburg" if $x=="pittssburgh"
replace $x="new york" if $x=="ne w york"
replace $x="new york" if $x=="new  york"
replace $x="new york" if $x=="new \ ork"
replace $x="new york" if $x=="new \ork"
replace $x="new york" if $x=="new \rork"
replace $x="new york" if $x=="new nork"
replace $x="new york" if $x=="new y ork"
replace $x="new york" if $x=="new yor"
replace $x="new york" if $x=="newb york"
replace $x="new york" if $x=="newyork"
replace $x="new york" if $x=="now york"
replace $x="new york" if $x=="nw york"
replace $x="new york" if $x=="sew york"
replace $x="new york" if $x=="xew york"
replace $x="moorestown" if $x=="mobrestown"
replace $x="moorestown" if $x=="moorestowa"
replace $x="moorestown" if $x=="moorestowu"
replace $x="morristown" if $x=="mooristown"
replace $x="morristown" if $x=="morribtown"
replace $x="morristown" if $x=="morris town"
replace $x="morristown" if $x=="morrlstown"
replace $x="norristown" if $x=="norribtown"
replace $x="norristown" if $x=="norriston"
replace $x="norristown" if $x=="norristow"
replace $x="norristown" if $x=="norrlstown"
replace $x="providence" if $x=="povidence"
replace $x="providence" if $x=="proovidence"
replace $x="providence" if $x=="providcnce"
replace $x="providence" if $x=="providenc"
replace $x="providence" if $x=="providence?"
replace $x="providence" if $x=="providene"
replace $x="providence" if $x=="providenoe"
replace $x="providence" if $x=="provident"
replace $x="providence" if $x=="providenve"
replace $x="providence" if $x=="providerce"
replace $x="providence" if $x=="providnce"
replace $x="providence" if $x=="province"
replace $x="providence" if $x=="rovidence"
replace $x="wilkes barre" if $x=="wifkesbarre"
replace $x="wilkes barre" if $x=="wilke barre"
replace $x="wilkes barre" if $x=="wilkeebarre"
replace $x="wilkes barre" if $x=="wilkegbarre"
replace $x="wilkes barre" if $x=="wilkersbarre"
replace $x="wilkes barre" if $x=="wilkes harre"
replace $x="wilkes barre" if $x=="wilkesbare"
replace $x="wilkes barre" if $x=="wilkesbarre"
replace $x="wilkes barre" if $x=="wilkesbarry"
replace $x="wilkes barre" if $x=="wilkesburre"
replace $x="wilkes barre" if $x=="wilkesrarre"
replace $x="wilkes barre" if $x=="wlikesbarre"
replace $x="wilkes barre" if $x=="wllkesbarre"
replace $x="pottsville" if $x=="pot tsville"
replace $x="pottsville" if $x=="potteville"
replace $x="pottsville" if $x=="pottsille"
replace $x="pottsville" if $x=="pottsviiie"
replace $x="pottsville" if $x=="pottsvile"
replace $x="pottsville" if $x=="pottsvilie"
replace $x="pottsville" if $x=="pottsvilla"
replace $x="pottsville" if $x=="pottsvillie"
replace $x="pottsville" if $x=="pottsviue"
replace $x="pottsville" if $x=="pottsvllle"
replace $x="portland" if $x=="porland"
replace $x="portland" if $x=="porrland"
replace $x="portland" if $x=="port laud"
replace $x="portland" if $x=="portand"
replace $x="portland" if $x=="portlan"
replace $x="portland" if $x=="porttland"
replace $x="portland" if $x=="port land"
replace $x="hartford" if $x=="haitford"
replace $x="hartford" if $x=="harford"
replace $x="hartford" if $x=="harrford"
replace $x="hartford" if $x=="hartfora"
replace $x="hartford" if $x=="hartfort"
replace $x="hartford" if $x=="hartfotd"
replace $x="hartford" if $x=="harttord"
replace $x="hartford" if $x=="nartford"
replace $x="lancaster" if $x=="lanchester"
replace $x="manchester" if $x=="mahchester"
replace $x="manchester" if $x=="manachester"
replace $x="manchester" if $x=="manchcester"
replace $x="manchester" if $x=="monchester"
replace $x="manchester" if $x=="slanchester"
replace $x="lancaster" if $x=="lanchaster"
replace $x="middleton" if $x=="midditown"
replace $x="middleton" if $x=="middlctown"
replace $x="middleton" if $x=="middle town"
replace $x="middleton" if $x=="middletwn"
replace $x="middleton" if $x=="mlddletown"
replace $x="middleton" if $x=="middietown"
replace $x="middleton" if $x=="middletowu"
replace $x="paterson" if $x=="parerson"
replace $x="paterson" if $x=="patcrson"
replace $x="paterson" if $x=="pateraon"
replace $x="paterson" if $x=="patereon"
replace $x="paterson" if $x=="patersou"
replace $x="paterson" if $x=="patprson"
replace $x="paterson" if $x=="patterson"
replace $x="paterson" if $x=="peterson"
replace $x="springfield" if $x=="sp  ringfield"
replace $x="springfield" if $x=="sp ringfield"
replace $x="springfield" if $x=="spingfield"
replace $x="springfield" if $x=="sprinfield"
replace $x="springfield" if $x=="springfiel"
replace $x="springfield" if $x=="springfiela"
replace $x="springfield" if $x=="springrfield"
replace $x="springfield" if $x=="springtield"
replace $x="utica" if $x=="erica"
replace $x="utica" if $x=="etica"
replace $x="utica" if $x=="ttica"
replace $x="utica" if $x=="utlca"
replace $x="erie" if $x=="eria"
replace $x="erie" if $x=="eric"
replace $x="lansdowne" if $x=="lanadowne"
replace $x="lansdowne" if $x=="landsdowne"
replace $x="lansdowne" if $x=="landsowne"
replace $x="lansdowne" if $x=="lanndowne"
replace $x="lansdowne" if $x=="lansdawne"
replace $x="lansdowne" if $x=="lansdnwne"
replace $x="lansdowne" if $x=="lawndowne"
replace $x="liverpool" if $x=="liveroool"
replace $x="liverpool" if $x=="liverpoool"
replace $x="liverpool" if $x=="liveipool"
replace $x="liverpool" if $x=="liverpoo"
replace $x="liverpool" if $x=="livenpool"
replace $x="liverpool" if $x=="liverpoll"
replace $x="mifflinburg" if $x=="miffinburg"
replace $x="mifflinburg" if $x=="mifflenbury"
replace $x="mifflinburg" if $x=="mifflinbure"
replace $x="mifflinburg" if $x=="mifflinburgh"
replace $x="mifflinburg" if $x=="mifflinbury"
replace $x="mifflinburg" if $x=="miffllnburg"
replace $x="mifflinburg" if $x=="mifilinburg"
replace $x="newburgh" if $x=="newbureh"
replace $x="newburgh" if $x=="newburg"
replace $x="newburgh" if $x=="newburgb"
replace $x="newburgh" if $x=="newburry"
replace $x="newburgh" if $x=="newhurgh"
replace $x="newburgh" if $x=="newsburgh"
replace $x="plainfield" if $x=="plainflela"
replace $x="plainfield" if $x=="plainfleld"
replace $x="plainfield" if $x=="plaintfield"
replace $x="plainfield" if $x=="plaiufield"
replace $x="plainfield" if $x=="plalnfield"
replace $x="plainfield" if $x=="plalntield"
replace $x="plainfield" if $x=="piainfield"
replace $x="san francisco" if $x=="san franciso"
replace $x="san francisco" if $x=="san franclsco"
replace $x="san francisco" if $x=="san francsco"
replace $x="san francisco" if $x=="san franeisco"
replace $x="san francisco" if $x=="san franscisco"
replace $x="san francisco" if $x=="sau francisco"
replace $x="san francisco" if $x=="snn francisco"
replace $x="williamsport" if $x=="wiiliamsport"
replace $x="williamsport" if $x=="wiliamsport"
replace $x="williamsport" if $x=="willamsport"
replace $x="williamsport" if $x=="willlamsport"
replace $x="williamsport" if $x=="willliamsport"
replace $x="williamsport" if $x=="wlliamsport"
replace $x="williamsport" if $x=="wllliamsport"
replace $x="aixlachapelle" if $x=="aix le chapelle"
replace $x="aixlachapelle" if $x=="aix la chapelle"
replace $x="aixlachapelle" if $x=="aixiachapelle"
replace $x="aixlachapelle" if $x=="aixlachapellc"
replace $x="aixlachapelle" if $x=="aix lachapelle"
replace $x="aixlachapelle" if $x=="alxlachapelle"
replace $x="reading" if $x=="beading"
replace $x="reading" if $x=="bending"
replace $x="reading" if $x=="heading"
replace $x="reading" if $x=="rending"
replace $x="reading" if $x=="roading"
replace $x="doylestown" if $x=="doyeston"
replace $x="doylestown" if $x=="doylcstown"
replace $x="doylestown" if $x=="doyleetown"
replace $x="doylestown" if $x=="doyleston"
replace $x="doylestown" if $x=="doylestowu"
replace $x="doylestown" if $x=="doylestwon"
replace $x="kennebunk" if $x=="kenncbunk"
replace $x="kennebunk" if $x=="kennebank"
replace $x="kennebunk" if $x=="kennebunke"
replace $x="kennebunk" if $x=="kennehunk"
replace $x="kennebunk" if $x=="kenuebunk"
replace $x="kennebunk" if $x=="keunebunk"
replace $x="los angeles" if $x=="lcs angeles"
replace $x="los angeles" if $x=="loa angeles"
replace $x="los angeles" if $x=="lob angeles"
replace $x="los angeles" if $x=="los angeies"
replace $x="los angeles" if $x=="los angles"
replace $x="los angeles" if $x=="los augeles"
replace $x="albany" if $x=="&lbany"
replace $x="albany" if $x=="albaany"
replace $x="albany" if $x=="albang"
replace $x="albany" if $x=="albanv"
replace $x="binghamton" if $x=="bingbamton"
replace $x="binghamton" if $x=="bingham ton"
replace $x="binghamton" if $x=="binghampton"
replace $x="binghamton" if $x=="binhamton"
replace $x="binghamton" if $x=="blnghamton"
replace $x="carbondale" if $x=="carbondaie"
replace $x="carbondale" if $x=="carbondal"
replace $x="carbondale" if $x=="carbondlale"
replace $x="carbondale" if $x=="carboudale"
replace $x="carbondale" if $x=="carhondale"
replace $x="chambersburg" if $x=="chambcrsburg"
replace $x="chambersburg" if $x=="chamberaburg"
replace $x="chambersburg" if $x=="chambereburg"
replace $x="chambersburg" if $x=="chambersburgh"
replace $x="chambersburg" if $x=="chambershurg"
replace $x="danvers" if $x=="dan vers"
replace $x="danvers" if $x=="danvere"
replace $x="danvers" if $x=="donrers"
replace $x="danvers" if $x=="donvers"
replace $x="danvers" if $x=="dunvers"
replace $x="elmira" if $x=="eimira"
replace $x="elmira" if $x=="eimlra"
replace $x="elmira" if $x=="elmir"
replace $x="elmira" if $x=="elmirn"
replace $x="elmira" if $x=="elmlra"
replace $x="fitchburg" if $x=="eltchburg"
replace $x="fitchburg" if $x=="fitch burg"
replace $x="fitchburg" if $x=="fitchhurg"
replace $x="fitchburg" if $x=="fitehburg"
replace $x="fitchburg" if $x=="fltchburg"
replace $x="jersey city" if $x=="ersey city"
replace $x="jersey city" if $x=="jereey city"
replace $x="jersey city" if $x=="jersev city"
replace $x="jersey city" if $x=="jersey cit"
replace $x="jersey city" if $x=="jersey citv"
replace $x="greensburg" if $x=="greeensburg"
replace $x="greensburg" if $x=="greensberg"
replace $x="greensburg" if $x=="greensbnrg"
replace $x="greensburg" if $x=="greensburgh"
replace $x="greensburg" if $x=="greenshurg"
replace $x="harrisburg" if $x=="harrisbnrg"
replace $x="harrisburg" if $x=="harrisburgh"
replace $x="harrisburg" if $x=="harrishurg"
replace $x="harrisburg" if $x=="harrlsburg"
replace $x="harrisburg" if $x=="narrisburg"
replace $x="london" if $x=="lndon"
replace $x="london" if $x=="iondon"
replace $x="london" if $x=="loudon"
replace $x="london" if $x=="londo"
replace $x="rhinebeck" if $x=="khinebcck"
replace $x="rhinebeck" if $x=="khinebeck"
replace $x="rhinebeck" if $x=="rhinbeck"
replace $x="rhinebeck" if $x=="rhinebeek"
replace $x="rhinebeck" if $x=="rhlnebeck"
replace $x="new haven" if $x=="new havn"
replace $x="new haven" if $x=="newhaven"
replace $x="new haven" if $x=="now haven"
replace $x="new haven" if $x=="rew haven"
replace $x="new haven" if $x=="yew haven"
replace $x="newark" if $x=="newaik"
replace $x="newark" if $x=="newalk"
replace $x="newark" if $x=="newart"
replace $x="newark" if $x=="newrk"
replace $x="newark" if $x=="xewark"
replace $x="pawtucket" if $x=="pawtncket"
replace $x="pawtucket" if $x=="pawtucke"
replace $x="pawtucket" if $x=="pawtuckec"
replace $x="pawtucket" if $x=="pawtucker"
replace $x="pawtucket" if $x=="pawtueket"
replace $x="poughkeepsie" if $x=="pougbkeepsie"
replace $x="poughkeepsie" if $x=="poughkeepaie"
replace $x="poughkeepsie" if $x=="poughkeepsic"
replace $x="poughkeepsie" if $x=="poughkeepsle"
replace $x="poughkeepsie" if $x=="poughkeppsle"
replace $x="schenectady" if $x=="scenectady"
replace $x="schenectady" if $x=="schenecpady"
replace $x="schenectady" if $x=="schenectaay"
replace $x="schenectady" if $x=="schenectadv"
replace $x="schenectady" if $x=="schnectady"
replace $x="willimantic" if $x=="willimanti"
replace $x="willimantic" if $x=="willimantlc"
replace $x="willimantic" if $x=="willimautic"
replace $x="willimantic" if $x=="willlmantic"
replace $x="willimantic" if $x=="wlllimantic"
replace $x="woonsocket" if $x=="wooasocket"
replace $x="woonsocket" if $x=="woonsockct"
replace $x="woonsocket" if $x=="woonsockt"
replace $x="woonsocket" if $x=="woonsoeket"
replace $x="woonsocket" if $x=="wooonsocket"
replace $x="baldwinville" if $x=="baldwinsville"
replace $x="baldwinville" if $x=="baldwinvllle"
replace $x="baldwinville" if $x=="baldwlnsville"
replace $x="baldwinville" if $x=="baldwlnvllle"
replace $x="rockville" if $x=="bockville"
replace $x="rockville" if $x=="kockville"
replace $x="rockville" if $x=="rockrille"
replace $x="rockville" if $x=="rockvllle"
replace $x="brooklyn" if $x=="brookalyn"
replace $x="brooklyn" if $x=="brooklvn"
replace $x="brooklyn" if $x=="broooklyn"
replace $x="brooklyn" if $x=="rooklyn"
replace $x="charlestown" if $x=="charles town"
replace $x="charlestown" if $x=="charleetown"
replace $x="charlestown" if $x=="charlestowu"
replace $x="coatesville" if $x=="coatesvillc"
replace $x="coatesville" if $x=="coatesvllle"
replace $x="coatesville" if $x=="coatesyille"
replace $x="coatesville" if $x=="coatsville"
replace $x="east jaffrey" if $x=="east jaffray"
replace $x="east jaffrey" if $x=="east jaffrev"
replace $x="east jaffrey" if $x=="east jeffray"
replace $x="east jaffrey" if $x=="east jeffrey"
replace $x="lewiston" if $x=="ewiston"
replace $x="lewiston" if $x=="lewis ton"
replace $x="lewiston" if $x=="lewlston"
replace $x="farmington" if $x=="farmtngton"
replace $x="farmington" if $x=="harmington"
replace $x="farmington" if $x=="farmingtotn"
replace $x="farmington" if $x=="farmingtou"
replace $x="pittston" if $x=="fittston"
replace $x="pittston" if $x=="piittston"
replace $x="pittston" if $x=="pittson"
replace $x="pittston" if $x=="plttston"
replace $x="freeland" if $x=="frecland"
replace $x="freeland" if $x=="free land"
replace $x="freeland" if $x=="freelaud"
replace $x="freeland" if $x=="freoland"
replace $x="rockport" if $x=="kockport"
replace $x="rockport" if $x=="roekport"
replace $x="rockport" if $x=="rockportj"
replace $x="machias" if $x=="macbias"
replace $x="machias" if $x=="machlas"
replace $x="machias" if $x=="maehlas"
replace $x="machias" if $x=="muchias"
replace $x="mckees rocks" if $x=="mckee  rocks"
replace $x="mckees rocks" if $x=="mckee rocks"
replace $x="mckees rocks" if $x=="mckees rock"
replace $x="mckees rocks" if $x=="mekees rocks"
replace $x="newburyport" if $x=="newburport"
replace $x="newburyport" if $x=="newburvport"
replace $x="newburyport" if $x=="newbury port"
replace $x="newburyport" if $x=="newbuyport"
replace $x="passaic" if $x=="passaie"
replace $x="passaic" if $x=="passale"
replace $x="passaic" if $x=="passalo"
replace $x="passaic" if $x=="passic"
replace $x="shelburne falls" if $x=="shelbourne falls"
replace $x="shelburne falls" if $x=="shelburne fails"
replace $x="shelburne falls" if $x=="shelburne falla"
replace $x="shelburne falls" if $x=="shellburne falls"
replace $x="south norwalk" if $x=="south  norwalk"
replace $x="south norwalk" if $x=="south nor walk"
replace $x="south norwalk" if $x=="south norwak"
replace $x="south norwalk" if $x=="soutn norwalk"
replace $x="st petersburg" if $x=="st petetrsburg"
replace $x="st petersburg" if $x=="stpetersburg"
replace $x="st petersburg" if $x=="stpeterburg"
replace $x="waverly" if $x=="warerly"
replace $x="waverly" if $x=="waveriy"
replace $x="waverly" if $x=="wavery"
replace $x="waverly" if $x=="wayerly"
replace $x="westfield" if $x=="west field"
replace $x="westfield" if $x=="westfleld"
replace $x="westfield" if $x=="westlield"
replace $x="westfield" if $x=="westfieid"
replace $x="whitinsville" if $x=="whitinsvilie"
replace $x="whitinsville" if $x=="whitinsvillo"
replace $x="whitinsville" if $x=="whitinsvllle"
replace $x="whitinsville" if $x=="whitlnsville"
replace $x="wiscasset" if $x=="wiscaseet"
replace $x="wiscasset" if $x=="wiscassett"
replace $x="wiscasset" if $x=="wiseasset"
replace $x="wiscasset" if $x=="wlscasset"
replace $x="abington" if $x=="ablngton"
replace $x="abington" if $x=="abngton"
replace $x="abington" if $x=="ahington"
replace $x="allegheny" if $x=="alegheny"
replace $x="allegheny" if $x=="allegheney"
replace $x="auburn" if $x=="anburn"
replace $x="auburn" if $x=="aubern"
replace $x="auburn" if $x=="aubur"
replace $x="buffalo" if $x=="baffalo"
replace $x="buffalo" if $x=="buflalo"
replace $x="buffalo" if $x=="buftalo"
replace $x="baltimore" if $x=="baltimoe"
replace $x="baltimore" if $x=="baltlimore"
replace $x="baltimore" if $x=="raltimore"
replace $x="bellefonte" if $x=="belefonte"
replace $x="bellefonte" if $x=="beliefonte"
replace $x="bellefonte" if $x=="bellfonte"
replace $x="hingham" if $x=="hingbam"
replace $x="hingham" if $x=="hlngham"
replace $x="boothbay harbor" if $x=="bootbbay harbor"
replace $x="boothbay harbor" if $x=="booth bay harbor"
replace $x="boothbay harbor" if $x=="bootnbay harbor"
replace $x="bridgton" if $x=="brldgton"
replace $x="bridgeton" if $x=="bridge ton"
replace $x="bridgewater" if $x=="bridge water"
replace $x="bridgewater" if $x=="bridgewate"
replace $x="bridgewater" if $x=="brldgewater"
replace $x="cohasset" if $x=="cobasset"
replace $x="cohasset" if $x=="cohasett"
replace $x="cohasset" if $x=="cohassett"
replace $x="danbury" if $x=="danbnry"
replace $x="danbury" if $x=="danburym"
replace $x="danbury" if $x=="dannury"
replace $x="fall river" if $x=="fail river"
replace $x="fall river" if $x=="fall rirer"
replace $x="fall river" if $x=="fall rive"
replace $x="greensboro" if $x=="greenboro"
replace $x="greensboro" if $x=="greensb ro"
replace $x="greensboro" if $x=="ureensboro"
replace $x="hackensack" if $x=="haekensack"
replace $x="hackensack" if $x=="haekensaek"
replace $x="hackensack" if $x=="hakensack"
replace $x="hamburg" if $x=="hamburgh"
replace $x="hamburg" if $x=="hamsburg"
replace $x="hazleton" if $x=="hasleton"
replace $x="hazleton" if $x=="haxleton"
replace $x="hazleton" if $x=="hazieton"
replace $x="hayward" if $x=="hay ward"
replace $x="hayward" if $x=="hay wards"
replace $x="hayward" if $x=="haywards"
replace $x="hershey" if $x=="herahey"
replace $x="hershey" if $x=="hershcy"
replace $x="hershey" if $x=="hershev"
replace $x="rochester" if $x=="rochenter"
replace $x="rochester" if $x=="hochester"
replace $x="rochester" if $x=="rocheste"
replace $x="holliston" if $x=="hoiliston"
replace $x="holliston" if $x=="holiiston"
replace $x="holliston" if $x=="holllston"
replace $x="huntingdon" if $x=="hundingdon"
replace $x="huntingdon" if $x=="huntington"
replace $x="huntingdon" if $x=="huntiugdon"
replace $x="indiana" if $x=="indaiana"
replace $x="indiana" if $x=="indianaa"
replace $x="indiana" if $x=="indiiana"
replace $x="jersey shore" if $x=="jersev shore"
replace $x="jersey shore" if $x=="jerseyshore"
replace $x="jersey shore" if $x=="tersey shore"
replace $x="jewett city" if $x=="jewett clty"
replace $x="jewett city" if $x=="jewettcity"
replace $x="jewett city" if $x=="jewitt city"
replace $x="laconia" if $x=="laconla"
replace $x="laconia" if $x=="laeonia"
replace $x="laconia" if $x=="lieonia"
replace $x="marianna" if $x=="marlanna"
replace $x="marianna" if $x=="marcanna"
replace $x="marianna" if $x=="mariana"
replace $x="medway" if $x=="mcdway"
replace $x="medway" if $x=="med way"
replace $x="medway" if $x=="midway"
replace $x="middleborough" if $x=="middle borough"
replace $x="middleborough" if $x=="middleborongh"
replace $x="middleborough" if $x=="middleborougb"
replace $x="milford" if $x=="miiford"
replace $x="milford" if $x=="millford"
replace $x="milford" if $x=="mllford"
replace $x="milwaukee" if $x=="milwankee"
replace $x="milwaukee" if $x=="milwaukeee"
replace $x="milwaukee" if $x=="wilwaukee"
replace $x="montclair" if $x=="montclalr"
replace $x="montclair" if $x=="montelair"
replace $x="montclair" if $x=="monclair"
replace $x="niagara falls" if $x=="nagara falls"
replace $x="niagara falls" if $x=="naigara falls"
replace $x="niagara falls" if $x=="niagara fals"
replace $x="naugatuck" if $x=="nangatuck"
replace $x="naugatuck" if $x=="naueatuck"
replace $x="naugatuck" if $x=="naugntuck"
replace $x="newport" if $x=="new tort"
replace $x="newport" if $x=="new port"
replace $x="newport" if $x=="xewport"
replace $x="somerville" if $x=="omerville"
replace $x="somerville" if $x=="somerviile"
replace $x="somerville" if $x=="somervllle"
replace $x="philadelphia" if $x=="phila"
replace $x="philadelphia" if $x=="philla"
replace $x="philadelphia" if $x=="phills"
replace $x="philadelphia" if $x=="phlla"
replace $x="saco" if $x=="saeo"
replace $x="saco" if $x=="saoo"
replace $x="saco" if $x=="sato"
replace $x="searsport" if $x=="sea report"
replace $x="searsport" if $x=="seareport"
replace $x="searsport" if $x=="sears port"
replace $x="shamokin" if $x=="shamokln"
replace $x="shamokin" if $x=="shomokin"
replace $x="shamokin" if $x=="snamokin"
replace $x="southington" if $x=="soutbington"
replace $x="southington" if $x=="southlngton"
replace $x="southington" if $x=="southlugton"
replace $x="south bethlehem" if $x=="south bethelehem"
replace $x="south bethlehem" if $x=="south bethelem"
replace $x="south bethlehem" if $x=="south bethelhem"
replace $x="syracuse" if $x=="sqracuse"
replace $x="syracuse" if $x=="syrause"
replace $x="syracuse" if $x=="syrncuse"
replace $x="sunbury" if $x=="sunbuiy"
replace $x="sunbury" if $x=="sunbunry"
replace $x="sunbury" if $x=="sunburv"
replace $x="titusville" if $x=="titiusville"
replace $x="titusville" if $x=="titusvilie"
replace $x="titusville" if $x=="tltusville"
replace $x="yonkers" if $x=="yonkere"
replace $x="yonkers" if $x=="tonkers"
replace $x="yonkers" if $x=="yorkers"
replace $x="turners falls" if $x=="turner  falls"
replace $x="turners falls" if $x=="turner falls"
replace $x="turners falls" if $x=="turner fulls"
replace $x="waterville" if $x=="watervile"
replace $x="waterville" if $x=="watervilie"
replace $x="waterville" if $x=="watervllle"
replace $x="winchendon" if $x=="wincnendon"
replace $x="winchendon" if $x=="winehendon"
replace $x="winchendon" if $x=="wlnchendon"
replace $x="worcester" if $x=="wocester"
replace $x="worcester" if $x=="worcenter"
replace $x="worcester" if $x=="woreester"
replace $x="altoona" if $x=="altona"
replace $x="cambridge" if $x=="camridge"
replace $x="amesbury" if $x=="amesburg"
replace $x="amesbury" if $x=="amesdury"
replace $x="andover" if $x=="ancover"
replace $x="andover" if $x=="andove"
replace $x="archbald" if $x=="archbaid"
replace $x="archbald" if $x=="archbold"
replace $x="bakersfield" if $x=="bakersfleld"
replace $x="bakersfield" if $x=="bakerstield"
replace $x="bangor" if $x=="bango"
replace $x="bangor" if $x=="bangof"
replace $x="east bridgewater" if $x=="bast bridgewater"
replace $x="east bridgewater" if $x=="east bridge water"
replace $x="bath" if $x=="hath"
replace $x="bath" if $x=="rath"
replace $x="peabody" if $x=="beabody"
replace $x="peabody" if $x=="pea body"
replace $x="bryn mawr" if $x=="biyn mawr"
replace $x="bryn mawr" if $x=="bryn wawr"
replace $x="bloomfield" if $x=="bloomfleld"
replace $x="bloomfield" if $x=="bloomiield"
replace $x="roxbury" if $x=="boxbury"
replace $x="roxbury" if $x=="rosbury"
replace $x="greenfield" if $x=="breenfield"
replace $x="greenfield" if $x=="greefield"
replace $x="bridgeport" if $x=="bridge port"
replace $x="bridgeport" if $x=="bridgepor"
replace $x="burlington" if $x=="bulington"
replace $x="burlington" if $x=="burlinton"
replace $x="carlisle" if $x=="carlilse"
replace $x="carlisle" if $x=="carlise"
replace $x="catskill" if $x=="catekill"
replace $x="catskill" if $x=="cntskill"
replace $x="charleroi" if $x=="charlerol"
replace $x="charleroi" if $x=="charlroi"
replace $x="chicago" if $x=="chicngo"
replace $x="chicago" if $x=="chisago"
replace $x="chicopee falls" if $x=="chicopee fails"
replace $x="chicopee falls" if $x=="chieopee falls"
replace $x="coudersport" if $x=="couderaport"
replace $x="coudersport" if $x=="coudereport"
replace $x="easthampton" if $x=="east hampton"
replace $x="easthampton" if $x=="kasthampton"
replace $x="elizabethtown" if $x=="elizabeth town"
replace $x="elizabethtown" if $x=="elizabethrown"
replace $x="gardiner" if $x=="gardiuer"
replace $x="glens falls" if $x=="glen falls"
replace $x="glens falls" if $x=="glens palls"
replace $x="gothenburg" if $x=="gothenberg"
replace $x="great barrington" if $x=="great harrington"
replace $x="great barrington" if $x=="groat barrington"
replace $x="hanover" if $x=="honover"
replace $x="hanover" if $x=="hanove"
replace $x="haydenville" if $x=="haydensville"
replace $x="haydenville" if $x=="haydenvllle"
replace $x="holyoke" if $x=="holvoke"
replace $x="holyoke" if $x=="holyokc"
replace $x="lebanon" if $x=="iebanon"
replace $x="lebanon" if $x=="letanon"
replace $x="leominster" if $x=="ieominster"
replace $x="leominster" if $x=="leomister"
replace $x="kittanning" if $x=="kitpanning"
replace $x="kittanning" if $x=="kittannins"
replace $x="lakeville" if $x=="lakcville"
replace $x="lakeville" if $x=="lakevllle"
replace $x="lakewood" if $x=="lake wood"
replace $x="lakewood" if $x=="lnkewood"
replace $x="littlestown" if $x=="littletown"
replace $x="lykens" if $x=="lvkens"
replace $x="lykens" if $x=="lykena"
replace $x="mahanoy city" if $x=="mahoney city"
replace $x="mahanoy city" if $x=="mahonoy city"
replace $x="meadville" if $x=="meadvile"
replace $x="meadville" if $x=="meadvllle"
replace $x="meriden" if $x=="merideo"
replace $x="meriden" if $x=="merlden"
replace $x="tilton" if $x=="tllton"
replace $x="mount holly" if $x=="mount holl"
replace $x="mount holly" if $x=="mouny holly"
replace $x="mystic" if $x=="mybtic"
replace $x="mystic" if $x=="mysti"
replace $x="napa" if $x=="nap"
replace $x="napa" if $x=="nappa"
replace $x="natick" if $x=="natiek"
replace $x="natick" if $x=="natlck"
replace $x="new rochelle" if $x=="new rocbelle"
replace $x="new rochelle" if $x=="new roehelle"
replace $x="nyack" if $x=="nvack"
replace $x="nyack" if $x=="nyuck"
replace $x="oakland" if $x=="oaklann"
replace $x="oakland" if $x=="oaklnd"
replace $x="perth amboy" if $x=="perth am boy"
replace $x="perth amboy" if $x=="perth ambov"
replace $x="peterborough" if $x=="peterborou gh"
replace $x="peterborough" if $x=="peterdorough"
replace $x="phenix" if $x=="phenlx"
replace $x="phenix" if $x=="phoenix"
replace $x="phillips" if $x=="philips"
replace $x="phillips" if $x=="phillipst"
replace $x="pittsfield" if $x=="pittsdeld"
replace $x="pittsfield" if $x=="pittsheld"
replace $x="pittsfield" if $x=="pittsneld"
replace $x="quakertown" if $x=="quakertowa"
replace $x="quakertown" if $x=="quarkertown"
replace $x="royersford" if $x=="roversford"
replace $x="royersford" if $x=="royereford"
replace $x="suffield" if $x=="saffield"
replace $x="suffield" if $x=="suffleld"
replace $x="santa cruz" if $x=="sanpa cruz"
replace $x="santa cruz" if $x=="santa crus"
replace $x="skowhegan" if $x=="scowhegan"
replace $x="skowhegan" if $x=="showhegan"
replace $x="seneca falls" if $x=="seneca fall"
replace $x="seneca falls" if $x=="seneca palls"
replace $x="south braintree" if $x=="south brain tree"
replace $x="south braintree" if $x=="south bralntree"
replace $x="st clair" if $x=="st  clair"
replace $x="st clair" if $x=="stclair"
replace $x="st louis" if $x=="st  louis"
replace $x="st louis" if $x=="stlouis"
replace $x="st helena" if $x=="sthelen"
replace $x="st helena" if $x=="sthelena"
replace $x="stafford springs" if $x=="stafford sprins"
replace $x="stafford springs" if $x=="tafford springs"
replace $x="vineland" if $x=="viheland"
replace $x="vineland" if $x=="vlneland"
replace $x="wappinger falls" if $x=="wappingers falls"
replace $x="wappinger falls" if $x=="wapplngers falls"
replace $x="waterbury" if $x=="water bury"
replace $x="waterbury" if $x=="watferbury"
replace $x="wellfleet" if $x=="well fleet"
replace $x="wellfleet" if $x=="wellfieet"
replace $x="west chester" if $x=="west cheste"
replace $x="west chester" if $x=="westchester"
replace $x="west hoboken" if $x=="west hobken"
replace $x="west hoboken" if $x=="west hoobken"
replace $x="wickford" if $x=="wicksford"
replace $x="wickford" if $x=="wlckford"
replace $x="woodsville" if $x=="woedsville"
replace $x="woodsville" if $x=="woodsvllle"
replace $x="yarmouthport" if $x=="yarmouth port"
replace $x="yarmouthport" if $x=="yarmouthsport"
replace $x="calais" if $x=="alais"
replace $x="allentown" if $x=="alientown"
replace $x="jamaica" if $x=="amaica"
replace $x="amherst" if $x=="amberst"
replace $x="angels camp" if $x=="angel camp"
replace $x="avalon" if $x=="anion"
replace $x="annville" if $x=="annvilie"
replace $x="ansonia" if $x=="ansonla"
replace $x="augusta" if $x=="augusra"
replace $x="ayer" if $x=="aver"
replace $x="bayonne" if $x=="bavonne"
replace $x="beaver" if $x=="bedver"
replace $x="hartford" if $x=="bel air"
replace $x="hartford" if $x=="belair"
replace $x="bellevue" if $x=="bellcvue"
replace $x="belle vernon" if $x=="bellevernon"
replace $x="bethlehem" if $x=="methlehem"
replace $x="beverly" if $x=="beverley"
replace $x="biddeford" if $x=="blddeford"
replace $x="brewer" if $x=="brwer"
replace $x="brookline" if $x=="brookllne"
replace $x="camden" if $x=="camaen"
replace $x="carnegie" if $x=="carnegia"
replace $x="concord" if $x=="ccncord"
replace $x="centerville" if $x=="centervllle"
replace $x="centreville" if $x=="centrevllle"
replace $x="chester" if $x=="cheater"
replace $x="chicopee" if $x=="chlcopee"
replace $x="cincinnati" if $x=="cinncinnati"
replace $x="clarion" if $x=="claron"
replace $x="clearfield" if $x=="clearfielld"
replace $x="collinsville" if $x=="collingsville"
replace $x="coraopolis" if $x=="corapolis"
replace $x="dallas" if $x=="dalla"
replace $x="danielson" if $x=="danlelson"
replace $x="dedham" if $x=="dedbam"
replace $x="deep river" if $x=="deep riven"
replace $x="dillsburg" if $x=="dellsburg"
replace $x="dorchester" if $x=="dorrhester"
replace $x="dover" if $x=="hover"
replace $x="dravosburg" if $x=="dravoeburg"
replace $x="du bois" if $x=="dubois"
replace $x="dubuque" if $x=="dubuaue"
replace $x="east cambridge" if $x=="eastcambridge"
replace $x="east orange" if $x=="fast orange"
replace $x="east weymouth" if $x=="east weymourh"
replace $x="eastport" if $x=="kastport"
replace $x="edinburgh" if $x=="edinburg"
replace $x="elizabeth" if $x=="elisabeth"
replace $x="elizabethville" if $x=="elizabethvllle"
replace $x="ellwood" if $x=="ell wood"
replace $x="ellsworth" if $x=="ellswort"
replace $x="exeter" if $x=="exete"
replace $x="falls village" if $x=="fails village"
replace $x="fairhaven" if $x=="falrhaven"
replace $x="fort worth" if $x=="fort wort"
replace $x="pottstown" if $x=="fottstown"
replace $x="frankfort" if $x=="fran kfortonthemain"
replace $x="frankfort" if $x=="frankfortonthemain"
replace $x="frankfort" if $x=="fraukfortonmain"
replace $x="frankfort" if $x=="frankfortonmain"
replace $x="fredonia" if $x=="fredonla"
replace $x="gonzales" if $x=="ganzales"
replace $x="germantown" if $x=="german town"
replace $x="gettysburg" if $x=="gettyburg"
replace $x="gorham" if $x=="gorbam"
replace $x="hallowell" if $x=="hollowell"
replace $x="hammond" if $x=="hanmmond"
replace $x="hellam" if $x=="hellan"
replace $x="hillsborough bridge" if $x=="hillsborough bridgie"
replace $x="hoboken" if $x=="hobokcn"
replace $x="honesdale" if $x=="honesdaie"
replace $x="hopkinton" if $x=="hopklnton"
replace $x="hyde park" if $x=="hyde tark"
replace $x="indianapolis" if $x=="indianaipolis"
replace $x="jeannette" if $x=="jeanette"
replace $x="keene" if $x=="kenne"
replace $x="kennett square" if $x=="keunett square"
replace $x="kingfield" if $x=="kingfleld"
replace $x="kingston" if $x=="kington"
replace $x="lakeport" if $x=="laweport"
replace $x="lawrence" if $x=="laurence"
replace $x="lee" if $x=="leo"
replace $x="lewisburg" if $x=="lewis burg"
replace $x="litchfield" if $x=="litchfiield"
replace $x="lock haven" if $x=="loek haven"
replace $x="london/new york" if $x=="londonn ew york"
replace $x="london/new york" if $x=="londonnew york"
replace $x="long branch" if $x=="long"
replace $x="ione" if $x=="lone"
replace $x="long beach" if $x=="long  beach"
replace $x="lynn" if $x=="lvnn"
replace $x="mannheim" if $x=="manheim"
replace $x="marblehead" if $x=="marbleheaid"
replace $x="marysville" if $x=="marysvllle"
replace $x="matteawan" if $x=="mattewan"
replace $x="mcsherrystown" if $x=="mcisherrystown"
replace $x="merrimac" if $x=="merrlmac"
replace $x="millvale" if $x=="mill vale"
replace $x="mineola" if $x=="mincola"
replace $x="mt pleasant" if $x=="ml pleasant"
replace $x="monson" if $x=="monsou"
replace $x="mt vernon" if $x=="mtvernon"
replace $x="munich" if $x=="muuich"
replace $x="new york" if $x=="n y"
replace $x="new york" if $x=="ny"
replace $x="naugatuck" if $x=="naugatnek"
replace $x="naugatuck" if $x=="naugatoek"
replace $x="nevada city" if $x=="nevada citl"
replace $x="new britain" if $x=="new  britain"
replace $x="new orleans" if $x=="new  orleans"
replace $x="new bedford" if $x=="new betford"
replace $x="new brunswick" if $x=="new brnnswick"
replace $x="new castle" if $x=="newcastle"
replace $x="new london" if $x=="new loudon"
replace $x="new milford" if $x=="new mllford"
replace $x="norwell" if $x=="nor well"
replace $x="north brookfield" if $x=="north brookfleld"
replace $x="norwalk" if $x=="norwaik"
replace $x="norwich" if $x=="norwick"
replace $x="omaha" if $x=="omana"
replace $x="orange" if $x=="orauge"
replace $x="south weymouth" if $x=="outh weymouth"
replace $x="petaluma" if $x=="pepaluma"
replace $x="petersburg" if $x=="petersbur"
replace $x="philadelphia" if $x=="philadelphia p"
replace $x="philadelphia" if $x=="philadelphia pa"
replace $x="pirrston" if $x=="pirrsron"
replace $x="plymouth" if $x=="plvmouth"
replace $x="port chester" if $x=="portchester"
replace $x="punxsutawney" if $x=="punxsupawney"
replace $x="raleigh" if $x=="raleign"
replace $x="richmond" if $x=="ricmond"
replace $x="ridgefield" if $x=="ridgefleld"
replace $x="ridgewood" if $x=="rldgewood"
replace $x="riverhead" if $x=="riverbead"
replace $x="rockford" if $x=="roekford"
replace $x="roslyn" if $x=="roslyu"
replace $x="san dimas" if $x=="san dinas"
replace $x="san luis obispo" if $x=="san luis oblspo"
replace $x="sandy spring" if $x=="sandv spring"
replace $x="santa rosa" if $x=="santa  rosa"
replace $x="sebastopol" if $x=="sebastapol"
replace $x="smethport" if $x=="smithport"
replace $x="spencer" if $x=="soencer"
replace $x="somersworth" if $x=="som rsworth"
replace $x="southport" if $x=="sonthport"
replace $x="south paris" if $x=="south  paris"
replace $x="st marys" if $x=="st mary"
replace $x="st paul" if $x=="stpaul"
replace $x="stettin" if $x=="stetten"
replace $x="stoneham" if $x=="stonenam"
replace $x="stroudsburg" if $x=="stroudsburgh"
replace $x="tacony" if $x=="tacouy"
replace $x="tarrytown" if $x=="tarry town"
replace $x="thomaston" if $x=="thomastom"
replace $x="toronto" if $x=="toronyo"
replace $x="troy" if $x=="trov"
replace $x="ukiah" if $x=="uklah"
replace $x="uniontown" if $x=="union town"
replace $x="uxbridge" if $x=="uxbrldge"
replace $x="wallingford" if $x=="waliingford"
replace $x="walpole" if $x=="walpolc"
replace $x="boston" if $x=="ward"
replace $x="warren" if $x=="warrenv"
replace $x="watertown" if $x=="watcrtown"
replace $x="waynesboro" if $x=="waynewsboro"
replace $x="webster" if $x=="webstor"
replace $x="westminster" if $x=="wesminster"
replace $x="westport" if $x=="west port"
replace $x="westborough" if $x=="westborougb"
replace $x="white plains" if $x=="white plaina"
replace $x="whittier" if $x=="whithier"
replace $x="wilkinsburg" if $x=="wllkinsburg"
replace $x="williamstown" if $x=="williawstown"
replace $x="wilmington" if $x=="wilmiugton"
replace $x="windsor locks" if $x=="windsor lock"
replace $x="winsted" if $x=="winstead"
replace $x="woburn" if $x=="wohurn"
replace $x="woodland" if $x=="woodlaud"
replace $x="zurich" if $x=="zuric"
replace $x=strtrim($x)
replace $x=stritrim($x)


replace $x="albany" if $x=="alban"
replace $x="altoona" if $x=="altoomi"
replace $x="perth amboy" if $x=="amboy"
replace $x="bridgton" if $x=="b ridgton"
replace $x="bangor" if $x=="bangor me"
replace $x="bakersfield" if $x=="barkesfield"
replace $x="belmont" if $x=="beluiont"
replace $x="redding" if $x=="bidding"
replace $x="bridgton" if $x=="bndgton"
replace $x="boston" if $x=="botson"
replace $x="brawley" if $x=="brawby"
replace $x="new britain" if $x=="britain"
replace $x="bridgeport" if $x=="brldgepprt"
replace $x="camden" if $x=="cainden"
replace $x="calais" if $x=="calais me"
replace $x="calais" if $x=="calias"
replace $x="cambridge" if $x=="cambridgeport"
replace $x="canton" if $x=="cantoni"
replace $x="charlestown" if $x=="chariest own"
replace $x="chicago" if $x=="chi"
replace $x="chicopee" if $x=="chicoitee"
replace $x="chicopee" if $x=="chicoppo"
replace $x="clearfield" if $x=="clearneld"
replace $x="charleroi" if $x=="cliarleroi"
replace $x="gorham" if $x=="corhain"
replace $x="new haven" if $x=="court"
replace $x="scranton" if $x=="cranton"
replace $x="danvers" if $x=="da livers"
replace $x="danielson" if $x=="damelson"
replace $x="danbury" if $x=="danbunr"
replace $x="dedham" if $x=="dedharn"
replace $x="doylestown" if $x=="doy lest own"
replace $x="dunmore" if $x=="duninore"
replace $x="edinburgh" if $x=="edlngurgh"
replace $x="fairfield" if $x=="fairneld"
replace $x="farmington" if $x=="fannington"
replace $x="farmington" if $x=="farniington"
replace $x="farmington" if $x=="farralngton"
replace $x="fitchburg" if $x=="fitehliurg"
replace $x="edinburgh" if $x=="fiuburgh"
replace $x="folsom" if $x=="folsoin"
replace $x="farmington" if $x=="framington"
replace $x="gorham" if $x=="gorharn"
replace $x="grafton" if $x=="gra&on"
replace $x="guilford" if $x=="gudford"
replace $x="harrison" if $x=="hanison"
replace $x="sag harbor" if $x=="harbor"
replace $x="harrisburg" if $x=="harnsburg"
replace $x="hartford" if $x=="hartford c"
replace $x="hartford" if $x=="hartford conn"
replace $x="hartford" if $x=="hatrrord"
replace $x="hallowell" if $x=="hauowell"
replace $x="hallowell" if $x=="hauoweu"
replace $x="hazleton" if $x=="hazelton"
replace $x="houlton" if $x=="hazoulton"
replace $x="reading" if $x=="hearting"
replace $x="hillsborough" if $x=="hillsboro"
replace $x="hartford" if $x=="hnrtforrt"
replace $x="hollister" if $x=="hoillster"
replace $x="houlton" if $x=="hotilton"
replace $x="hanover" if $x=="ilanover"
replace $x="hartford" if $x=="ilartford"
replace $x="salem" if $x=="in salem"
replace $x="ipswich" if $x=="ipswloh"
replace $x="jersey city" if $x=="jersey"
replace $x="laconia" if $x=="lacoma"
replace $x="lancaster" if $x=="lanacster"
replace $x="lancaster" if $x=="lancaster pa"
replace $x="lewiston" if $x=="levriston"
replace $x="lewiston" if $x=="lewiston me"
replace $x="littlestown" if $x=="littlesotwn"
replace $x="roslyn" if $x=="ltoslvn"
replace $x="ludlow" if $x=="luldow"
replace $x="machias" if $x=="machais"
replace $x="meriden" if $x=="me riden"
replace $x="mercer" if $x=="mercer pa"
replace $x="mercer" if $x=="mercer pa"
replace $x="middletown" if $x=="middletuck"
replace $x="mount vernon" if $x=="mt vernon"
replace $x="nevada city" if $x=="nevada"
replace $x="newburgh" if $x=="nevvburgh"
replace $x="new york" if $x=="new icork"
replace $x="new york" if $x=="new york city"
replace $x="new york" if $x=="new york n"
replace $x="new york" if $x=="new york n y"
replace $x="newburgh" if $x=="newbunrh"
replace $x="newburyport" if $x=="newbury"
replace $x="newburgh" if $x=="newliurgh"
replace $x="norristown" if $x=="nor ristown"
replace $x="norristown" if $x=="nornstown"
replace $x="pittsburgh" if $x=="nttaburgh"
replace $x="san luis obispo" if $x=="obispo"
replace $x="hartford" if $x=="of hartford"
replace $x="new york" if $x=="of new york"
replace $x="pittston" if $x=="of pittston"
replace $x="reading" if $x=="of reading"
replace $x="rochester" if $x=="of rochester"
replace $x="ontario" if $x=="ont"
replace $x="outerville" if $x=="outervllle"
replace $x="williamsport" if $x=="p williamsport"
replace $x="paris" if $x=="pa ris"
replace $x="palmer" if $x=="painter"
replace $x="paris" if $x=="pans"
replace $x="pawling" if $x=="pawhug"
replace $x="plainfield" if $x=="plainneld"
replace $x="pottsville" if $x=="pottsville pa"
replace $x="pittsburgh" if $x=="ptitsburgh"
replace $x="rakersfield" if $x=="rakersfied"
replace $x="reading" if $x=="readiftg"
replace $x="reading" if $x=="reading pa"
replace $x="reading" if $x=="readlug"
replace $x="reading" if $x=="residing"
replace $x="rockville" if $x=="rocfcville"
replace $x="rock island" if $x=="rock"
replace $x="rock island" if $x=="rock"
replace $x="rockville" if $x=="rockviue"
replace $x="rochester" if $x=="roenester"
replace $x="roxbury" if $x=="roxbunr"
replace $x="new york" if $x=="s� new york"
replace $x="new york" if $x=="savoy"
replace $x="saco" if $x=="saw"
replace $x="sharpsburg" if $x=="sliarpsburg"
replace $x="greenville" if $x=="smithville"
replace $x="manchester" if $x=="so manchester"
replace $x="south paris" if $x=="so paris"
replace $x="adams" if $x=="south adams"
replace $x="south paris" if $x=="south pa ris"
replace $x="south paris" if $x=="south pans"
replace $x="south paris" if $x=="south purls"
replace $x="springfield" if $x=="spring meld"
replace $x="stafford springs" if $x=="springs"
replace $x="east boston" if $x=="sumner"
replace $x="annville" if $x=="sunville"
replace $x="south paris" if $x=="suoth paris"
replace $x="tarrytown" if $x=="tanytown"
replace $x="tacony" if $x=="tawny"
replace $x="london" if $x=="tendon"
replace $x="mount vernon" if $x=="vernon"
replace $x="vineland" if $x=="vine] land"
replace $x="vineland" if $x=="vineyard"
replace $x="waltham" if $x=="vvaltham"
replace $x="watertown" if $x=="watertonw"
replace $x="waterville" if $x=="watervillefi"
replace $x="westfield" if $x=="westneld"
replace $x="wheeling" if $x=="wheeling w"
replace $x="wickford" if $x=="wickfo"
replace $x="williamsport" if $x=="williamson"
replace $x="williamsport" if $x=="williamson"
replace $x="williamsport" if $x=="willlainsport"
replace $x="wilmington" if $x=="wilming"
replace $x="winchester" if $x=="wmchester"
replace $x="windber" if $x=="wmdber"
replace $x="zurich" if $x=="zu rich"
replace $x="binghamton" if $x=="bingham"
replace $x="hingham" if $x=="hinghain"
replace $x="hingham" if $x=="hingliam"
replace $x="hingham" if $x=="ilingham"
replace $x="philadelphia" if $x=="of philadelphia"
replace $x="philadelphia" if $x=="philadelp"
replace $x="philadelphia" if $x=="philadeuni"
replace $x="philadelphia" if $x=="piladelpbla"
replace $x="philadelphia" if $x=="pliiladelphia"
replace $x="philadelphia" if $x=="the philadelphia"
replace $x="cambridge" if $x=="camb ridge"
replace $x="cambridge" if $x=="cambndge"
replace $x="cambridge" if $x=="cambria"
replace $x="fall river" if $x=="fau river"
replace $x="fall river" if $x=="fidl river"
replace $x="toms river" if $x=="tours river"
replace $x="yarmouthport" if $x=="yarmouth"
replace $x="greenfield" if $x=="oreenfleld"
replace $x="easthampton" if $x=="easthainpton"
replace $x="easthampton" if $x=="eastharapton"
replace $x="northampton" if $x=="northamoion"
replace $x="san francisco" if $x=="san fraiuisco"
replace $x="san francisco" if $x=="san franc"
replace $x="san francisco" if $x=="san fransico"
replace $x="san francisco" if $x=="sim francisco"
replace $x="hoboken" if $x=="hobofcen"
replace $x="hoboken" if $x=="holioken"
replace $x="pittsfield" if $x=="pittsefild"
replace $x="pittsfield" if $x=="pittsfiled"
replace $x="montclair" if $x=="montdalr"
replace $x="mount carmel" if $x=="mount carrael"
replace $x="mount carmel" if $x=="mt carmel"
replace $x="mount carmel" if $x=="mt carrael"
replace $x="mt pleasant" if $x=="mount pleasant"
replace $x="mt pleasant" if $x=="pleasant"
replace $x="mannheim" if $x=="man nheim"
replace $x="bridgewater" if $x=="b ridgewater"
replace $x="fishkillonhudson" if $x=="fishkilloniiudson"
replace $x="fishkillonhudson" if $x=="fishkillonthehudson"
replace $x="hyde park" if $x=="hyde bank"
replace $x="peterborough" if $x=="ieterliorough"
replace $x="peterborough" if $x=="peterborough n"
replace $x="long beach" if $x=="lorig beach"
replace $x="monongahela" if $x=="monogabela"
replace $x="monongahela" if $x=="mononcrahela"
replace $x="pawtucket" if $x=="pavvtucket"
replace $x="north easton" if $x=="north huston"
replace $x="san luis obispo" if $x=="san luis"
replace $x="st louis" if $x=="st loiuse"
replace $x="skowhegan" if $x=="skowheagn"
replace $x="skowhegan" if $x=="skowhejpn"
replace $x="aixlachapelle" if $x=="aixlachanell"
replace $x="angels camp" if $x=="angles camp"
replace $x="apollo" if $x=="apouo"
replace $x="baltimore" if $x=="baltimore md"
replace $x="belle vernon" if $x=="bellevemon"
replace $x="east orange" if $x=="blast orange"
replace $x="chicopee falls" if $x=="ohiropee falls"
replace $x="cincinnati" if $x=="cincinatti"
replace $x="cornwallonhudson" if $x=="cornwallonthehudson"
replace $x="east bridgewater" if $x=="east bridgexvater"
replace $x="east jaffrey" if $x=="fist jaffrpy"
replace $x="elizabethville" if $x=="euzabethville"
replace $x="franklin" if $x=="fbanklin"
replace $x="fort worth" if $x=="ft worth"
replace $x="hamburg/new york" if $x=="hamburg new york"
replace $x="hamburg/new york" if $x=="hamburgnew york"
replace $x="haverhill" if $x=="haverbil"
replace $x="jenkintown" if $x=="jenktutown"
replace $x="kennebunk" if $x=="kennebec"
replace $x="kittanning" if $x=="klttannlng"
replace $x="london and edinburgh" if $x=="london & edinburgh"
replace $x="london" if $x=="ltd london"
replace $x="lyndonville" if $x=="lyondville"
replace $x="mahoning city" if $x=="malioning city"
replace $x="mcsherrystown" if $x=="mcshcrrytown"
replace $x="middleborough" if $x=="middelborough"
replace $x="mifflinburg" if $x=="miffiingburg"
replace $x="mount holly" if $x=="mt holly"
replace $x="newton centre" if $x=="newton center"
replace $x="north attleborough" if $x=="north attleboro"
replace $x="north brookfield" if $x=="north brookneld"
replace $x="norwalk" if $x=="norwalk conn"
replace $x="norwich" if $x=="norwich conn"
replace $x="wilkes barre" if $x=="of wilkesbarre"
replace $x="wilkes barre" if $x=="the wilkesbarre"
replace $x="poughkeepsie" if $x=="pouchkoepsie"
replace $x="providence" if $x=="providence r"
replace $x="punxsutawney" if $x=="punsntawney"
replace $x="salmon falls" if $x=="salmon faus"
replace $x="south framingham" if $x=="south franjingham"
replace $x="southbridge" if $x=="southliridge"
replace $x="st gall" if $x=="stjail"
replace $x="vandergrift" if $x=="vandergri&"
replace $x="wappinger falls" if $x=="wappinger fail"
replace $x="west newton" if $x=="west nejvton"
replace $x="west new brighton" if $x=="west new b righton"
replace $x="westborough" if $x=="westliorougb"
replace $x="wilkes barre" if $x=="wukesbarre"
replace $x="woonsocket" if $x=="woonscoekt"

replace $x=strtrim($x)
replace $x=stritrim($x)

replace $x="albany" if $x=="alleghany" & invname_hold_orig=="Dutchess Insurance Company."
replace $x="toronto" if $x=="toronto ont"
replace $x="troy" if $x=="troy troy"
replace $x="new london" if $x=="new london conn"
replace $x="pittsburgh" if $x=="pittsburgh pa"
replace $x="falls village" if $x=="falls village conn"
replace $x="south norwalk" if $x=="south norwalk conn"
replace $x="portsmouth" if $x=="portsmouth n h"
replace $x="new bedford" if $x=="new bedford mass"
replace $x="springfield" if $x=="springfield mass"
replace $x="gothenburg" if $x=="gothenburg sweden"
replace $x="east boston" if $x=="east roston"
replace $x="rochester" if $x=="rochester n y"
replace $x="pawtucket" if $x=="pawtucket r i"
replace $x="east boston" if $x=="east roston"
replace $x="northampton" if $x=="northampton mass"
replace $x="pittsfield" if $x=="pittsfield mass"
replace $x="kingston" if $x=="kingston r i"
replace $x="stockton" if $x=="stockton cal"
replace $x="pasadena" if $x=="pasadena cal"
replace $x="syracuse" if $x=="syracuse n y"
replace $x="brooklyn" if $x=="brooklyn n y"
replace $x="worcester" if $x=="worcester mass"
replace $x="buffalo" if $x=="buffalo n y"
replace $x="concord" if $x=="concord n h"
replace $x="millbury" if $x=="millbury mass"
replace $x="newark" if $x=="newark n j"
replace $x="newman" if $x=="newman cal"
replace $x="santa maria" if $x=="sanpa maria cal"
replace $x="danbury" if $x=="danbury conn"
replace $x="gardner" if $x=="gardner mass"
replace $x="clinton" if $x=="clinton mass"
replace $x="providence" if $x=="r i providence"
replace $x="boston" if $x=="boston mass"
replace $x="edinburgh/hartford" if $x=="edinburghhartford"
replace $x="niagara falls" if $x=="niagara"
replace $x="newburyport" if $x=="newburyport & vicinity"
replace $x="frankfort on main" if $x=="frankfortonthemalu"
replace $x="bridgeport" if $x=="conn bridgeport"
replace $x="newburgh" if $x=="the newburgh"
replace $x="perth" if $x=="perth scot"
replace $x="athol" if $x=="athol mass"
replace $x="new haven" if $x=="haven new"
replace $x="carbondale" if $x=="bk carbondale"
replace $x="frankfort on main" if $x=="frankfort on the main"

replace $x=strtrim($x)
replace $x=stritrim($x)

replace $x="morgan hill" if $x=="morgan"
replace $x="bakersfield" if $x=="rakersfield"
replace $x="red bluff" if $x=="red bluff cadinro"
replace $x="redondo beach" if $x=="rodondo"
replace $x="salinas" if $x=="salinas city"
replace $x="san jose" if $x=="san jose cal"
replace $x="south san francisco" if $x=="south francisco"
replace $x="berkeley" if $x=="west berkeley"
replace $x="putnam" if $x=="bank putnam"
replace $x="lewiston" if $x=="savings bank lewiston"
replace $x="bel air" if $x=="md bel air"
replace $x="new york" if $x=="of the city of new york"
replace $x="erie" if $x=="bank erie"
replace $x="wilkes barre" if $x=="bank of wilkesbarre"
replace $x="carbondale" if $x=="bk carbondale"
replace $x="brackenridge" if $x=="brackenbridge"
replace $x="philadelphia" if $x=="guarantee & trust company the philadelphia"
replace $x="homestead" if $x=="homestead"
replace $x="pittsburgh" if $x=="httsfcurga"
replace $x="philadelphia" if $x=="pbtlndoirm"
replace $x="philadelphia" if $x=="phllodplpbia"
replace $x="philadelphia" if $x=="safe deposit & insurance co philadelphia"
replace $x="olyphant" if $x=="the olympant"
replace $x="philadelphia" if $x=="title & savings company philadelphia"
replace $x="wilkes barre" if $x=="wllkesenrre"
replace $x="perth/philadephia" if $x=="perthphiladephia"
replace investor_state_temp=subinstr(investor_state_temp,"england","england & scotland",.) if investor_city_temp=="london & aberdenn"
replace $x="london" if $x=="ltd" & strpos(investor_state_temp,"england") & invname_hold_orig=="Palatine Insurance Company"
replace investor_state_temp=subinstr(investor_state_temp,"pennsylvania","iowa",.) if $x=="des moines"
replace $x="erie" if $x=="fine" & strpos(investor_state_temp,"pennsylvania") & invname_hold_orig=="People's Bank"
replace $x="jenkintown" if $x=="jerusalem" & strpos(investor_state_temp,"pennsylvania") //& invname_hold_orig=="People's Bank"
replace $x="philadelphia" if $x=="safe deposit & insurance co" & strpos(investor_state_temp,"pennsylvania") & invname_hold_orig=="Philadelphia Trust"
replace $x="munich/new york" if $x=="munichnew york"
replace $x="spain/new york" if $x=="spainyork" & investor_state_temp=="new york"
replace $x="pittsburgh" if $x=="warren pittsburgh"
replace $x="new york" if $x=="s new york"

replace investor_city_1="hartford" if invname_hold_orig=="Aetna Life Insurance Company. Hartford" & book_year_hold==1908 & cname_hold_temp=="central of georgia"
replace investor_city_1="kittanning" if invname_hold_orig=="Armstrong County Trust Company. Kittanning" & book_year_hold==1913 & cname_hold_temp=="st louis and san francisco"
replace investor_city_1="baltimore" if invname_hold_orig=="Baltimore Life Insurance Company of Baltimore" & book_year_hold==1913 & cname_hold_temp=="pennsylvania railroad"
replace investor_city_1="bath" if invname_hold_orig=="Bath Savings Bank" & book_year_hold==1911 & cname_hold_temp=="brunswick electric light and power"
replace investor_city_1="berkshire" if invname_hold_orig=="Berkshire Life Insurance Company" & book_year_hold==1908 & cname_hold_temp=="chicago and northwestern"
replace investor_city_1="boston" if invname_hold_orig=="Brighton Five Cents Savings Bank (Ward 25)" & book_year_hold==1908 & cname_hold_temp=="chicago burlington and quincy"
replace investor_city_1="boston" if invname_hold_orig=="Brighton Five Cents Savings Bank (Ward 25) Boston" & book_year_hold==1908 & cname_hold_temp=="denter and piscataquis"
replace investor_city_1="brookline" if invname_hold_orig=="Brookline Savings Bank. Brookline" & book_year_hold==1908 & cname_hold_temp=="west end street"
replace investor_city_1="buxton" if invname_hold_orig=="Buxton and Hollis Savings Bank. Buxton" & book_year_hold==1908 & cname_hold_temp=="mousam river"
replace investor_city_1="boston" if invname_hold_orig=="Charlestown Five Cents Savings Bank. Boston" & book_year_hold==1908 & cname_hold_temp=="concord and claremont"
replace investor_city_1="freeland" if invname_hold_orig=="Citizens Bank of Freeland" & book_year_hold==1911 & cname_hold_temp=="o gara coal"
replace investor_city_1="new york" if invname_hold_orig=="Commonwealth Insurance Company. New York" & book_year_hold==1908 & cname_hold_temp=="kansas city st louis and chicago"
replace investor_city_1="new haven" if invname_hold_orig=="Connecticut Savings Bank" & book_year_hold==1908 & cname_hold_temp=="united new jersey railroad and canal"
replace investor_city_1="new york" if invname_hold_orig=="Continental Insurance Company. New York City" & book_year_hold==1908 & cname_hold_temp=="columbia and greenville"
replace investor_city_1="danvers" if invname_hold_orig=="Danvers Savings Bank. Danvers" & book_year_hold==1911 & cname_hold_temp=="new york new haven and hartford"
replace investor_city_1="hanover" if invname_hold_orig=="Dartmouth Savings Bank. Hanover" & book_year_hold==1913 & cname_hold_temp=="oregon short line"
replace investor_city_1="chester" if invname_hold_orig=="Delaware County Trust" & book_year_hold==1908 & cname_hold_temp=="kanawha valley traction"
replace investor_city_1="chester" if invname_hold_orig=="Delaware County Trust,Safe Deposit & Title Insurance Company" & book_year_hold==1911 & cname_hold_temp=="gogebic service"
replace investor_city_1="eastport" if invname_hold_orig=="Eastport Savings Bank. Eastport" & book_year_hold==1913 & cname_hold_temp=="boston and worcester street"
replace investor_city_1="boston" if invname_hold_orig=="Eliot Five Cents Savings Bank. Boston" & book_year_hold==1908 & cname_hold_temp=="west end street"
replace investor_city_1="new york" if invname_hold_orig=="Equitable Life Assurance Society of the U" & book_year_hold==1911 & cname_hold_temp=="chicago milwaukee and st paul"
replace investor_city_1="norwalk" if invname_hold_orig=="Fairfield County Savings Bank. Norwalk" & book_year_hold==1913 & cname_hold_temp=="chicago rock island and pacific railway"
replace investor_city_1="fall river" if invname_hold_orig=="Fall River Five Cents Savins� Bank. Fall River" & book_year_hold==1913 & cname_hold_temp=="northwestern union"
replace investor_city_1="middletown" if invname_hold_orig=="Farmers' Bank of Middletown" & book_year_hold==1913 & cname_hold_temp=="pennsylvania railroad"
replace investor_city_1="middletown" if invname_hold_orig=="Farmers' Bank of Middletown" & book_year_hold==1911 & cname_hold_temp=="hudson and manhattan"
replace investor_city_1="middletown" if invname_hold_orig=="Farmers' Bank of Middletown" & book_year_hold==1911 & cname_hold_temp=="chicago and alton railroad"
replace investor_city_1="wilmington" if invname_hold_orig=="Farmers' Mutual Fire Insurance Company of the State of Delaware" & book_year_hold==1908 & cname_hold_temp=="hocking valley"
replace investor_city_1="farmington" if invname_hold_orig=="Farmlngton Savings Bank. Farmington" & book_year_hold==1908 & cname_hold_temp=="louisville and nashville"
replace investor_city_1="philadelphia" if invname_hold_orig=="Frankford Trust Company. Philadelphia" & book_year_hold==1911 & cname_hold_temp=="central normal school association"
replace investor_city_1="wheeling" if invname_hold_orig=="Franklin Fire Insurance Company of Wheeling" & book_year_hold==1908 & cname_hold_temp=="toledo and ohio central"
replace investor_city_1="philadelphia" if invname_hold_orig=="Franklin Fire Insurance Company. Philadelphia" & book_year_hold==1913 & cname_hold_temp=="pennsylvania"
replace investor_city_1="perth/philadelphia" if invname_hold_orig=="General Accident" & book_year_hold==1913 & cname_hold_temp=="pennsylvania railroad"
replace investor_city_1="perth/philadelphia" if invname_hold_orig=="General Accident. Fire & Life Assur. Corp.. Ltd.. Perth" & book_year_hold==1911 & cname_hold_temp=="american telephone and telegraph"
replace investor_city_1="new york" if invname_hold_orig=="Guaranty Trust Company" & book_year_hold==1911 & cname_hold_temp=="american smelters securities"
replace investor_city_1="new york" if invname_hold_orig=="Guaranty Trust Company. New York" & book_year_hold==1911 & cname_hold_temp=="chicago and alton railroad"
replace investor_city_1="holyoke" if invname_hold_orig=="Hoi yoke Mutual Fire Insurance Company in Salem" & book_year_hold==1908 & cname_hold_temp=="erie railroad"
replace investor_city_1="holyoke" if invname_hold_orig=="Holyoke Mutual Fire Insurance Company in Salem" & book_year_hold==1908 & cname_hold_temp=="fitchburg railroad"
replace investor_city_1="holyoke" if invname_hold_orig=="Holyoke Savings Bank. Holyoke" & book_year_hold==1908 & cname_hold_temp=="chicago and northwestern"
replace investor_city_1="north adams" if invname_hold_orig=="Hoosac Savings Bank. North Adams" & book_year_hold==1908 & cname_hold_temp=="chicago burlington and quincy"
replace investor_city_1="philadelphia" if invname_hold_orig=="Industrial Trust" & book_year_hold==1908 & cname_hold_temp=="chicago rock island and pacific railway"
replace investor_city_1="philadelphia" if invname_hold_orig=="Industrial Trust, Title A Savings Company" & book_year_hold==1913 & cname_hold_temp=="philadelphia and willow grove street"
replace investor_city_1="philadelphia" if invname_hold_orig=="Insurance Company of the State of Pa." & book_year_hold==1913 & cname_hold_temp=="atchison topeka and santa fe"
replace investor_city_1="suffolk" if invname_hold_orig=="Interstate Fire Insurance Company" & book_year_hold==1908 & cname_hold_temp=="southern railway"
replace investor_city_1="suffolk" if invname_hold_orig=="Interstate Fire Insurance Company" & book_year_hold==1908 & cname_hold_temp=="southern railway"
replace investor_city_1="napa" if invname_hold_orig=="James H. Goodman & Co." & book_year_hold==1913 & cname_hold_temp=="finnell land"
replace investor_city_1="jenkintown" if invname_hold_orig=="Jenkintown Trust Company" & book_year_hold==1911 & cname_hold_temp=="bethlehem steel"
replace investor_city_1="philadelphia" if invname_hold_orig=="Land Title & Trust Company. Philadelphia" & book_year_hold==1908 & cname_hold_temp=="coal river"
replace investor_city_1="lewisburg" if invname_hold_orig=="Lewisburg Trust & Safe Deposit Company. Lewisburg" & book_year_hold==1908 & cname_hold_temp=="lehigh valley railroad"
replace investor_city_1="richmond" if invname_hold_orig=="Life Insurance Company of Virginia." & book_year_hold==1908 & cname_hold_temp=="commonwealth power"
replace investor_city_1="new york" if invname_hold_orig=="Lincoln Trust Company" & book_year_hold==1911 & cname_hold_temp=="atlantic coast line"
replace investor_city_1="lowell" if invname_hold_orig=="Lowell Mutual Fire Insurance Company of Lowell" & book_year_hold==1911 & cname_hold_temp=="fitchburg railroad"
replace investor_city_1="lowell" if invname_hold_orig=="Lowell Mutual Fire Insurance Company of Lowell" & book_year_hold==1908 & cname_hold_temp=="fitchburg railroad"
replace investor_city_1="portland" if invname_hold_orig=="Maine Savings Bank. Portland" & book_year_hold==1913 & cname_hold_temp=="boston and worcester street"
replace investor_city_1="new york" if invname_hold_orig=="Manhattan Trust Company" & book_year_hold==1911 & cname_hold_temp=="casualty of america (new york new york)"
replace investor_city_1="providence" if invname_hold_orig=="Manufacturers' Mutual Fire Insurance Company of Providence" & book_year_hold==1908 & cname_hold_temp=="great northern"
replace investor_city_1="marlborough" if invname_hold_orig=="Mariborough,Savings Bank" & book_year_hold==1908 & cname_hold_temp=="fitchburg railroad"
replace investor_city_1="springfield" if invname_hold_orig=="Massachusetts Mutual Life Insurance Company Springfield" & book_year_hold==1911 & cname_hold_temp=="georgia midland"
replace investor_city_1="bridgeport" if invname_hold_orig=="Mechanics & Farmers' Savings Bank of Bridgeport" & book_year_hold==1908 & cname_hold_temp=="eastern railway of minnesota"
replace investor_city_1="bridgeport" if invname_hold_orig=="Mechanics & Farmers' Savings Bank of Bridgeport" & book_year_hold==1908 & cname_hold_temp=="genesee and wyoming"
replace investor_city_1="hartford" if invname_hold_orig=="Mechanics' Savings Bank" & book_year_hold==1908 & cname_hold_temp=="burlington cedar rapids and northern"
replace investor_city_1="greensburg" if invname_hold_orig=="Merchants' Trust Company of Greensburg" & book_year_hold==1911 & cname_hold_temp=="pryor coal"
replace investor_city_1="milford" if invname_hold_orig=="Milford Savings Bank. Milford" & book_year_hold==1913 & cname_hold_temp=="boston and albany"
replace investor_city_1="alton" if invname_hold_orig=="Millers' Mutual Fire Ins, Association of Ill.inois" & book_year_hold==1911 & cname_hold_temp=="south side elevated"
replace investor_city_1="wilkes barre" if invname_hold_orig=="Miners' Savings Bank of Wilkes-Barre" & book_year_hold==1908 & cname_hold_temp=="elgin joliet and eastern"
replace investor_city_1="munich/new york" if invname_hold_orig=="Munich Reinsurance Co" & book_year_hold==1911 & cname_hold_temp=="hocking valley"
replace investor_city_1="munich/new york" if invname_hold_orig=="Munich Re-insurance Co" & book_year_hold==1911 & cname_hold_temp=="fort worth and rio grande"
replace investor_city_1="munich/new york" if invname_hold_orig=="Munich Re-insurance Co" & book_year_hold==1911 & cname_hold_temp=="chicago rock island and pacific railroad"
replace investor_city_1="philadelphia" if invname_hold_orig=="Mutual Assurance Company for Insuring Houses from Loss by Fire" & book_year_hold==1913 & cname_hold_temp=="lehigh valley railroad"
replace investor_city_1="waterloo" if invname_hold_orig=="Mutual Life Assurance Company of Canada" & book_year_hold==1911 & cname_hold_temp=="winnipeg electric railway"
replace investor_city_1="hartford" if invname_hold_orig=="National Fire Insurance Company of Hartford" & book_year_hold==1913 & cname_hold_temp=="boston and albany"
replace investor_city_1="hartford" if invname_hold_orig=="National Fire Insurance Company of Hartford" & book_year_hold==1913 & cname_hold_temp=="boston and albany"
replace investor_city_1="new haven" if invname_hold_orig=="National Savings Bank of New Haven" & book_year_hold==1908 & cname_hold_temp=="eastern railway of minnesota"
replace investor_city_1="new haven" if invname_hold_orig=="National Savings Bank of New Haven" & book_year_hold==1908 & cname_hold_temp=="illinois central"
replace investor_city_1="nevada city" if invname_hold_orig=="Nevada County Bank (Agency of) Nevada City" & book_year_hold==1908 & cname_hold_temp=="nevada union building association"
replace investor_city_1="london/new york" if invname_hold_orig=="North British & merc. Ins. Co  London" & book_year_hold==1911 & cname_hold_temp=="southern railway"
replace investor_city_1="philadelphia" if invname_hold_orig=="Northw.este.cn" & book_year_hold==1911 & cname_hold_temp=="missouri pacific"
replace investor_city_1="olyphant" if invname_hold_orig=="Olyphant Bank. Olyphant" & book_year_hold==1911 & cname_hold_temp=="central pacific"
replace investor_city_1="englewood" if invname_hold_orig=="Palisades Trust & Guarantee Company" & book_year_hold==1913 & cname_hold_temp=="illinois central"
replace investor_city_1="philadelphia" if invname_hold_orig=="Pennsylvania Fire Insurance Company" & book_year_hold==1911 & cname_hold_temp=="chicago and alton railroad"
replace investor_city_1="wilkes barre" if invname_hold_orig=="PeopIe&^Eank />�-" & book_year_hold==1911 & cname_hold_temp=="missouri pacific"
replace investor_city_1="erie" if invname_hold_orig=="People's Bank of Erie" & book_year_hold==1908 & cname_hold_temp=="detroit toledo and ironton"
replace investor_city_1="wilkes barre" if invname_hold_orig=="People's Bank of Wilkes-Barre" & book_year_hold==1908 & cname_hold_temp=="elgin joliet and eastern"
replace investor_city_1="pittston" if invname_hold_orig=="People's Savings Bank of Pittston" & book_year_hold==1908 & cname_hold_temp=="erie railroad"
replace investor_city_1="philadelphia" if invname_hold_orig=="Philadelphia Savings Fund Society of Philadelphia" & book_year_hold==1908 & cname_hold_temp=="harrisburg portsmouth montana joy and lancaster"
replace investor_city_1="london/new york" if invname_hold_orig=="Phoenix Assurance Co.  Ltd. Of London" & book_year_hold==1913 & cname_hold_temp=="new york telephone"
replace investor_city_1="dover" if invname_hold_orig=="Piscataquis Cents Savings Bank" & book_year_hold==1908 & cname_hold_temp=="richmond national bank richmond maine"
replace investor_city_1="providence" if invname_hold_orig=="Providence" & book_year_hold==1913 & cname_hold_temp=="northern pacific"
replace investor_city_1="philadelphia" if invname_hold_orig=="Provident Life Trust Company. Philadelphia" & book_year_hold==1908 & cname_hold_temp=="lehigh valley railroad"
replace investor_city_1="new york" if invname_hold_orig=="Provident Savings Life Assurance Society. New York" & book_year_hold==1908 & cname_hold_temp=="canadian northern"
replace investor_city_1="newark" if invname_hold_orig=="Prudential Insurance Company of America" & book_year_hold==1908 & cname_hold_temp=="east tennessee virginia and georgia"
replace investor_city_1="providence" if invname_hold_orig=="Rhode Island Hospital Trust Company Providence" & book_year_hold==1911 & cname_hold_temp=="chicago telephone"
replace investor_city_1="providence" if invname_hold_orig=="Rhode Island Hospital Trust Company. Providence" & book_year_hold==1908 & cname_hold_temp=="keokuk and des moines"
replace investor_city_1="salmon falls" if invname_hold_orig=="Rollinsford Savings Bank. Salmon Falls" & book_year_hold==1908 & cname_hold_temp=="decatur water (alabama)"
replace investor_city_1="pottsville" if invname_hold_orig=="Safe Deposit Bank of Pottsville" & book_year_hold==1911 & cname_hold_temp=="hudson and manhattan"
replace investor_city_1="ansonia" if invname_hold_orig=="Savings Bank of Ansonia" & book_year_hold==1908 & cname_hold_temp=="detroit and bay city"
replace investor_city_1="danbury" if invname_hold_orig=="Savings Bank of Danbury" & book_year_hold==1908 & cname_hold_temp=="eastern railway of minnesota"
replace investor_city_1="danbury" if invname_hold_orig=="Savings Bank of Danbury" & book_year_hold==1908 & cname_hold_temp=="george creek and cumberland"
replace investor_city_1="danbury" if invname_hold_orig=="Savings Bank of Danbury" & book_year_hold==1911 & cname_hold_temp=="chicago and indiana coal"
replace investor_city_1="binghamton" if invname_hold_orig=="Security Muruai NiLfeai^ujcao.ce~Cot!(pacy" & book_year_hold==1911 & cname_hold_temp=="missouri pacific"
replace investor_city_1="south boston" if invname_hold_orig=="South Boston Savings Bank South Boston" & book_year_hold==1908 & cname_hold_temp=="cleveland and pittsburgh"
replace investor_city_1="south weymouth" if invname_hold_orig=="South Weymouth Savings Bank" & book_year_hold==1908 & cname_hold_temp=="chicago burlington and quincy"
replace investor_city_1="south weymouth" if invname_hold_orig=="South Weymouth Savings Bank South Weymouth" & book_year_hold==1908 & cname_hold_temp=="west end street"
replace investor_city_1="london/new york" if invname_hold_orig=="Sun Insurance Office. London" & book_year_hold==1913 & cname_hold_temp=="kansas city southern"
replace investor_city_1="troy" if invname_hold_orig=="Troy Trust Company" & book_year_hold==1911 & cname_hold_temp=="american tobacco"
replace investor_city_1="onondaga & syracuse" if invname_hold_orig=="Trust & Deposit Company" & book_year_hold==1908 & cname_hold_temp=="monroe brewing (rochester new york)"
replace investor_city_1="madrid/new york" if invname_hold_orig=="Union & Phenix Espanol Ins. Co. Madrid" & book_year_hold==1911 & cname_hold_temp=="atchison topeka and santa fe"
replace investor_city_1="pittsburgh" if invname_hold_orig=="Union Trust Company of rittsburgh" & book_year_hold==1911 & cname_hold_temp=="new york shipbuilding"
replace investor_city_1="new york" if invname_hold_orig=="United States Life Insurance Company  New York" & book_year_hold==1911 & cname_hold_temp=="american telegraph and cable"
replace investor_city_1="new haven" if invname_hold_orig=="United Workmen of Connecticut (Ancient Order)" & book_year_hold==1911 & cname_hold_temp=="atlantic coast line"
replace investor_city_1="warren" if invname_hold_orig=="Warren Savings Bank" & book_year_hold==1911 & cname_hold_temp=="birmingham water works (alabama)"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="western maryland"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1908 & cname_hold_temp=="fidelity trust philadelphia pennsylvania"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="new york and richmond gas"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="southern pacific railroad"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="new york central lines"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="missouri pacific"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="hackensack water (new jersey)"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="third avenue"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1908 & cname_hold_temp=="third avenue"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="north hudson county"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="hackensack water (new jersey)"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1908 & cname_hold_temp=="hackensack water (new jersey)"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="norfolk and western"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="new york jsusquehanna and western"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1908 & cname_hold_temp=="new york jsusquehanna and western"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1908 & cname_hold_temp=="new york and new jersey ferry"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="new york jsusquehanna and western"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="new york and richmoxd georgia scompany"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="pacific gas and electric"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="southern pacific railroad"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="norfolk and western pocahontas coal and coke"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1908 & cname_hold_temp=="southern pacific railroad"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1913 & cname_hold_temp=="southern railway"
replace investor_city_1="weehawken" if invname_hold_orig=="Weehawken Trust Company" & book_year_hold==1908 & cname_hold_temp=="norfolk and western pocahontas coal and coke"
replace investor_city_1="weehawken" if invname_hold_orig=="Weeliawken Trust Company" & book_year_hold==1911 & cname_hold_temp=="north hudson county"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="westfield" if invname_hold_orig=="Westfield Savings Bank." & book_year_hold==1913 & cname_hold_temp=="aroostook northern"
replace investor_city_1="weymouth" if invname_hold_orig=="Weymouth Savings Bank Weymouth" & book_year_hold==1913 & cname_hold_temp=="lynn and boston"
replace investor_city_1="winsted" if invname_hold_orig=="Winsted Savings Bank. Winsted" & book_year_hold==1911 & cname_hold_temp=="atlantic coast line"
replace investor_city_1="worcester" if invname_hold_orig=="Worcester County Institution for Savings" & book_year_hold==1911 & cname_hold_temp=="illinois central"
replace investor_city_1="worcester" if invname_hold_orig=="Worcester Five Cents Savings Bank. Worcester" & book_year_hold==1908 & cname_hold_temp=="west end street"

replace investor_city_1="fall river" if strpos(invname_hold_orig,"Fall River Five Cents Savins") & strpos(invname_hold_orig,"Bank. Fall River") & book_year_hold==1913 & cname_hold_temp=="northwestern union"
replace investor_city_1="london/new york" if invname_hold_orig=="Sun Insurance Office London" & book_year_hold==1908 & cname_hold_temp=="southern railway"
replace investor_city_1="london/new york" if invname_hold_orig=="Phoenix Assur. Co  Ltd  London" & book_year_hold==1911 & cname_hold_temp=="norfolk and western pocahontas coal and coke"
replace investor_city_1="london/new york" if invname_hold_orig=="Northern Assurance Co  London" & book_year_hold==1911 & cname_hold_temp=="norfolk and western"
replace investor_city_1="liverpool/new york" if invname_hold_orig=="Royal Insurance Co Liverpool" & book_year_hold==1913 & cname_hold_temp=="pere marquette"
replace investor_city_1="london/toronto" if invname_hold_orig=="Star Assurance Society London" & book_year_hold==1913 & cname_hold_temp=="london street"
replace investor_city_1="london/new york" if invname_hold_orig=="Commercial Union As. Co.. London/New York. Eng./N. Y" & book_year_hold==1908 & cname_hold_temp=="chicago st louis and new orleans"
replace investor_city_1="london/new york" if invname_hold_orig=="Northern Assurance Co.. London" & book_year_hold==1911 & cname_hold_temp=="louisville and nashville"
replace investor_city_1="munich/new york" if invname_hold_orig=="Munich Re-Insurance Co  Munich" & book_year_hold==1911 & cname_hold_temp=="norfolk and western"
replace investor_city_1="stettin/new york" if invname_hold_orig=="Prussian National Ins. Co. Stettin" & book_year_hold==1911 & cname_hold_temp=="louisville and nashville evansville henderson and nashville division"
replace investor_city_1="wilkes barre" if invname_hold_orig=="people's bank of wilkes barre" & book_year_hold==1911 & cname_hold_temp=="missouri pacific"
replace investor_city_1="buffalo" if invname_hold_orig=="Buffalo Loan" & book_year_hold==1908 & cname_hold_temp=="cataract power and conduit"
replace investor_city_1="philadelphia" if invname_hold_orig=="Spring lake and sea girt company Stock" & book_year_hold==1911 & cname_hold_temp=="springfield water (pennsylvania)"
replace investor_city_1="wilkes barre" if invname_hold_orig=="people's bank of wilkes barre" &cname_hold_temp=="missouri pacific"

replace $x=strtrim($x)
replace $x=stritrim($x)
