replace investor_city_hold=proper(investor_city_hold)
replace invname_hold_temp="home savings bank" if invname_hold_orig=="ome Savings Bank"
replace invname_hold_temp="athol savins bank" if invname_hold_orig=="nol Savings Bank"
replace invname_hold_temp="augusta savings bank" if invname_hold_orig=="3ta Savings Bank"
replace invname_hold_temp="people savings bank" if invname_hold_orig=="s Savings Bank"
replace invname_hold_temp="bridgeport savings bank" if invname_hold_orig=="port Savings Bank"
replace invname_hold_temp="stunner savings bank" if invname_hold_orig=="nner Savings Bank"
replace invname_hold_temp="fairfield Savings Bank." if invname_hold_orig=="rfield Savings Bank."
replace invname_hold_temp="gorham savings bank" if invname_hold_orig=="ham Savings Bank"
replace invname_hold_temp="lexington savings bank" if invname_hold_orig=="Savings Bank"
replace invname_hold_temp="medford savings bank" if invname_hold_orig=="dford Savings Bank"
replace invname_hold_temp="meriden savings bank" if invname_hold_orig=="en Savings Bank"
replace invname_hold_temp="city savings bank" if invname_hold_orig=="ty Savings Bank"
replace invname_hold_temp="meriden savings bank" if invname_hold_orig=="n Savings Bank"
replace invname_hold_temp="middletown savings bank" if invname_hold_orig=="town Savings Bank"
replace invname_hold_temp="groton savings bank" if invname_hold_orig=="on Savings Bank"
replace invname_hold_temp="mariners savings bank" if invname_hold_orig=="ers' Savings Bank"
replace invname_hold_temp="newtown savings bank" if invname_hold_orig=="Own Savings Bank"
replace invname_hold_temp="norwich savings bank" if invname_hold_orig=="avings Bank"
replace invname_hold_temp="ridgefield savings bank" if invname_hold_orig=="eld Savings Bank"
replace invname_hold_temp="people savings bank" if invname_hold_orig==";'a Savings Bank"
replace invname_hold_temp="somersworth savings bank" if invname_hold_orig=="worth Savings Bank"
replace invname_hold_temp="stamford savings bank" if invname_hold_orig=="ford Savings Bank"
replace invname_hold_temp="stamford savings bank" if invname_hold_orig=="d Savings Bank"
replace invname_hold_temp="taunton savings bank" if invname_hold_orig=="mton Savings Bank"
replace invname_hold_temp="wakefield savings bank" if invname_hold_orig=="befield Savings Bank"
replace invname_hold_temp="walden savings bank" if invname_hold_orig=="den Savings Bank"
replace invname_hold_temp="winsted savings bank" if invname_hold_orig=="ed Savings Bank"
replace invname_hold_temp="republic life insurance" if invname_hold_orig=="lie Life Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Bom Fire Insurance Company"
replace invname_hold_temp="aetna life insurance" if invname_hold_orig=="na Life Insurance Company"
replace invname_hold_temp="connecticut general life insurance" if invname_hold_orig=="Life Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="Dome Life Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Hume Fire Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="Hone Life Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="rne Life Insurance Company"
replace invname_hold_temp="home life insurance" if invname_hold_orig=="Rome Life Insurance Company"
replace invname_hold_temp="scranton life insurance" if invname_hold_orig=="ton Life Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Bone Fire Insurance Company"
replace invname_hold_temp="home fire insurance" if invname_hold_orig=="Homo Fire Insurance Company"
replace invname_hold_temp="wildey savings bank" if invname_hold_orig=="Wildey Savings Bank"
replace invname_hold_temp="wildey savings bank" if invname_hold_orig=="WUdey Savings Bank"
replace invname_hold_temp="wildey savings bank" if invname_hold_orig=="Wlldey Savings Bank"
replace invname_hold_temp="malden savings bank" if invname_hold_orig=="Male en Savings Bank"
replace invname_hold_temp="malden savings bank" if invname_hold_orig=="Malden Savings Bank"
replace invname_hold_temp="meriden savings bank" if invname_hold_orig=="Merlden Savings Bank"
replace invname_hold_temp="hampden savings bank" if invname_hold_orig=="Cnmden Savings Bank"
replace invname_hold_temp="salem savings bank" if invname_hold_orig=="Salem Savings Bank"
replace invname_hold_temp="hampden savings bank" if invname_hold_orig=="Campden Savings Bank"
replace invname_hold_temp="walden savings bank" if invname_hold_orig=="Walden Savings Bank"
replace invname_hold_temp="warren savings bank" if invname_hold_orig=="Warren Savings Bank"
replace invname_hold_temp="astor trust" if invname_hold_orig=="Astir Trust Company"
replace invname_hold_temp="astor trust" if invname_hold_orig=="stor Trust Company"
replace invname_hold_temp="astor trust" if invname_hold_orig=="istor Trust Company"
replace invname_hold_temp="astor trust" if invname_hold_orig=="Astor Trust Company"
replace invname_hold_temp="willimantic trust" if invname_hold_orig=="antic Trust Company"
replace invname_hold_temp="easton trust" if invname_hold_orig=="Eastern Trust Company"
replace invname_hold_temp="easton trust" if invname_hold_orig=="Eastlan Trust Company"
replace invname_hold_temp="franklin fire insurance" if invname_hold_orig=="Franklin F ire Insurance Company"
replace invname_hold_temp="franklin fire insurance" if invname_hold_orig=="Franklin l ire Insurance Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="Monton Mutual Fire Insurance Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="Minion Mutual Fire Insurance Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="Manton Mutual Fire Insurance Company"
replace invname_hold_temp="mechanics savings bank" if invname_hold_orig=="hanics' Savings Bank"
replace invname_hold_temp="mechanics savings bank" if invname_hold_orig=="Panics'Savings Bank"
replace invname_hold_temp="slater trust" if invname_hold_orig=="Sinter Trust Company"
replace invname_hold_temp="slater trust" if invname_hold_orig=="Slater Trust Company"
replace invname_hold_temp="dollar savings bank" if invname_hold_orig=="Hollar Savings Bank"
replace invname_hold_temp="dollar savings bank" if invname_hold_orig=="Dnllnr Snvings Bnnk"
replace invname_hold_temp="dorchester savings bank" if invname_hold_orig=="Dorcester Savings Bank."
replace invname_hold_temp="aetna insurance" if invname_hold_orig=="na Insurance Company"
replace invname_hold_temp="sea insurance" if invname_hold_orig=="Sea Insurance Company  Ltd"
replace invname_hold_temp="sun insurance" if invname_hold_orig=="Sun Insurance Company"
replace invname_hold_temp="home insurance" if invname_hold_orig=="Dome Insurance company"
replace invname_hold_temp="home insurance" if invname_hold_orig=="Home Insurance Company"
replace invname_hold_temp="social union assurance" if invname_hold_orig=="he Insurance Company"
replace invname_hold_temp="cranford trust" if invname_hold_orig=="Cranford Trust Company"
replace invname_hold_temp="frankford trust" if invname_hold_orig=="Frankfort Trust Company"
replace invname_hold_temp="frankford trust" if invname_hold_orig=="Frankford Trust Company"
replace invname_hold_temp="providence institution for savings" if invname_hold_orig=="Providence Institution for Savings,"
replace invname_hold_temp="provident institution for savings" if invname_hold_orig=="Provident Institution tor Savings"
replace invname_hold_temp="provident institution for savings" if invname_hold_orig=="Provident Institution for Savings,"
replace invname_hold_temp="providence institution for savings" if invname_hold_orig=="Provide e Institution for Savings"
replace invname_hold_temp="morristown trust" if invname_hold_orig=="Morristown Trust Company"
replace invname_hold_temp="norristown trust" if invname_hold_orig=="Norristown Trust Company"
replace invname_hold_temp="albany trust" if invname_hold_orig=="Albany Trut Company"
replace invname_hold_temp="albany trust" if invname_hold_orig=="Albany Trust Company"
replace invname_hold_temp="albany trust" if invname_hold_orig=="Alba Trust Company"
replace invname_hold_temp="merrimac river savings bank" if invname_hold_orig=="merrimack Kiver Savings Bank"
replace invname_hold_temp="merrimac river savings bank" if invname_hold_orig=="Merrimack River Savings Bank"
replace invname_hold_temp="merrimac river savings bank" if invname_hold_orig=="merimackRiver Savings Bank"
replace invname_hold_temp="gardner savings bank" if invname_hold_orig=="Gardner Savings Bank"
replace invname_hold_temp="gardiner savings bank" if invname_hold_orig=="Gardiner Savings Bank"
replace invname_hold_temp="gardner savings bank" if invname_hold_orig=="Gardner Saiings Bank"
replace invname_hold_temp="marine insurance" if invname_hold_orig=="m Marine Insurance Company  Ltd."
replace invname_hold_temp="maine insurance" if invname_hold_orig==">me Insurance Company"
replace invname_hold_temp="providence mutual fire insurance" if invname_hold_orig=="Providence Mutual Fir Insurance Company"
replace invname_hold_temp="providence mutual life insurance" if invname_hold_orig=="Providence Mutual lire Insurance Company"
replace invname_hold_temp="providence mutual fire insurance" if invname_hold_orig=="Providence Mutual Fire Insurance Company"
replace invname_hold_temp="salisbury savings society" if invname_hold_orig=="bury Savings Society."
replace invname_hold_temp="norwalk savings society" if invname_hold_orig=="Ik Savings Society"
replace invname_hold_temp="norwalk savings society" if invname_hold_orig=="ralk Savings Society"
replace invname_hold_temp="norwalk savings society" if invname_hold_orig=="ilk Savings Society"
replace invname_hold_temp="norwich savings society" if invname_hold_orig=="ich Savings Society"
replace invname_hold_temp="hackensack trust" if invname_hold_orig=="lack Trust Company"
replace invname_hold_temp="land trust" if invname_hold_orig=="Land Trust Company"
replace invname_hold_temp="reading trust" if invname_hold_orig=="ling Trust Company"
replace invname_hold_temp="manton mutual fire insurance" if invname_hold_orig=="ton Mutual Fire Insurance Company"
replace invname_hold_temp="worcester mutual fire insurance" if invname_hold_orig=="ter Mutual Fire Insurance Company"
replace invname_hold_temp="new england mutual life insurance" if invname_hold_orig=="New England Mutual I.ife Insurance Company"
replace invname_hold_temp="nation five cents savings bank" if invname_hold_orig=="Natiok Five Cents Savings Bank"
replace invname_hold_temp="john hancock mutual fire insurance" if invname_hold_orig=="John Havock Mutual Life Insurance Company"
replace invname_hold_temp="order of the golden seal" if invname_hold_orig=="Order of the Golden Sed"
replace invname_hold_temp="order of the golden seal" if invname_hold_orig=="Order of the Golden Seal"
replace invname_hold_temp="order of the golden seal" if invname_hold_orig=="Order of the Colder Seal"
replace invname_hold_temp="east boston savings bank" if invname_hold_orig=="st Boston Savings Bank"
replace invname_hold_temp="allemania fire insurance" if invname_hold_orig=="Allemania Fire Insurance Company"
replace invname_hold_temp="allemania fire insurance" if invname_hold_orig=="Allemama Fire Insurance Company"
replace invname_hold_temp="erie county savings bank" if invname_hold_orig=="Ene County Savings Bank"
replace invname_hold_temp="monroe county savings bank" if invname_hold_orig=="roe County Savings Bank"
replace invname_hold_temp="rhinebeck savings bank" if invname_hold_orig=="llhinebeck Savings Bank"
replace invname_hold_temp="rhinebeck savings bank" if invname_hold_orig=="Rliinebeck Savings Bank"
replace invname_hold_temp="rhinebeck savings bank" if invname_hold_orig=="Rhinebeck Savings Bank"
replace invname_hold_temp="state bank of dunsmuir" if invname_hold_orig=="Mate Bank of Dunsmuir"
replace invname_hold_temp="colonial trust" if invname_hold_orig=="Colonial Trust Company"
replace invname_hold_temp="colonial trust" if invname_hold_orig=="ilonial Trust Company"
replace invname_hold_temp="hamburg savings bank" if invname_hold_orig=="amburg Savings Bank"
replace invname_hold_temp="flatbush trust" if invname_hold_orig=="Flatburg Trust Company"
replace invname_hold_temp="rome savings bank" if invname_hold_orig=="Koine Savings Bank"
replace invname_hold_temp="orient insurance" if invname_hold_orig=="ricnt Insurance Company"
replace invname_hold_temp="orient insurance" if invname_hold_orig=="ient Insurance Company"
replace invname_hold_temp="orient insurance" if invname_hold_orig=="Orient Insurance Company"
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Assurance Society of the U"
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Assurance Society of the U. S."
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Insurance Socity"
replace invname_hold_temp="equitable life assurance society" if invname_hold_orig=="Equitable Life Assurance Society"
replace invname_hold_temp="banker trust" if invname_hold_orig=="Jankers Trust Company"
replace invname_hold_temp="banker trust" if invname_hold_orig=="Bankets Trust Company"
replace invname_hold_temp="union trust" if invname_hold_orig=="Union Tmst Company"
replace invname_hold_temp="nassau county trust" if invname_hold_orig=="Nasaa County Trust Company"
replace invname_hold_temp="nassau county trust" if invname_hold_orig=="Nassau County Trust Company"
replace invname_hold_temp="hudson trust" if invname_hold_orig=="idson Trust Company"
replace invname_hold_temp="holyoke mutual fire insurance" if invname_hold_orig=="tlyoke Mutual Fire Insurance Company"
replace invname_hold_temp="first mortgage guaranty and trust" if invname_hold_orig=="Firt Mortgnge Guaranty & Trust Company"
replace invname_hold_temp="rittenhouse trust" if invname_hold_orig=="Kittenbouse Trust Company"
replace invname_hold_temp="farmers and mechanic savings bank" if invname_hold_orig=="Farmere & Mechanics' Savings Bank"
replace invname_hold_temp="merchants and farmers mutual fire insurance" if invname_hold_orig=="Merchants' & Farmers' M.utual Fire Insurance Co."
replace invname_hold_temp="cape ann savings bank" if invname_hold_orig=="Cape Anil Savings Bank"
replace invname_hold_temp="national fire insurance" if invname_hold_orig=="ional Fire Insurance Co."
replace invname_hold_temp="underwriters of new york and boston lloyds" if invname_hold_orig=="Underwriters of New York and Boston Lloyds"
replace invname_hold_temp="underwriters of new york and boston lloyds" if invname_hold_orig=="Underwriters at New York & Boston, Lloyds"
replace invname_hold_temp="underwriters of new york and boston lloyds" if invname_hold_orig=="Underwriters of New York at Boston Lloyds"
replace invname_hold_temp="apollo trust" if invname_hold_orig=="Apollo Trust Company"
replace invname_hold_temp="apollo trust" if invname_hold_orig=="ApoUo Trust Company"
replace invname_hold_temp="national savings bank" if invname_hold_orig=="Nation Savings Bank"
replace invname_hold_temp="middlesex mutual assurance" if invname_hold_orig=="Middlesex Mutual Assurance Company"
replace invname_hold_temp="middlesex mutual insurance" if invname_hold_orig=="Middlesex Mutual Insurance Company"
replace invname_hold_temp="glen lyon bank" if invname_hold_orig=="lien Lyon Bank"
replace invname_hold_temp="standard fire assurance" if invname_hold_orig=="andard Fire Insurance Company"
replace invname_hold_temp="marine insurance company" if invname_hold_orig=="Ma  rine Insurance Company, Ltd"
replace invname_hold_temp="sun mutual insurance" if invname_hold_orig=="Snn Mutual Insurance Company"
replace invname_hold_temp="institution for savings newburyport and vicinity" if invname_hold_orig=="Institution for Savings, Newburyport and Vicin"
replace invname_hold_temp="institution for savings newburyport and vicinity" if invname_hold_orig=="Institution for Savings Newburyport & Vic"
replace invname_hold_temp="employers liability assurance" if invname_hold_orig=="Employers' Liability Assur. Corp."
replace invname_hold_temp="employers liability assurance" if invname_hold_orig=="Employer's Liability Ass. Corp."
replace invname_hold_temp="monroe county savings bank" if invname_hold_orig=="Afonroe County Savings Bank"
replace invname_hold_temp="sun life assurance" if invname_hold_orig=="Sim Life Assurance Company"
replace invname_hold_temp="boiler inspection and insurance" if invname_hold_orig=="BoUer Inspection & Insurance Company"
replace invname_hold_temp="guardian assurance" if invname_hold_orig=="Cardian Assurance Co., Ltd."
replace invname_hold_temp="insurance of north america" if invname_hold_orig=="wurance Company of North America"
replace invname_hold_temp="insurance of north america" if invname_hold_orig=="nirance Company of North America"
replace invname_hold_temp="provident institution for savings" if invname_hold_orig=="evident Institution for Savings"
replace invname_hold_temp="providence institution for savings" if invname_hold_orig=="Evidence Institution for Savings"
replace invname_hold_temp="illinois life insurance" if invname_hold_orig=="Ill.inois Life Insurance Company"
replace invname_hold_temp="illinois fire insurance" if invname_hold_orig=="Ill.inois Fire Insurance Company"
replace invname_hold_temp="hanover fire insurance" if invname_hold_orig=="over Fire Insurance Company"
replace invname_hold_temp="hanover fire insurance" if invname_hold_orig=="er Fire Insurance Company"
replace invname_hold_temp="essex county trust" if invname_hold_orig==">ex County Trust Company"
replace invname_hold_temp="nassau county trust" if invname_hold_orig=="iu County Trust Company"
replace invname_hold_temp="teutonia fire insurance" if invname_hold_orig=="Teutoma Fire Insurance Company"
replace invname_hold_temp="people savings bank" if invname_hold_orig=="'copies' Savings Bank"
replace invname_hold_temp="general accid fire and life assur" if invname_hold_orig=="General Accid,Fire & Life Assur, Corp,"
replace invname_hold_temp="general accid fire and life assur" if invname_hold_orig=="General Acc.. Fire & Life Assur. Corp. Ltd."
replace invname_hold_temp="new england mutual life insurance" if invname_hold_orig=="land" & investor_city_hold=="Boston"
replace invname_hold_temp="iona savings bank" if invname_hold_orig=="lona Savings Bank"



